### ISSUE TITLE
Empty lines in the --fastx --other files

### ISSUE THREAD

**Issue by nicolasDelhomme** [biocore/sortmerna#115]
Hej Jenya!

Hope this message finds you well!

Long time we haven't talked, which is a good thing when it comes to talking about bugs I guess ;-)

I have had some issues using sortmerna 2.x where I have had spurious empty lines occurring in the fastq files created using --fastx --other --paired_in using multithreading. 

My context is different from the standard use of sortmerna as I use it to assess the amount of rRNA in my poly-dT RNA-Seq samples (and for filtering them).

The bug is hard to reproduce as it happens inconsistently in a few% of all files I proceed. But I believe that what happens is that threads are returning asynchronously the results in the final file (or you maybe sort the chunks?), so that in some instances the code in src/outputformats.cpp at line 533 and 583 (as of today in the repos) - i.e. `if ( *end_read == '\n' ) otherreads << "\n";` introduces an extra empty line in the body of the fastq file.

This is an issue because a number of tools stop on an empty line in a fastq file, de facto discarding what's left of the file.

Since I've commented out that line and recompiled, I have not had the issue anymore, but I have not processed so many files yet. I'm using the LTS Ubuntu 14.04 on HPE G7 servers (AMD Opteron) and have compiled using gcc
`gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4`

Let me know if you need any more infos. As I said, it's hard to reproduce, but if I manage to get a reproducible example, I'll grant you access to our machine if you want to take a look (whether I have a reproducible example or not, actually ;-)).

Finally, as a side note, I have encountered an issue with sortmerna v1.9; so it's obviously outdated, but I thought I should still share it :-). When there's only one sequence in the index, sortmerna 1.9 never returns any hit to that sequence. I have not checked if the first sequence is always ignored when there are more sequences in the index, but as I said, that's an outdated version and it does not happen in version 2.x.

Cheers,

Nico

**Comment by ekopylova** [comment]
Hi Nicolas,
Thanks for reporting this. I will definitely take a look and add to the add_zlib [PR](#111).
Jenya

**Comment by nicolasDelhomme** [comment]
Awesome :-)
---------------------------------------------------------------
Nicolas Delhomme, PhD

UPSC bioinformatics facility Manager
Umeå Plant Science Center,
Swedish University for Agricultural 
Sciences (SLU) and Umeå University

Tel: +46 90 786 5478
Email: nicolas.delhomme@umu.se
SLU - Umeå universitet
Umeå S-901 87 Sweden
---------------------------------------------------------------

**Comment by ekopylova** [comment]
Sequence input/output code has been throughly updated, this issue should no longer apply. Please create a new issue if that is still the case (SortMeRNA 3).
