### ISSUE TITLE
option to accept forward + reverse reads

### ISSUE THREAD

**Issue by ekopylova** [biocore/sortmerna#118]

**Comment by hongenxu** [comment]
Hi, 
when will this option be available?

**Comment by ekopylova** [comment]
I will try for January. Thanks for you interest!

**Comment by biocodz** [comment]
Implemented in [release 4.0](https://github.com/biocore/sortmerna/releases/tag/v4.0.0)
Two `-reads` can be specified for paired reads input like
`sortmerna -ref file_REF -reads file_FWD -reads file_REV ...`
