### ISSUE TITLE
Discrepancy between results in log file and in output fastq

### ISSUE THREAD

**Issue by rbeinart** [biocore/sortmerna#129]
Hi there,
I'm seeing a discrepancy between what is reported in the log file and the number of reads in my output files themselves. I'm running these with paired end data using the paired_out mode. Here's an example:

My log file reports
    Total reads = 33347754
    Total reads passing E-value threshold = 85682 (0.26%)
    Total reads failing E-value threshold = 33262072 (99.74%)

I interpret this as 85,682 reads are rRNA. However, when I count the number of reads in the output file rRNA output file, I get only 16,258 reads. Am I interpreting the log file incorrectly? 

Here's what I'm running:

sortmerna --ref /n/home07/rbeinart/sortmerna_databases/rRNA_databases/silva-bac-16s-id90.fasta,/n/home07/rbeinart/sortmerna_databases/index/silva-bac-16s-db:\
/n/home07/rbeinart/sortmerna_databases/rRNA_databases/silva-bac-23s-id98.fasta,/n/home07/rbeinart/sortmerna_databases/index/silva-bac-23s-db:\
/n/home07/rbeinart/sortmerna_databases/rRNA_databases/silva-arc-16s-id95.fasta,/n/home07/rbeinart/sortmerna_databases/index/silva-arc-16s-db:\
/n/home07/rbeinart/sortmerna_databases/rRNA_databases/silva-arc-23s-id98.fasta,/n/home07/rbeinart/sortmerna_databases/index/silva-arc-23s-db:\
/n/home07/rbeinart/sortmerna_databases/rRNA_databases/silva-euk-18s-id95.fasta,/n/home07/rbeinart/sortmerna_databases/index/silva-euk-18s-db:\
/n/home07/rbeinart/sortmerna_databases/rRNA_databases/silva-euk-28s-id98.fasta,/n/home07/rbeinart/sortmerna_databases/index/silva-euk-28s:\
/n/home07/rbeinart/sortmerna_databases/rRNA_databases/rfam-5s-database-id98.fasta,/n/home07/rbeinart/sortmerna_databases/index/rfam-5s-db:\
/n/home07/rbeinart/sortmerna_databases/rRNA_databases/rfam-5.8s-database-id98.fasta,/n/home07/rbeinart/sortmerna_databases/index/rfam-5.8s-db\
 --reads ./ --num_alignments 1 --fastx --paired_out --aligned BC_metaG_retry_sortmeRNA \
 --other BC_metaG_retry_sortmeRNA_non_rRNA --log -v

Any idea what's going on here? Thanks!!

**Comment by ekopylova** [comment]
The ```paired_out``` option filters any rRNA classified reads from the output FASTA/Q file which have a read pair not classified as rRNA. Your output FASTA/Q for ```--aligned``` results will only have rRNA reads where both reads are rRNA, whereas the log file outputs the actual number of rRNA reads (85682) even when the pair is not classified as rRNA. 

Please see section 4.3.2 in the user manual for further explanation.
