### ISSUE TITLE
PE reads: after running SortMeRNA, R1 and R2 end up having different numbers of reads

### ISSUE THREAD

**Issue by lfaller** [biocore/sortmerna#133]
Hi all,

I have paired end reads and I am running sortmerna as follows:

1) merge PE reads using the `scripts/merge-paired-reads.sh` script
2) sortmerna
3) unmerge reads using the `scripts/unmerge-paired-reads.sh` script

In some instances, I found log files that look like this:

```
 Command: /home/lina/sortmerna/sortmerna --ref /home/lina/sortmerna/rRNA_databases/silva-bac-16s-id90.fasta,/home/lina/sortmerna/index/silva-bac-16s-db:/home/lina/sortmerna/rRNA_databases/silva-bac-23s-id98.fasta,/home/lina/sortmerna/index/silva-bac-23s-db:/home/lina/sortmerna/rRNA_databases/silva-arc-16s-id95.fasta,/home/lina/sortmerna/index/silva-arc-16s-db:/home/lina/sortmerna/rRNA_databases/silva-arc-23s-id98.fasta,/home/lina/sortmerna/index/silva-arc-23s-db:/home/lina/sortmerna/rRNA_databases/silva-euk-18s-id95.fasta,/home/lina/sortmerna/index/silva-euk-18s-db:/home/lina/sortmerna/rRNA_databases/silva-euk-28s-id98.fasta,/home/lina/sortmerna/index/silva-euk-28s:/home/lina/sortmerna/rRNA_databases/rfam-5s-database-id98.fasta,/home/lina/sortmerna/index/rfam-5s-db:/home/lina/sortmerna/rRNA_databases/rfam-5.8s-database-id98.fasta,/home/lina/sortmerna/index/rfam-5.8s-db --reads /tmp/lina/sortmerna_K//merged.fastq --num_alignments 1 --fastx --aligned /tmp/lina/sortmerna_K//K_rrna_reads --other /tmp/lina/sortmerna_K//K_rrna_free_reads.fastq fastq --log -v --blast 1

...

 Results:
    Total reads = 872
    Total reads passing E-value threshold = 23 (2.64%)
    Total reads failing E-value threshold = 849 (97.36%)
    Minimum read length = 4
    Maximum read length = 76
    Mean read length = 50
```

When I count the number of reads in the unmerged rRNA-free R1 and R2 files, I find that R1 contains 425 reads and R2 contains 424. This adds up to the 849 reads. However, the resulting files now have unequal number of reads which proves problematic for downstream analysis.

I can perform an additional filtering step that just filters out unpaired reads, but I figured it was worth checking here if there is a better solution.

Thanks!

**Comment by ekopylova** [comment]
I would suggest using the ```--paired_in``` or ```--paired_out``` option which will result in equal number of read counts in both files. Please read more about these options in section 4.3.2 in the [user manual](https://github.com/biocore/sortmerna/blob/master/SortMeRNA-User-Manual-2.1.pdf) and let me know if you have further questions. Thanks!

**Comment by lfaller** [comment]
Great, thanks for the tip!
