### ISSUE TITLE
ERROR: '?' is not one of the options.

### ISSUE THREAD

**Issue by Transmystical** [biocore/sortmerna#134]
Dear Sortmerna Gurus: 

I am trying to put in my command to execute the sortmerna algorithm and I keep getting this error: 
"ERROR: '?' is not one of the options"

Here is my command-line that I am using (on our cluster):
sortmerna --ref /sortmerna/SILVA_128_SSURef_Nr99_tax_silva.fasta,/sortmerna/silva_index/silva_index --reads M40A_R1.R1.fasta --aligned M40A_sortmerna --fastx --log --paired_in 

Where the directory silva_index directory contains the following: 
$ls silva_index
silva_index.bursttrie_0.dat  silva_index.bursttrie_1.dat  silva_index.kmer_0.dat  silva_index.kmer_1.dat  silva_index.pos_0.dat  silva_index.pos_1.dat silva_index.stats

Any insight into why this command isn't executing would be so much appreciated!

Thank you!
Joany

**Comment by ekopylova** [comment]
Hi Joany,
I've created a forum for sortmerna help and answered your question there (see [thead](https://groups.google.com/forum/#!topic/sortmerna/tW9b9Td9wus)). Could you reply to my questions there? Thanks!

**Comment by ppericard** [comment]
It seems the forum is not public and you need to subscribe to see the threads... Wouldn't it be better if it were public ? I'm also thinking SEO.

**Comment by emailjack** [comment]
Would you please invite me to the sortmerna forum, it seems to be private. I am having the same issue.

Cheers

**Comment by ekopylova** [comment]
Hello,

Full paths should be used, can you try that?

Jenya

**Comment by emailjack** [comment]
Hi Jenya

I used this:


/fastdata/mdt16j/sortmerna-2.1/sortmerna --ref /fastdata/mdt16j/sortmerna-2.1/rRNA_databases/silva-euk-28s-id98.fasta,/fastdata/mdt16j/sortmerna-2.1/index/silva-euk-28s-db:/fastdata/mdt16j/sortmerna-2.1/rRNA_databases/silva-euk-18s-id95.fasta,/fastdata/mdt16j/sortmerna-2.1/index/silva-euk-18s-db –-reads /fastdata/mdt16j/Trimmomatic_Files/Brain_GRmut_1_Trimmed.fastq --aligned Brain_GRmut_1_Trimmed_sortmerna --num_alignments 1 --fastx –-other Brain_GRmut_1_non_rna -–log --v


and I still get the same error message. I am using version 2.1. I believe I have indexed two databases correctly as I get:


./indexdb_rna --ref /fastdata/mdt16j/sortmerna-2.1/rRNA_databases/silva-euk-28s-id98.fasta,/fastdata/mdt16j/sortmerna-2.1/index/silva-euk-28s-db:/fastdata/mdt16j/sortmerna-2.1/rRNA_databases/silva-euk-18s-id95.fasta,/fastdata/mdt16j/sortmerna-2.1/index/silva-euk-18s-db -v


  Program:     SortMeRNA version 2.1, 01/02/2016

  Copyright:   2012-16 Bonsai Bioinformatics Research Group:

               LIFL, University Lille 1, CNRS UMR 8022, INRIA Nord-Europe

               2014-16 Knight Lab, Department of Pediatrics, UCSD, La Jolla,

  Disclaimer:  SortMeRNA comes with ABSOLUTELY NO WARRANTY; without even the

               implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

               See the GNU Lesser General Public License for more details.

  Contact:     Evguenia Kopylova, jenya.kopylov@gmail.com

               Laurent Noé, laurent.noe@lifl.fr

               Hélène Touzet, helene.touzet@lifl.fr



  Parameters summary:

    K-mer size: 19

    K-mer interval: 1

    Maximum positions to store per unique K-mer: 10000


  Total number of databases to index: 2


  Begin indexing file /fastdata/mdt16j/sortmerna-2.1/rRNA_databases/silva-euk-28s-id98.fasta under index name /fastdata/mdt16j/sortmerna-2.1/index/silva-euk-28s-db:

  Collecting sequence distribution statistics ..  done  [0.235444 sec]


  start index part # 0:

    (1/3) building burst tries .. done  [5.338746 sec]

    (2/3) building CMPH hash .. done  [17.436676 sec]

    (3/3) building position lookup tables .. done [14.921360 sec]

    total number of sequences in this part = 4935

      temporary file was here: /tmp/sortmerna_keys_2692.txt

      writing kmer data to /fastdata/mdt16j/sortmerna-2.1/index/silva-euk-28s-db.kmer_0.dat

      writing burst tries to /fastdata/mdt16j/sortmerna-2.1/index/silva-euk-28s-db.bursttrie_0.dat

      writing position lookup table to /fastdata/mdt16j/sortmerna-2.1/index/silva-euk-28s-db.pos_0.dat

      writing nucleotide distribution statistics to /fastdata/mdt16j/sortmerna-2.1/index/silva-euk-28s-db.stats

    done.



  Begin indexing file /fastdata/mdt16j/sortmerna-2.1/rRNA_databases/silva-euk-18s-id95.fasta under index name /fastdata/mdt16j/sortmerna-2.1/index/silva-euk-18s-db:

  Collecting sequence distribution statistics ..  done  [0.215582 sec]


  start index part # 0:

    (1/3) building burst tries .. done  [5.097530 sec]

    (2/3) building CMPH hash .. done  [3.877501 sec]

    (3/3) building position lookup tables .. done [16.717706 sec]

    total number of sequences in this part = 7348

      temporary file was here: /tmp/sortmerna_keys_2692.txt

      writing kmer data to /fastdata/mdt16j/sortmerna-2.1/index/silva-euk-18s-db.kmer_0.dat

      writing burst tries to /fastdata/mdt16j/sortmerna-2.1/index/silva-euk-18s-db.bursttrie_0.dat

      writing position lookup table to /fastdata/mdt16j/sortmerna-2.1/index/silva-euk-18s-db.pos_0.dat

      writing nucleotide distribution statistics to /fastdata/mdt16j/sortmerna-2.1/index/silva-euk-18s-db.stats

    done.


I am unsure what the matter is still. Any advice please?


________________________________

**Comment by ekopylova** [comment]
Hello,
Could you first try using parameter "-v" instead of "--v" in your sortmerna command?
If that wasn't the issue, could you try running with just one database (and "-v")?

/fastdata/mdt16j/sortmerna-2.1/sortmerna --ref /fastdata/mdt16j/sortmerna-2.1/rRNA_databases/silva-euk-28s-id98.fasta,/fastdata/mdt16j/sortmerna-2.1/index/silva-euk-28s-db –-reads /fastdata/mdt16j/Trimmomatic_Files/Brain_GRmut_1_Trimmed.fastq --aligned Brain_GRmut_1_Trimmed_sortmerna --num_alignments 1 --fastx –-other Brain_GRmut_1_non_rna -–log -v

**Comment by emailjack** [comment]
I got the same error:

ERROR: '?' is not one of the options.



I copy and pasted my edited code in, removing - from --v (-v) first. This did not work.
I copy and pasted my edited code in, then removed the second indexed database. This did not work.

I copy your edited code from previous email, this did not work either.


Maybe I have installed something incorrectly? I am unsure what to do next.


Thank you for your fantastic response time. I very much appreciate it.

________________________________

**Comment by ekopylova** [comment]
Normally this error is due to incorrect command line parameters. Could you try running the latest SortMeRNA version however, since we are not supporting development of 2.1 any longer. We can help with command line instructions or installation if you require.

**Comment by emailjack** [comment]
Ok.

I have used to get the newer sortmerna:


wget https://github.com/biocore/sortmerna/archive/v3.0.3.tar.gz

pushd sortmerna


I can't see the indexdb_rna command as the previous version. How do I index the rRNA databases now?


Cheers



________________________________

**Comment by evchambers** [comment]
Hi Jack, 

If you try installing via the convenience script you may have more luck.

wget https://github.com/biocore/sortmerna/releases/download/v3.0.3/sortmerna-3.0.3-Linux_C6.sh

Detailed instructions for the install are here
https://github.com/biocore/sortmerna#using-github-release-binaries

**Comment by ekopylova** [comment]
@emailjack Hi Jack, using pre-built binaries should be the quickest way to install. What Linux system are you using? All available binaries are listed [here](https://github.com/biocore/sortmerna/releases/tag/v3.0.3). You can also use the convenience scripts to install, try following the steps here (as suggested by @evchambers, thanks!):

https://github.com/biocore/sortmerna/blob/master/README.md#using-github-release-binaries

**Comment by biocodz** [comment]
@emailjack  Please, note the `indexdb_rna` has been changed to `indexdb` in version 3.

**Comment by biocodz** [comment]
As a side note, we are working on a release that will hide the indexing from the user all together, allow for relative paths, and add more rigorous options validation.

**Comment by biocodz** [comment]
Since the release `4.0.0` the indexing is no longer a standalone application. Relative paths are handled automatically.
