### ISSUE TITLE
paired-read alignment support

### ISSUE THREAD

**Issue by ekopylova** [biocore/sortmerna#136]

**Comment by danwiththeplan** [comment]
It would be really great if this was implemented. Since most NGS data is paired these days, this adds the requirement to interleave and then de-interleave after sortmerna, adding a lot of unnecessary steps and processing time.

**Comment by ekopylova** [comment]
Hi Dan,
I agree. We are writing a complete overhaul of the code and the new SMR will have this functionality.
Best,
Jenya

**Comment by swiddison** [comment]
Hi have you made these changes to the code yet? I just looked at the code and it looks like interleaving is still required for paired end reads (section 4.3.2).

**Comment by biocodz** [comment]
Sorry, not yet. But working on...

**Comment by biocodz** [comment]
For reference this is being developed on the branch `issue_136_paired_reads`, which also modifies the program arguments processing. The changes will result in a new release `4.x.y`

**Comment by biocodz** [comment]
[Release 4.0](https://github.com/biocore/sortmerna/releases/tag/v4.0.0) is finally out. It implements the paired reads processing as requested (takes two `-reads` options)
