### ISSUE TITLE
Same read mapped more than once on the same reference

### ISSUE THREAD

**Issue by loic-couderc** [biocore/sortmerna#137]
Hi everyone,

I encountered an unexpected behaviour when mapping my reads with SortMeRNA.
During the evaluation of the result SAM file, I could observe that some reads are mapped more than once on the same reference (no duplication or so).

I identified at least two cases:
1. The read is mapped twice with the same cigar
2. The read is mapped twice with slightly different cigar due to soft clipping.

I build a minimal set to reproduce the situation:
[dataset.tar.gz](https://github.com/biocore/sortmerna/files/1010698/dataset.tar.gz)

And below are the commands used:

## indexing
```bash
indexdb_rna --ref scaffolds.fa,idx_prefix -m 10000 -v
```
output:
```text
  Program:     SortMeRNA version 2.1b, 03/03/2016
  Copyright:   2012-16 Bonsai Bioinformatics Research Group:
               LIFL, University Lille 1, CNRS UMR 8022, INRIA Nord-Europe
               2014-16 Knight Lab:
               Department of Pediatrics, UCSD, La Jolla,
  Disclaimer:  SortMeRNA comes with ABSOLUTELY NO WARRANTY; without even the
               implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
               See the GNU Lesser General Public License for more details.
  Contact:     Evguenia Kopylova, jenya.kopylov@gmail.com
               Laurent Noé, laurent.noe@lifl.fr
               Hélène Touzet, helene.touzet@lifl.fr


  Parameters summary:
    K-mer size: 19
    K-mer interval: 1
    Maximum positions to store per unique K-mer: 10000

  Total number of databases to index: 1

  Begin indexing file scaffolds.fa under index name idx_prefix:
  Collecting sequence distribution statistics ..  done  [0.000088 sec]

  start index part # 0:
    (1/3) building burst tries .. done  [0.005356 sec]
    (2/3) building CMPH hash .. done  [0.005295 sec]
    (3/3) building position lookup tables .. done [0.001938 sec]
    total number of sequences in this part = 3
      temporary file was here: /tmp/sortmerna_keys_15230.txt
      writing kmer data to idx_prefix.kmer_0.dat
      writing burst tries to idx_prefix.bursttrie_0.dat
      writing position lookup table to idx_prefix.pos_0.dat
      writing nucleotide distribution statistics to idx_prefix.stats
    done.
```

## mapping
```bash
sortmerna --ref scaffolds.fa,idx_prefix --reads faulty_reads.fa --aligned filt_prefix --fastx --sam --blast "1" --log --best 10 --min_lis 10 -e 1.00e-05 -a 8 -v
```

output:
```text
Program:     SortMeRNA version 2.1b, 03/03/2016
  Copyright:   2012-16 Bonsai Bioinformatics Research Group:
               LIFL, University Lille 1, CNRS UMR 8022, INRIA Nord-Europe
               2014-16 Knight Lab:
               Department of Pediatrics, UCSD, La Jolla,
  Disclaimer:  SortMeRNA comes with ABSOLUTELY NO WARRANTY; without even the
               implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
               See the GNU Lesser General Public License for more details.
  Contact:     Evguenia Kopylova, jenya.kopylov@gmail.com
               Laurent Noé, laurent.noe@lifl.fr
               Hélène Touzet, helene.touzet@lifl.fr


  Computing read file statistics ... done [0.00 sec]
  size of reads file: 879 bytes
  partial section(s) to be executed: 1 of size 879 bytes
  Parameters summary:
    Number of seeds = 2
    Edges = 4 (as integer)
    SW match = 2
    SW mismatch = -3
    SW gap open penalty = 5
    SW gap extend penalty = 2
    SW ambiguous nucleotide = -3
    SQ tags are not output
    Number of threads = 8

  Begin mmap reads section # 1:
  Time to mmap reads and set up pointers [0.00 sec]

  Begin analysis of: scaffolds.fa
    Seed length = 18
    Pass 1 = 18, Pass 2 = 9, Pass 3 = 3
    Gumbel lambda = 0.583099
    Gumbel K = 0.311465
    Minimal SW score based on E-value = 41
    Loading index part 1/1 ...  done [0.02 sec]
    Begin index search ...  done [0.03 sec]
    Freeing index ...  done [0.00 sec]
    Total number of reads mapped (incl. all reads file sections searched): 5
    Writing alignments ...  done [0.00 sec]
    Writing aligned FASTA/FASTQ ...  done [0.00 sec]
```

**Comment by ppericard** [comment]
These are the alignments we get from these reads:

```
query_id 	subject_id 	%identity 	alignment_length 	mismatches 	gap_opens 	q.start 	q.end 	s.start 	s.end 	evalue 	score      cigar   
SRR606249.6025199.2 	159 	83.3 	91 	6 	11 	1 	91 	43 	144 	2.88e-18 	107  35M4D1M7D55M7S 
SRR606249.6025199.2 	159 	83.3 	91 	6 	11 	8 	98 	50 	151 	2.88e-18 	107  7S28M4D1M7D62M 
SRR606249.24492705.1 	161 	93.2 	59 	4 	0 	6 	64 	1329 	1387 	1.44e-11 	85  5S59M37S 
SRR606249.24492705.1 	161 	93.2 	59 	4 	0 	6 	64 	1329 	1387 	1.44e-11 	85  5S59M37S 
SRR606249.25652482.2 	240 	82.2 	92 	9 	9 	1 	92 	72 	172 	5.99e-16 	100  46M6D4M3D42M5S 
SRR606249.25652482.2 	240 	82.2 	92 	9 	9 	1 	92 	72 	172 	5.99e-16 	100  46M6D4M3D42M5S 
SRR606249.26931475.2 	240 	82.2 	92 	9 	9 	1 	92 	72 	172 	5.99e-16 	100  46M6D4M3D42M5S 
SRR606249.26931475.2 	240 	82.2 	92 	9 	9 	1 	92 	72 	172 	5.99e-16 	100  46M6D4M3D42M5S 
SRR606249.33106002.1 	240 	82.9 	101 	13 	5 	1 	101 	68 	171 	5.59e-17 	103  48M4D10M1I42M 
SRR606249.33106002.1 	240 	82.9 	101 	13 	5 	1 	101 	68 	171 	5.59e-17 	103  48M4D10M1I42M 
```

**Comment by ekopylova** [comment]
Hello,

With the option `--best 10`, it is expected that up to 10 best alignments per read reaching E-value = 1.00e-05 are reported. It appears all your E-values are below the threshold and reported. If you wanted only one best alignment, then `--best 1` should work.

Does that answer your question, or did you have something else in mind?

Apologies for the delayed response, we're currently focusing most of our attention of a full re-write of SortMeRNA.

Jenya

**Comment by ppericard** [comment]
Hi,

We configured SortMe to give up 10 alignements with --best 10. The problem is for some reads, SortMe reports the same alignment (or nearly the same) twice.

For example, in the above example, the read SRR606249.24492705.1 is aligned against the reference 161 twice on exactly the same positions and with the same CIGAR.

**Comment by biocodz** [comment]
If you provide the reads and references for download, I could test this with the newest version of SMR

**Comment by ppericard** [comment]
@biocodz, the dataset and the refs are linked in the first post of this issue

**Comment by biocodz** [comment]
I confirm the discrepancy using the new code. Number of alignments reported in Log and Fasta_out is 5, but SAM and BLAST both show more records.

I'm looking into the cause.

Below are the results of the tests done on the provided data.

<pre>
biocodz@ubuntu16-1:~$ indexdb --ref /home/biocodz/data/reads/scaffolds_issue_137.fasta,/home/biocodz/data/idx/scaffolds_issue_137 -v

  Program:      SortMeRNA version 3.0.0
  Copyright:    2016-2018 Clarity Genomics BVBA:
                Turnhoutseweg 30, 2340 Beerse, Belgium
                2014-2016 Knight Lab:
                Department of Pediatrics, UCSD, La Jolla
                2012-2014 Bonsai Bioinformatics Research Group:
                LIFL, University Lille 1, CNRS UMR 8022, INRIA Nord-Europe
  Disclaimer:   SortMeRNA comes with ABSOLUTELY NO WARRANTY; without even the
                implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
                See the GNU Lesser General Public License for more details.
  Contributors: Jenya Kopylova   jenya.kopylov@gmail.com
                Laurent Noé      laurent.noe@lifl.fr
                Pierre Pericard  pierre.pericard@lifl.fr
                Daniel McDonald  wasade@gmail.com
                Mikaël Salson    mikael.salson@lifl.fr
                Hélène Touzet    helene.touzet@lifl.fr
                Rob Knight       robknight@ucsd.edu


  Parameters summary:
    K-mer size: 19
    K-mer interval: 1
    Maximum positions to store per unique K-mer: 10000

  Total number of databases to index: 1

  Begin indexing file /home/biocodz/data/reads/scaffolds_issue_137.fasta under index name /home/biocodz/data/idx/scaffolds_issue_137:
  Collecting sequence distribution statistics ..  done  [0.000070 sec]

  start index part # 0:
    (1/3) building burst tries .. done  [0.006879 sec]
    (2/3) building CMPH hash .. done  [0.010969 sec]
    (3/3) building position lookup tables .. done [0.001931 sec]
    total number of sequences in this part = 3
      temporary file was here: /tmp/sortmerna_keys_2162.txt
      writing kmer data to /home/biocodz/data/idx/scaffolds_issue_137.kmer_0.dat
      writing burst tries to /home/biocodz/data/idx/scaffolds_issue_137.bursttrie_0.dat
      writing position lookup table to /home/biocodz/data/idx/scaffolds_issue_137.pos_0.dat
      writing nucleotide distribution statistics to /home/biocodz/data/idx/scaffolds_issue_137.stats
    done.

biocodz@ubuntu16-1:~$ sortmerna --ref /home/biocodz/data/reads/scaffolds_issue_137.fasta,/home/biocodz/data/idx/scaffolds_issue_137 --reads /home/biocodz/data/reads/faulty_reads_issue_137.fasta --aligned /home/biocodz/data/out/issue_137 --fastx --sam --blast 1 --log --best 10 --min_lis 10 -e 1.00e-05 -v -d /home/biocodz/data/kvdb

  Program:      SortMeRNA version 3.0.0
  Copyright:    2016-2018 Clarity Genomics BVBA:
                Turnhoutseweg 30, 2340 Beerse, Belgium
                2014-2016 Knight Lab:
                Department of Pediatrics, UCSD, La Jolla
                2012-2014 Bonsai Bioinformatics Research Group:
                LIFL, University Lille 1, CNRS UMR 8022, INRIA Nord-Europe
  Disclaimer:   SortMeRNA comes with ABSOLUTELY NO WARRANTY; without even the
                implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
                See the GNU Lesser General Public License for more details.
  Contributors: Jenya Kopylova   jenya.kopylov@gmail.com
                Laurent Noé      laurent.noe@lifl.fr
                Pierre Pericard  pierre.pericard@lifl.fr
                Daniel McDonald  wasade@gmail.com
                Mikaël Salson    mikael.salson@lifl.fr
                Hélène Touzet    helene.touzet@lifl.fr
                Rob Knight       robknight@ucsd.edu

main:55 Running task ALIGN_REPORT: 4
Readstats::calculate starting ...   Readstats::calculate done. Elapsed time: 0.00 sec. Reads processed: 5
align:374 Using default number of Processor threads equals num CPU cores: 8
Number of cores: 8 Read threads:  1 Write threads: 1 Processor threads: 8
ThreadPool:36 initialized Pool with: [10] threads
...
Cleaning directory: /home/biocodz/data/kvdb
...
Refstats:33 Index Statistics calculation Start ... Done. Time elapsed: 1.38 sec
align:414 Loading index 0 part 1/1 ... done [0.07] sec
align:425 Loading references  ... done [0.00] sec
...
read:135 reader_0 thread: 139819255318272 done. Elapsed time: 0.00 sec Reads added: 5 readQueue.size: 5
...
Processor proc_1 thread 139819272103680 done. Processed 0 reads. Skipped already processed: 0 reads
...
Processor proc_0 thread 139819263710976 done. Processed 5 reads. Skipped already processed: 0 reads
...
Processor proc_4 thread 139819297281792 done. Processed 0 reads. Skipped already processed: 0 reads
...
Processor proc_5 thread 139819305674496 done. Processed 0 reads. Skipped already processed: 0 reads
...
Processor proc_6 thread 139819314067200 done. Processed 0 reads. Skipped already processed: 0 reads
...
Processor proc_3 thread 139819288889088 done. Processed 0 reads. Skipped already processed: 0 reads
...
Processor proc_2 thread 139819280496384 done. Processed 0 reads. Skipped already processed: 0 reads
...
Processor proc_7 thread 139819322459904 done. Processed 0 reads. Skipped already processed: 0 reads
...
align:461 paralleltraversal: Done index 0 Part: 1 Time: 0.01 sec
...

postProcess:175 Log file generation starts
ThreadPool:36 initialized Pool with: [3] threads
....
postProcess:251 Done
...
generateReports:810 Report generation starts. Thread: 139819364538624
ThreadPool:36 initialized Pool with: [2] threads
generateReports:818 Restored Readstats from DB: 1
...
generateReports:871 Done Reports generation
...
</pre>

``` biocodz@ubuntu16-1:~$ ls -lrt ~/data/out ```
<pre>
-rw-rw-r-- 1 biocodz biocodz      2263 Oct 22 12:10 issue_137.sam
-rw-rw-r-- 1 biocodz biocodz       331 Oct 22 12:10 issue_137.log
-rw-rw-r-- 1 biocodz biocodz       879 Oct 22 12:10 issue_137.fasta
-rw-rw-r-- 1 biocodz biocodz       689 Oct 22 12:10 issue_137.blast
</pre>

``` less ~/data/out/issue_137.log ```
<pre>
 Results:
    Total reads = 5
    Total reads passing E-value threshold = 5 (100.00)
    Total reads failing E-value threshold = 0 (0.00)
    Minimum read length = 97
    Maximum read length = 101
    Mean read length    = 98
 By database:
    /home/biocodz/data/reads/scaffolds_issue_137.fasta          100.00

 Mon Oct 22 12:10:17 2018
</pre>

```less /data/out/issue_137.fasta ```
<pre>
>SRR606249.6025199.2 HWI-ST829:109:D073EACXX:2:1106:8626:110274 length=101
CACCTGCCCAGTGCTGGAAGGTTAAGGGGAGATGTGCAAGCGTTGAACCGAAGCCCCAGTAAACGGCGGCCGTAACTATAACGGTCCTAAGGTAGCGA
>SRR606249.24492705.1 HWI-ST829:109:D073EACXX:2:1306:9405:164392 length=101
GCCGCAGGTTCCCCTACGGCTACCTTGTTACGACTTCTCCCCCCTCGGGGGGAGCGACGGGCGGTGTGTGCAAGGAGCAGGGACGTGTTCACCGCGCGATG
>SRR606249.25652482.2 HWI-ST829:109:D073EACXX:2:1307:2506:138672 length=101
GACCTGTGTTTTTGGTAAACAGTCGCTTGGGCCTCTTCTCTGCGGCCTTTCGGCACTCCTTCTCCCGAAGTTACGGAGTCATTTTGCCGAGTTCCTT
>SRR606249.26931475.2 HWI-ST829:109:D073EACXX:2:1308:20741:118672 length=101
GACCTGTGTTTTTGGTAAACAGTCGCTTGGGCCTCTTCTCTGCGGCCTTTCGGCACTCCTTCTCCCGAAGTTACGGAGTCATTTTGCCGAGTTCCTT
>SRR606249.33106002.1 HWI-ST829:109:D073EACXX:2:2106:16757:57509 length=101
TGTTTTTGATAAACAGTCGCTTGGGCCTATTCACTGCGGCTGACCGAAGTCAGCACCCCTTCTCCCGAAGTTACGGGGTCATTTTGCCGAGTTCCTTAACG
</pre>

``` less /data/out/issue_137.blast ```
<pre>
SRR606249.6025199.2     159     83.3    91      6       11      1       91      43      144     1.45e-26        105
SRR606249.6025199.2     159     83.3    91      6       11      8       98      50      151     1.45e-26        105
SRR606249.24492705.1    161     93.2    59      4       0       6       64      1329    1387    5.55e-20        84
SRR606249.24492705.1    161     93.2    59      4       0       6       64      1329    1387    5.55e-20        84
SRR606249.24492705.1    161     95      40      2       0       49      88      1429    1468    6.84e-13        60
SRR606249.25652482.2    240     82.2    92      9       9       1       92      72      172     2.75e-24        98
SRR606249.25652482.2    240     82.2    92      9       9       1       92      72      172     2.75e-24        98
SRR606249.26931475.2    240     82.2    92      9       9       1       92      72      172     2.75e-24        98
SRR606249.26931475.2    240     82.2    92      9       9       1       92      72      172     2.75e-24        98
SRR606249.33106002.1    240     82.9    101     13      5       1       101     68      171     2.67e-25        101
SRR606249.33106002.1    240     82.9    101     13      5       1       101     68      171     2.67e-25        101
</pre>

``` less /data/out/issue_137.sam ```
<pre>
@HD     VN:1.0  SO:unsorted
@PG     ID:sortmerna    VN:1.0  CL:sortmerna --ref /home/biocodz/data/reads/scaffolds_issue_137.fasta,/home/biocodz/data/idx/scaffolds_issue_137 --reads /home/biocodz/data/reads/faulty_reads_issue_137.fasta --aligned /home/biocodz/data/out/issue_137 --fastx --sam --blast 1 --log --best 10 --min_lis 10 -e 1.00e-05 -v -d /home/biocodz/data/kvdb
SRR606249.6025199.2     0       159     43      255     35M4D1M7D55M7S  *       0       0       CACCTGCCCAGTGCTGGAAGGTTAAGGGGAGATGTGCAAGCGTTGAACCGAAGCCCCAGTAAACGGCGGCCGTAACTATAACGGTCCTAAGGTAGCGA      *       AS:i:124        NM:i:17
SRR606249.6025199.2     0       159     50      255     7S28M4D1M7D62M  *       0       0       CACCTGCCCAGTGCTGGAAGGTTAAGGGGAGATGTGCAAGCGTTGAACCGAAGCCCCAGTAAACGGCGGCCGTAACTATAACGGTCCTAAGGTAGCGA      *       AS:i:124        NM:i:17
SRR606249.24492705.1    16      161     1329    255     5S59M37S        *       0       0       CATCGCGCGGTGAACACGTCCCTGCTCCTTGCACACACCGCCCGTCGCTCCCCCCGAGGGGGGAGAAGTCGTAACAAGGTAGCCGTAGGGGAACCTGCGGC   *       AS:i:98 NM:i:4
SRR606249.24492705.1    16      161     1329    255     5S59M37S        *       0       0       CATCGCGCGGTGAACACGTCCCTGCTCCTTGCACACACCGCCCGTCGCTCCCCCCGAGGGGGGAGAAGTCGTAACAAGGTAGCCGTAGGGGAACCTGCGGC   *       AS:i:98 NM:i:4
SRR606249.24492705.1    16      161     1429    255     48S40M13S       *       0       0       CATCGCGCGGTGAACACGTCCCTGCTCCTTGCACACACCGCCCGTCGCTCCCCCCGAGGGGGGAGAAGTCGTAACAAGGTAGCCGTAGGGGAACCTGCGGC   *       AS:i:70 NM:i:2
SRR606249.25652482.2    16      240     72      255     46M6D4M3D42M5S  *       0       0       AAGGAACTCGGCAAAATGACTCCGTAACTTCGGGAGAAGGAGTGCCGAAAGGCCGCAGAGAAGAGGCCCAAGCGACTGTTTACCAAAAACACAGGTC       *       AS:i:115        NM:i:18
SRR606249.25652482.2    16      240     72      255     46M6D4M3D42M5S  *       0       0       AAGGAACTCGGCAAAATGACTCCGTAACTTCGGGAGAAGGAGTGCCGAAAGGCCGCAGAGAAGAGGCCCAAGCGACTGTTTACCAAAAACACAGGTC       *       AS:i:115        NM:i:18
SRR606249.26931475.2    16      240     72      255     46M6D4M3D42M5S  *       0       0       AAGGAACTCGGCAAAATGACTCCGTAACTTCGGGAGAAGGAGTGCCGAAAGGCCGCAGAGAAGAGGCCCAAGCGACTGTTTACCAAAAACACAGGTC       *       AS:i:115        NM:i:18
SRR606249.26931475.2    16      240     72      255     46M6D4M3D42M5S  *       0       0       AAGGAACTCGGCAAAATGACTCCGTAACTTCGGGAGAAGGAGTGCCGAAAGGCCGCAGAGAAGAGGCCCAAGCGACTGTTTACCAAAAACACAGGTC       *       AS:i:115        NM:i:18
SRR606249.33106002.1    16      240     68      255     48M4D10M1I42M   *       0       0       CGTTAAGGAACTCGGCAAAATGACCCCGTAACTTCGGGAGAAGGGGTGCTGACTTCGGTCAGCCGCAGTGAATAGGCCCAAGCGACTGTTTATCAAAAACA   *       AS:i:119        NM:i:18
SRR606249.33106002.1    16      240     68      255     48M4D10M1I42M   *       0       0       CGTTAAGGAACTCGGCAAAATGACCCCGTAACTTCGGGAGAAGGGGTGCTGACTTCGGTCAGCCGCAGTGAATAGGCCCAAGCGACTGTTTATCAAAAACA   *       AS:i:119        NM:i:18
</pre>

**Comment by biocodz** [comment]
Found and fixed a bug in alignment routine. The new release will be ready soon.

**Comment by biocodz** [comment]
Release (v3.0.2)[https://github.com/biocore/sortmerna/releases/tag/v3.0.2] fixes this.
Here are the results running on the provided data
```
biocodz@ubuntu16-1:~$ ls -lrt data/out/
-rw-rw-r-- 1 biocodz biocodz 1213 Nov 21 12:43 issue_137.sam
-rw-rw-r-- 1 biocodz biocodz  326 Nov 21 12:43 issue_137.log
-rw-rw-r-- 1 biocodz biocodz  879 Nov 21 12:43 issue_137.fasta
-rw-rw-r-- 1 biocodz biocodz 2592 Nov 21 12:43 issue_137.blast

cat data/out/issue_137.log
 Results:
    Total reads = 5
    Total reads passing E-value threshold = 5 (100.00)
    Total reads failing E-value threshold = 0 (0.00)
    Minimum read length = 97
    Maximum read length = 101
    Mean read length    = 98
 By database:
    /home/biocodz/data/reads/refs_issue_137.fasta               100.00

 Wed Nov 21 12:43:30 2018


cat data/out/issue_137.sam
@HD     VN:1.0  SO:unsorted
@PG     ID:sortmerna    VN:1.0  CL:sortmerna --ref /home/biocodz/data/reads/refs_issue_137.fasta,/home/biocodz/data/idx/refs_issue_137 --reads /home/biocodz/data/reads/reads_issue_137.fasta --aligned /home/biocodz/data/out/issue_137 --fastx --sam --blast 0 --log --best 10 --min_lis 10 -v -d /home/biocodz/data/kvdb --threads 1:1:2
SRR606249.6025199.2     0       159     43      255     35M4D1M7D55M7S  *       0       0       CACCTGCCCAGTGCTGGAAGGTTAAGGGGAGATGTGCAAGCGTTGAACCGAAGCCCCAGTAAACGGCGGCCGTAACTATAACGGTCCTAAGGTAGCGA     *       AS:i:124        NM:i:17
SRR606249.24492705.1    16      161     1329    255     5S59M37S        *       0       0       CATCGCGCGGTGAACACGTCCCTGCTCCTTGCACACACCGCCCGTCGCTCCCCCCGAGGGGGGAGAAGTCGTAACAAGGTAGCCGTAGGGGAACCTGCGGC  *       AS:i:98 NM:i:4
SRR606249.25652482.2    16      240     76      255     4S42M6D4M3D47M  *       0       0       AAGGAACTCGGCAAAATGACTCCGTAACTTCGGGAGAAGGAGTGCCGAAAGGCCGCAGAGAAGAGGCCCAAGCGACTGTTTACCAAAAACACAGGTC      *       AS:i:117        NM:i:18
SRR606249.26931475.2    16      240     76      255     4S42M6D4M3D47M  *       0       0       AAGGAACTCGGCAAAATGACTCCGTAACTTCGGGAGAAGGAGTGCCGAAAGGCCGCAGAGAAGAGGCCCAAGCGACTGTTTACCAAAAACACAGGTC      *       AS:i:117        NM:i:18
SRR606249.33106002.1    16      240     68      255     48M4D10M1I42M   *       0       0       CGTTAAGGAACTCGGCAAAATGACCCCGTAACTTCGGGAGAAGGGGTGCTGACTTCGGTCAGCCGCAGTGAATAGGCCCAAGCGACTGTTTATCAAAAACA  *       AS:i:119        NM:i:18

```
