### ISSUE TITLE
sortmerna segfaults when splitting data in multiple partial sections

### ISSUE THREAD

**Issue by stevendbrown** [biocore/sortmerna#161]
I'm using sortmerna to filter reads from a NovaSeq run, and some of the samples are somewhat large (~49GB FASTQ for one read of a pair). I've previously used fairly small memory sizes (`-m 2048`) which is how I noticed the problem. I can workaround by increasing the memory limit (`-m 65536`). I've only tested this on my workstation, which runs Ubuntu Linux.

I'm not familiar with using gdb to debug executables, so it'll probably take me a little while to get that sorted out, but the segfaults logs are available here (though I suspect these are useless without my particular binaries to check against?): https://gist.github.com/stevendbrown/68e20cb1d648368fb9a2cefd9f2969c0

I first tried updating to the current github version, but I was already up-to-date with `master`.  I'm using the provided silva-bac-16s and silva-bac-23s databases for filtering, and using options `-v --log --reads fn.fq --ref <refs> --fastx --aligned smr_aligned --other smr_unaligned -m <number> -a 32 --out_map`. The error occurs regardless of whether or not the input FASTQ file is gz-compressed.

If there's something in particular that would be helpful (e.g. attaching a debugger) please let me know and I'll work on getting that output. If I'm doing something dumb, please also let me know so I can stop doing it! :-)

**Comment by ekopylova** [comment]
Hello,

Thank you for reporting this. Indeed, we are familiar with the seg fault when loading reads using memory mapping. The error occurs when reading FASTQ reads that were split precisely between two memory blocks (e.g. 2048 in size). We have removed this option completely from the development version of SortMeRNA and it will not be in the next release. Thus, I would suggest to use "-m 65536" if you have the RAM or convert your reads to FASTA format first, then run with "-m 2048" or the default. We're fully involved in the release of the next version now, so please stay tuned for that.

Best,
Jenya

**Comment by biocodz** [comment]
Closing this issue. The new version of Sortmerna doesn't use memory mapping all together. The reads are consumed from the stream, processed immediately in multiple worker threads, and the alignment results are stored in the key-value database (RocksDB). This  reduces memory footprint and gets away with the complexities of the memory mapping.
