### ISSUE TITLE
Error compiling with GCC 8.2 under Ubuntu 18.04

### ISSUE THREAD

**Issue by ppericard** [biocore/sortmerna#165]
Hi,

I'm currently trying to compile the master version of SortMeRNA with GCC 8.2 under Ubuntu 18.04.
I installed the necessary dependencies through the OS package manager, and when compiling I end up with a critical error:

```
[ 93%] Building CXX object src/sortmerna/CMakeFiles/smr_objs.dir/writer.cpp.o
[ 93%] Built target smr_objs
Scanning dependencies of target sortmerna
[ 95%] Building CXX object src/sortmerna/CMakeFiles/sortmerna.dir/main.cpp.o
[ 96%] Linking CXX executable sortmerna
[ 96%] Built target sortmerna
Scanning dependencies of target test_kvdb
[ 98%] Building CXX object tests/sortmerna/CMakeFiles/test_kvdb.dir/kvdb.cpp.o
[100%] Linking CXX executable test_kvdb
/usr/bin/ld: ../../src/sortmerna/CMakeFiles/smr_objs.dir/output.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
tests/sortmerna/CMakeFiles/test_kvdb.dir/build.make:137: recipe for target 'tests/sortmerna/test_kvdb' failed
make[2]: *** [tests/sortmerna/test_kvdb] Error 1
CMakeFiles/Makefile2:347: recipe for target 'tests/sortmerna/CMakeFiles/test_kvdb.dir/all' failed
make[1]: *** [tests/sortmerna/CMakeFiles/test_kvdb.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

```

Can you help me understand what's happening and get it to work if possible ?

Thanks ^^

**Comment by ekopylova** [comment]
Hello @ppericard!

What exact command did you use to start the build? It appears you may have used ```WITH_TESTS``` option, though this is intended for development. Could you try instead:

```cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DWITH_TESTS=0 ../..```
```make```

Jenya

**Comment by biocodz** [comment]
From the log it seems that 'sortmerna' was built OK, just the 'tests' failed. The tests were added for development purposes and found to be not very useful. I modified the build to disable 'WITH_TESTS' by default. Either don't use 'WITH_TESTS' at all or set '-DWITH_TESTS=0' e.g.
-----------
cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DWITH_TESTS=0 ../..
-----------
Meanwhile I'll look into the problem. Probably simply using
-DEXTRA_CXX_FLAGS_RELEASE="-pthread"
might solve this.

**Comment by ppericard** [comment]
Hi @ekopylova,

I followed to the letter the README. So these commands:

```
git clone https://github.com/biocore/sortmerna.git

mkdir -p $SMR_HOME/build/Release
pushd $SMR_HOME/build/Release

cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ../..

make
```

I imagine that the tests were activated by default ^^

Thanks @biocodz for solving the pb !
