### ISSUE TITLE
Add minimal GCC version requirement

### ISSUE THREAD

**Issue by ppericard** [biocore/sortmerna#166]
Hi,

Would it be possible to add to the README the minimal GCC version required to compile SortMeRNA ?

Thanks ^^

**Comment by biocodz** [comment]
The very minimal was not tested, but GCC 5.4.0 (default on Ubuntu 16.04) was tested OK. Added this to the README under 'SortMeRNA Compilation'

**Comment by ppericard** [comment]
Thanks ^^
