### ISSUE TITLE
WARNING: At least one of the reads is shorter than 18 nucleotides, by default it will not be searched

### ISSUE THREAD

**Issue by flippy23** [biocore/sortmerna#169]
Hello,

I am getting this error thousands of times in my text file for the outuput, which is taking more than hours to run. I am having trouble understanding why this is, as i have followed all the steps. any help would be appreciated. I am working with human data. There is nothing wrong with my fq files, as they aligned to STAR and now i am deciding to go back to check on rRNA depletion. 

and this is my index to the rRNA: 
sortmernaREF=/path/sortmerna-2.1/rRNA_databases/silva-euk-18s-id95.fasta,/path/sortmerna-2.1/index/silva-euk-18s-id95:\
/path/rRNA_databases/silva-euk-28s-id98.fasta,/path/sortmerna-2.1/index/silva-euk-28s-id98
/path/sortmerna-2.1/indexdb_rna --ref $sortmernaREF

here is my code for merging and alignment: 

bash ./scripts/merge-paired-reads.sh /path/forward_paired.fq /path/reverse_paired.fq merged-reads14.fq
sortmernaREF=/path/sortmerna-2.1/rRNA_databases/silva-euk-18s-id95.fasta,/path/sortmerna-2.1/index/silva-euk-18s-id95:\
/path/sortmerna-2.1/rRNA_databases/silva-euk-28s-id98.fasta,/path/rnatest/sortmerna-2.1/index/silva-euk-28s-id98
./sortmerna --ref $sortmernaREF --reads ./merged-reads14.fq --aligned /path/sample_aligned --other /path/sample_filtered --paired_out --fastx --log -a 30

Thanks

**Comment by flippy23** [comment]
the input files are around 5GB

**Comment by biocodz** [comment]
@flippy23 
Could you also provide the starting trace (stdout) of the ```sortmerna``` execution, and what ```top``` shows with regards to processor load ? I wonder if multithreading is working. If only a single thread is running, it'll take ages to process.

**Comment by biocodz** [comment]
Closing this issue until further details are available.

**Comment by olferievm** [comment]
Dear Jenya,

I have the same warnings about short reads. My fastq files have been prefiltered with fastp and lack the reads shorter than 36nt.
Could the issue be related to the lack of  \1 and \2 at the end of the reads name?


```
@K00237:63:H2HTJBBXY:6:1116:22232:34354
00
GCAGCATCTTGGATGGACCAGGATCCAGTCTTTCTTTTCTTTTTTTTTTTTTAGGGGGGGGTTCGCCTTTTTTTCCCAGGCTGGGGGGGGATGGCGCCATC
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJJFJFJJFJJJJJJJJJJJJJJJJJ<--<77A<<-7F-----7A-7F-<FA-77---A7A-AF<7<FF--77F<-
@K00237:63:H2HTJBBXY:6:1116:22232:34354
00
CCCAACTACTAGGGAGGCTGAGGCAGGAGAATCACTTGAACGCGGGATGCAGAGGTTGCAGTGAGCCGAGATTGCGCCATTCCACTCCAGCCTGGGCAACA
+
AAAFFJJJFJJJJJFAFJJJJJJJJJJJJJJJJJJJFJJJFFAJJJFJJJFJFJJ-A<<AJ-FAJFAFJFJ<FJFJFJFF<FFJJJJJJJJJJFA-7FJAJ
@K00237:63:H2HTJBBXY:6:1116:25073:34354
00
GTCAAGTTGTTTCCATTAAAAAGTACTGATTTTAAAAACTAATAACTTAAAACTGCCACACGCAAAAAAGAAAACCAAAGTGGTCCACAAAACATTCTCCT
+
AAFFFJJJJJJFFJJJJJJJJJJFJJF<JJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJAJA<<AJJJJJJJJJJJJFJFJFJJJFJFFJJJFJJJJJJJ
@K00237:63:H2HTJBBXY:6:1116:25073:34354
00
```

Mikhail.

**Comment by ekopylova** [comment]
Hello @olferievm , what version of SMR are you using?

**Comment by olferievm** [comment]
Dear Jenya,

My version is 2.1. I used SortMeRNA to remove rRNA from unmapped reads after STAR alignment (Unmapped.out.mate1 and Unmapped.out.mate2) and got the same error. However, SortMeRNA works well when pair reads were labeled with /1 and /2 at the end before merging files. But I also removed short reads using fastp before merging. 

@K00237:63:H2HTJBBXY:6:1116:22232:34354/1
@K00237:63:H2HTJBBXY:6:1116:22232:34354/2
@K00237:63:H2HTJBBXY:6:1116:25073:34354/1
@K00237:63:H2HTJBBXY:6:1116:25073:34354/2

Thank you.

Mikhail.

**Comment by ekopylova** [comment]
Please try version [3.0.3](https://github.com/biocore/sortmerna/releases/tag/v3.0.3) as this error should not appear any longer. We're happy to assist you with installation if you run into issues.

Jenya

**Comment by olferievm** [comment]
Спасибо!

**Comment by biocodz** [comment]
@olferievm You can install v3 at any location (default is `$HOME/bin/`), and use it without touching the v2.1 (which is likely in `/usr/bin/` or `/usr/local/bin/`). To remove the v3, just delete the `$HOME/bin/sortmerna`, indexdb.
