### ISSUE TITLE
Dangerous behaviour of -d option !!!

### ISSUE THREAD

**Issue by ppericard** [biocore/sortmerna#171]
Ok, so this one is very important because I almost lost a ton of work first time using sortmerna 3.0.0 and I'm pretty sure a lot of users will do the same.

With the new release you added a new mandatory option: -d; key−value store location (folder path)
The first time I ran sortmerna, I just did `sortmerna -d .` , making thus the current working dir the location of the database. And what sortmerna did, without any warning, is "cleaning" this directory by deleting all files in it !!!

This cannot happen !!! You will have hordes of angry biologists wanting to kill you because all their precious data disappeared. I was just saved because as a careful bioinformatician I always use symbolic links to my data and therefore only lost the links.

In light of this, I have 2 comments:
1. Do not "clean" a directory if you are not sure all the files you are deleting where generated by your tool
2. Users really will not care about the location of temporary files used only internally by sortmerna. Therefore, this is a case where you can set a default value. You could use the /tmp dir, or if you think it will not be big enough you can create a new directory (with a unique name clearly designed for tmp data) inside the current working directory. You can always clean after the run by deleting this tmp directory.

Cheers ^^

**Comment by ppericard** [comment]
I will add that this is true in general for bioinformatic tools. Options should really be focused on results-oriented parameters. All technical/internal stuff should be dealt with without needing the user input.
I'm seeing the same tendency with the --threads options (I'll open another issue).

**Comment by biocodz** [comment]
Good catch. I definitely thought about the '-d' location as a temporary location for the processed data and nothing else. I'll try to fix this quickly.

**Comment by biocodz** [comment]
The new release [30.01](https://github.com/biocore/sortmerna/releases/tag/v3.0.1) makes the '-d' optional.
By default the Key-Value datastore will be created in the User Home `kvdb` directory e.g. `/home/biocodz/kvdb/`. If the directory already exists and is not empty, the user will be prompted to empty it, or to specify a different directory using `-d` option.
No matter what directory is used, it is always validated. If not empty, the program will ask to empty/use different directory, and exit

**Comment by biocodz** [comment]
Closing this as fixed
