### ISSUE TITLE
Simplifying multi-threading options

### ISSUE THREAD

**Issue by ppericard** [biocore/sortmerna#172]
Multi-threading options really need simplifying. Most bioinformatics users do not need, and do not want, to know exactly how their CPU are utilized by the different processes. Right now they could change up to 7 parameters in 3 different options (--thread, --thpp, --threp).

A way to simplify this could be to have a unique option (--threads, or --cpus) with only one number to input, which could be set by default to the number of available cores. The only important thing is that, whatever internal choices are made, the CPU usage of SortMe can never go above this set number.

**Comment by biocodz** [comment]
I agree. These options are intended for development. I think to remove them from the help completely and to document separately for developers.

**Comment by biocodz** [comment]
New release [3.0.1](https://github.com/biocore/sortmerna/releases/tag/v3.0.1) moves the multi-threaded options to the 'Developer options' category as follows:
<pre>
...
  [DEVELOPER OPTIONS]:
    --cmd             BOOL             launch an interactive session (command prompt)
    --task            INT              Processing Task
                                           0 - align Only perform alignment
                                           1 - post-processing (log writing)
                                           2 - generate reports
                                           3 - align and post?process
                                           4 - all (default)

    -d                STRING           key-value datastore FULL folder path                      USERDIR/kvdb
    -a                INT              number of threads to use                                  numCores
    --threads         INT:INT:INT      number of Read:Write:Process threads to use               1:1:numCores
    --thpp            INT:INT:INT      number of Post-Processing Read:Process threads to use     1:1
    --threp           INT:INT:INT      number of Report Read:Process threads to use              1:1
</pre>

**Comment by biocodz** [comment]
Closing this issue as fixed
