### ISSUE TITLE
librocksdb.so.4.1 error message

### ISSUE THREAD

**Issue by PavlinaG** [biocore/sortmerna#173]
Hi Jenya,

I am newbie and I downloaded the newest binaries of sortmerna-v3.0.1 and followed instructions for using binaries as they are described in sortmerna documentation here on GitHub. Once I tried to run sortmerna it gave me error:
"error while loading shared libraries: librocksdb.so.4.1: cannot open shared object file: No such file or directory"
I just renamed libstdc++.so.6 to librocksdb.so.4.1 and then it works. Is it okay just to rename the file or this will tamper the functionality of sortmerna?
Thanks in advance for help!
Cheers,
Pavlina

**Comment by biocodz** [comment]
Renaming libstdc++.so.6 to librocksdb.so.4.1 is a wrong thing to do. 
What Linux version you are using?

**Comment by PavlinaG** [comment]
Hi, 
I am using Ubuntu 18.04. Thanks for helping to sort this out.

**Comment by biocodz** [comment]
We didn't test on 18.04 yet, but the distribution still might work.
Could you, please, run the following command:
`apt-cache policy librocksdb-dev` and publish the result.
Something like
```
biocodz@ubuntu16-1:~$ apt-cache policy librocksdb-dev
librocksdb-dev:
  Installed: 4.1-1
  Candidate: 4.1-1
  Version table:
 *** 4.1-1 500
        500 http://ca.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by PavlinaG** [comment]
Hi, 
I got:

```
librocksdb-dev:
  Installed: 5.8.8-1
  Candidate: 5.8.8-1
  Version table:
 *** 5.8.8-1 500
        500 http://cubbli.cs.helsinki.fi/mirror/ubuntu-bionic bionic/universe amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by biocodz** [comment]
Build on Ubuntu 18 worked OK:
```
 ldd sortmerna
        linux-vdso.so.1 (0x00007ffeb4dde000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f903b334000)
        librocksdb.so.5.8 => /usr/lib/librocksdb.so.5.8 (0x00007f903abac000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f903a98d000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f903a604000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f903a266000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f903a04e000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9039c5d000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f9039a55000)
        libsnappy.so.1 => /usr/lib/x86_64-linux-gnu/libsnappy.so.1 (0x00007f903984d000)
        libgflags.so.2.2 => /usr/lib/x86_64-linux-gnu/libgflags.so.2.2 (0x00007f9039628000)
        libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007f9039418000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f903b825000)
```
I added the binaries to the Release [sortmerna-3.0.2-ubuntu18-beta.tar.gz](https://github.com/biocore/sortmerna/releases/tag/v3.0.2)
The tar only contains `sortmerna` and `indexdb` assuming all the dependencies are present on the system (see `ldd` output above).
Please, let me know how it works for you.
Thank you

**Comment by biocodz** [comment]
There is a problem running on Ubuntu 18, see [issue 174](https://github.com/biocore/sortmerna/issues/174)
This suspends the usage on U18 until fixed

**Comment by biocodz** [comment]
I updated the release [v3.0.2](https://github.com/biocore/sortmerna/releases/tag/v3.0.2) with the required dependencies. Please, see the release notes.
