### ISSUE TITLE
Issue on kvdb in Ubuntu 18.04

### ISSUE THREAD

**Issue by OPSmolander** [biocore/sortmerna#174]
I was able to build sortmerna under Ubuntu 18.04 using the instructions available and also using parameters provided in #165 

However, when I run without parameter -d I am not able to run it repeatedly on several files because I get errors that the kvdb directory is not empty. If I specify the directory I get segmentation fault. 
ldd gives me this:

ldd /home/opsmolan/sortmerna/build/Release/src/sortmerna/sortmerna
        linux-vdso.so.1 (0x00007ffd96de3000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f17c6ed8000)
        librocksdb.so.5.8 => /usr/lib/librocksdb.so.5.8 (0x00007f17c6750000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f17c6530000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f17c61a0000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f17c5e00000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f17c5be8000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f17c57f0000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f17c55e8000)
        libsnappy.so.1 => /usr/lib/x86_64-linux-gnu/libsnappy.so.1 (0x00007f17c53e0000)
        libgflags.so.2.2 => /usr/lib/x86_64-linux-gnu/libgflags.so.2.2 (0x00007f17c51b8000)
        libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007f17c4fa8000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f17c73c8000)

**Comment by biocodz** [comment]
Could you, please, publish the command and the output (that gives the segfault)

**Comment by OPSmolander** [comment]
I will post the command as soon as I am able to re-run it. 

Currently I am running the version 2.1, which works fine, to get my data to downstream. My main motivation was to use version 3 to be able to run it on gz-files but of course it would be nice to be able to use the most up-to-date version anyways.

**Comment by biocodz** [comment]
I reproduced the error:
```
[Running on]
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
...
sortmerna --ref /home/biocodz/sortmerna/tests/t14_iss137_78/refs/refs_issue_137.fasta,/home/biocodz/sortmerna/tests/t14_iss137_78/idx/refs_issue_137 --reads /home/biocodz/sortmerna/tests/t14_iss137_78/reads/reads_issue_137.fasta --aligned /home/biocodz/sortmerna/tests/t14_iss137_78/out/aligned --sam --blast "1 qstrand cigar" -v --log -d /home/biocodz/sortmerna/tests/t14_iss137_78/kvdb --threads 1:1:2
test_kvdb_path: Using Key-value DB location: /home/biocodz/sortmerna/tests/t14_iss137_78/kvdb
...
list_dir:56 Directory /home/biocodz/sortmerna/tests/t14_iss137_78/kvdb has 0 files

  Program:      SortMeRNA version 3.0.2
...

main:55 Running task ALIGN_REPORT: 4
Readstats::calculate starting ...   Readstats::calculate done. Elapsed time: 0.00 sec. Reads processed: 5
align:380 Using number of Processor threads set in run options: 2
Number of cores: 1 Read threads:  1 Write threads: 1 Processor threads: 2
ThreadPool:36 initialized Pool with: [4] threads
read_queue created
write_queue created
Refstats:31 Index Statistics calculation Start ... Done. Time elapsed: 1.58 sec
align:413 Loading index 0 part 1/1 ... done [0.06] sec
align:424 Loading references  ... done [0.00] sec
reader_0 thread: 140484784887552 started
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
tests/run.sh: line 44: 15840 Aborted                 (core dumped) sortmerna --ref $REF --reads $TOP/reads/reads_issue_137.fasta --aligned $TOP/out/aligned --sam --blast "1 qstrand cigar" -v --log -d $TOP/kvdb --threads 1:1:2
```
Hmm. That's a new one. 
On it...

**Comment by biocodz** [comment]
The cause of this issue is the incompatibility between Sortmerna 3.0.2 and RocksDB 5.8.
v3.0.2 was built and tested OK with RocksDB 4.1 (5.8 is incompatible with 4.1 by definition according to semantic versioning).
The cure for this is creating proper distribution packages. Working on ...

**Comment by biocodz** [comment]
I updated the release [v3.0.2](https://github.com/biocore/sortmerna/releases/tag/v3.0.2). RocksDB 4.1 shared library and dependencies are added to the distro. Please, see the release notes.
Meanwhile I'm going to create the standard Debian and RPM packages, so as to prevent the dependency hell.

**Comment by deearahman** [comment]
Thank you. The former command works!
