### ISSUE TITLE
'P' is not one of the options

### ISSUE THREAD

**Issue by deearahman** [biocore/sortmerna#176]
I ran this command on version 3.0.2 

sortmerna --ref ./rRNA_databases/silva-bac-16s-id90.fasta,./index/silva-bac-16s-db:\./rRNA_databases/silva-bac-23s-id98.fasta,./index/silva-bac-23s-db:\./rRNA_databases/silva-arc-16s-id95.fasta,./index/silva-arc-16s-db:\./rRNA_databases/silva-arc-23s-id98.fasta,./index/silva-arc-23s-db:\./rRNA_databases/silva-euk-18s-id95.fasta,./index/silva-euk-18s-db:\./rRNA_databases/silva-euk-28s-id98.fasta,./index/silva-euk-28s:\./rRNA_databases/rfam-5s-database-id98.fasta,./index/rfam-5s-db:\./rRNA_databases/rfam-5.8s-database-id98.fasta,./index/rfam-5.8s-db\ --reads MPS139_contigs.fasta --sam --num_alignments 1 --fastx --aligned MPS139_rRNA\ --other MPS139_non_rRNA --log 

and got an error message as below.

ERROR: [Line 1174: ~/sortmerna/src/sortmerna/options.cpp] 'P' is not one of the options.

Any suggestion?

**Comment by ekopylova** [comment]
Could you try running the following command:

```bash
sortmerna --ref ./rRNA_databases/silva-bac-16s-id90.fasta,./index/silva-bac-16s-db --reads MPS139_contigs.fasta --sam --num_alignments 1 --fastx --aligned MPS139_rRNA --other MPS139_non_rRNA --log
```

Also try the command providing full paths to the rRNA databases, e.g.

```bash
sortmerna --ref /full/path/to/rRNA_databases/silva-bac-16s-id90.fasta,/full/path/to/index/silva-bac-16s-db ..
```

Do you obtain the same error?

**Comment by biocodz** [comment]
Full paths have to be provided. We'll add the paths validation in the coming releases.

**Comment by deearahman** [comment]
> Could you try running the following command:
> 
> ```shell
> sortmerna --ref ./rRNA_databases/silva-bac-16s-id90.fasta,./index/silva-bac-16s-db --reads MPS139_contigs.fasta --sam --num_alignments 1 --fastx --aligned MPS139_rRNA --other MPS139_non_rRNA --log
> ```
> 
> Also try the command providing full paths to the rRNA databases, e.g.
> 
> ```shell
> sortmerna --ref /full/path/to/rRNA_databases/silva-bac-16s-id90.fasta,/full/path/to/index/silva-bac-16s-db ..
> ```
> 
> Do you obtain the same error?

I did the former and it worked. Thanks!

**Comment by biocodz** [comment]
`4.x` versions allow using relative paths
