### ISSUE TITLE
Update conda recipe

### ISSUE THREAD

**Issue by adityabandla** [biocore/sortmerna#181]
Would be great if you can update the conda recipe for the latest release

**Comment by biocodz** [comment]
working on this now for [release 4](https://github.com/biocore/sortmerna/releases/tag/v4.0.0)
Note: duplicates the [issue 186](https://github.com/biocore/sortmerna/issues/186)

**Comment by biocodz** [comment]
Done. Ref: [Bioconda pull request 20877](https://github.com/bioconda/bioconda-recipes/pull/20877)
