### ISSUE TITLE
Update rocksdb source installation steps for Linux OS

### ISSUE THREAD

**Issue by adityabandla** [biocore/sortmerna#182]
Using the current instructions, rocksdb seems to pick up only the default zlib (/usr/local/lib64/libz.a) installation in the system and throws an error that zlib.h is not found

Altering the thirparty.inc file seems to have absolutely no effect

The workaround is to supply these flags during the CMAKE step 
`-DZLIB_INCLUDE_DIR=$HOME/zlib/dist/include  -DZLIB_LIBRARIES=$HOME/zlib/dist/lib/libz.so`

**Comment by biocodz** [comment]
Closing this as the fixes were applied and the readme updated
