### ISSUE TITLE
3.0.3 release fails with missing libraries on CentOS 6.6

### ISSUE THREAD

**Issue by unode** [biocore/sortmerna#184]
```
% cat /etc/centos-release 
CentOS release 6.6 (Final)

% wget https://github.com/biocore/sortmerna/releases/download/v3.0.3/sortmerna-3.0.3-Linux_C6.tar.gz -O - | tar xzf -

% ./sortmerna-3.0.3-Linux/bin/indexdb 
./indexdb: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./indexdb)
./indexdb: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./indexdb)

% ./sortmerna-3.0.3-Linux/bin/sortmerna 
./sortmerna: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./sortmerna)
./sortmerna: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./sortmerna)
./sortmerna: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.17' not found (required by ./sortmerna)
./sortmerna: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./sortmerna)
./sortmerna: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by ./sortmerna)
./sortmerna: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by ./sortmerna)
./sortmerna: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by ./sortmerna)
./sortmerna: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./sortmerna)
./sortmerna: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ./sortmerna)
./sortmerna: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.19' not found (required by ./sortmerna)
./sortmerna: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./sortmerna)

% ldd sortmerna-3.0.3-Linux/bin/indexdb
sortmerna-3.0.3-Linux/bin/indexdb: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by sortmerna-3.0.3-Linux/bin/indexdb)
sortmerna-3.0.3-Linux/bin/indexdb: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by sortmerna-3.0.3-Linux/bin/indexdb)
        linux-vdso.so.1 =>  (0x00007fff121ff000)
        librt.so.1 => /lib64/librt.so.1 (0x0000003338400000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x0000003341000000)
        libm.so.6 => /lib64/libm.so.6 (0x0000003337800000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x000000333b400000)
        libc.so.6 => /lib64/libc.so.6 (0x0000003337400000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x0000003338000000)
        /lib64/ld-linux-x86-64.so.2 (0x0000003337000000)
```

The release notes mention the binary as 'static' but it isn't.
Can you produce (and release) a [static binary (with cmake)](https://stackoverflow.com/a/24671474)?

**Comment by unode** [comment]
Attached a static version of 3.0.3: [sortmerna-3.0.3.zip](https://github.com/biocore/sortmerna/files/2856437/sortmerna-3.0.3.zip)
(github doesn't allow attaching a tar file so adding a zip instead).

Had to do some manual tinkering with cmake files to get it to link `zlib.a` instead of `zlib.so`.
Compiled on Ubuntu 16.04.

**Comment by biocodz** [comment]
The releases statically bundle only RocksDB and ZLib. They don't include the system libraries. Installing GCC would have taken care of the system dependencies.  I'll modify the descriptions to reflect this.
Appreciate your input and the effort on building. I'll check the binaries and add them to the release.

**Comment by unode** [comment]
I tried several gcc versions but either didn't get the right one or I kept getting errors due to missing symbols. Going for the source was the only solution in the end.

**Comment by biocodz** [comment]
Once again thanks for your effort to go through all the troubles. It's hard to provide binaries that satisfy all the needs.
I added the zip to the release together with the notes.
BTW, if you provide the modifications made on the Cmake files, I'll check how to incorporate them into the next release.

**Comment by unode** [comment]
The first step was to add:
```
target_link_libraries(indexdb -static)
```
and
```
target_link_libraries(sortmerna -static)
```
to the end of the cmakelists of each `src/` folder.

However as mentioned when building sortmerna cmake adds `zlib.so` in addition to `zlib.a` in the last linking step.

I'm not familiar enough with cmake to know how to change/correct this in a more future proof way. As this was the last step I simply ran the build in verbose mode and repeated the last step manually by copying the printed command and removing the `zlib.so` reference. `zlib.a` was already included in same command so everything else worked.

**Comment by biocodz** [comment]
That's good enough for me:-) Thanks.

**Comment by biocodz** [comment]
Full static linkage was added as the default. See release [3.0.4](https://github.com/biocore/sortmerna/releases/tag/v3.0.4)

**Comment by unode** [comment]
Thanks!
