### ISSUE TITLE
Update SortMeRNA bioconda package

### ISSUE THREAD

**Issue by bgruening** [biocore/sortmerna#186]
I would be great if we could get a new bioconda version of sortmerna. The new compilers are already in place.

https://bioconda.github.io/recipes/sortmerna/README.html?highlight=sortmerna

Thanks!

**Comment by biocodz** [comment]
Yep. This is in the workings ...

**Comment by biocodz** [comment]
Not that [release 4.0](https://github.com/biocore/sortmerna/releases/tag/v4.0.0) is out, we got ours hands on this. Hang on...

**Comment by biocodz** [comment]
Sortmerna 4.2.0 is available as Conda package.
Ref: [ BIoconda pull request 20877](https://github.com/bioconda/bioconda-recipes/pull/20877)
