### ISSUE TITLE
cannot customize install location

### ISSUE THREAD

**Issue by dynamo07** [biocore/sortmerna#188]
When I built sortmerna from source on RHEL7, I cannot specify -DCMAKE_INSTALL_PREFIX=customized/path when using cmake. In CMakeLists.txt, the customized install location seems replaced. I commented it and everything went well. But I don't know how it will affect others.
```
# Installation and packaging
set(CMAKE_INSTALL_PREFIX ${CMAKE_CURRENT_SOURCE_DIR}/dist CACHE PATH "Install path prefix, prepended onto install directories." FORCE)
```

**Comment by biocodz** [comment]
Could you, please, specify how the customised location is replaced? Is it replaced with something like '/usr/bin/'?
CMAKE_INSTALL_PREFIX is a built-in Cmake facility, not something provided by the SMR code, so this problem looks odd.

**Comment by dynamo07** [comment]
Hi, I worked with a server using RHEL7 and cmake 3.14.5. I git cloned SMR as "/XX/projects/myID/sortmerna" and intended to install SMR in "/XX/projects/myID/SMR". So I used codes:
```
mkdir -p sortmerna/build/Release
pushd sortmerna/build/Release
cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/XX/projects/myID/SMR -DCPACK_BINARY_TGZ=ON -DROCKSDB_HOME=/XX/projects/myID/rocksdb_install_here -DROCKSDB_SRC=/XX/projects/myID/rocksdb -DRAPIDJSON_HOME=/XX/projects/myID/rapidjson_install_here -DEXTRA_CXX_FLAGS_RELEASE="-lrt" ../..
cmake --build .
cmake --build . --target install
cmake --build . --target package
popd
```
It ignored the location specified by DCMAKE_INSTALL_PREFIX and instead installed in "/XX/projects/myID/sortmerna/dist". When I comment the line "set...."
```
# Installation and packaging
set(CMAKE_INSTALL_PREFIX ${CMAKE_CURRENT_SOURCE_DIR}/dist CACHE PATH "Install path prefix, prepended onto install directories." FORCE)
```
in the file "/XX/projects/myID/sortmerna/CMakeLists.txt", it successfully installed where I specified. But I have no idea the risk of commenting this line.

**Comment by biocodz** [comment]
Thanks for the detailed input.
I'm looking into it

**Comment by biocodz** [comment]
pushed the fix to master

**Comment by dynamo07** [comment]
Thanks for the fix.

**Comment by biocodz** [comment]
Closing this.
