### ISSUE TITLE
The input reads file or reference file is empty, or the reads file is not in FASTA or FASTQ format, no analysis could be made.

### ISSUE THREAD

**Issue by Riverhuang42** [biocore/sortmerna#189]
sortmerna --ref silva-euk-18s-id95.fasta,./index/silva-euk-18s-db:silva-euk-28s-id98.fasta,./index/silva-euk-28s-db --reads Untreated_merge.fastq --num_alignments 1 --fastx --aligned reads_rRNA_Untreated --other reads_non_rRNA_Untreated --log -a 16 -m 6400 --paired_in -v

I checked  index, reference, and my fastq file, they all in the same folder with the right format, but it still cannot run properly

error: The input reads file or reference file is empty, or the reads file is not in FASTA or FASTQ format, no analysis could be made.

anyone can give some suggestions?

**Comment by ekopylova** [comment]
Hello,

What version of SortMeRNA are you using?

⁣Jenya

**Comment by biocodz** [comment]
Please, use Full paths when specifying the references and the reads.

**Comment by Riverhuang42** [comment]
> Hello, What version of SortMeRNA are you using? ⁣Jenya
> […](#)
> On Jul 11, 2019, 09:04, at 09:04, Riverhuang42 ***@***.***> wrote: sortmerna --ref silva-euk-18s-id95.fasta,./index/silva-euk-18s-db:silva-euk-28s-id98.fasta,./index/silva-euk-28s-db --reads Untreated_merge.fastq --num_alignments 1 --fastx --aligned reads_rRNA_Untreated --other reads_non_rRNA_Untreated --log -a 16 -m 6400 --paired_in -v I checked index, reference, and my fastq file, they all in the same folder but it still cannot run properly error: The input reads file or reference file is empty, or the reads file is not in FASTA or FASTQ format, no analysis could be made. anyone can give some suggestions? -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #189

sortmerna-2.1

**Comment by Riverhuang42** [comment]
> Please, use Full paths when specifying the references and the reads.

I tried, it has the same issue

**Comment by ekopylova** [comment]
Hello,

This version is not being supported any longer. Please try the latest available release (v3.0.3).
