### ISSUE TITLE
reads can not fastqc after sortmerna

### ISSUE THREAD

**Issue by Riverhuang42** [biocore/sortmerna#191]
Before sortmerna, the reads are validated and passed fastqc. After I removed rRNA with sortmerna (v3.0.3) and did unmerge, one of the reads failed fastqc. with error
uk.ac.babraham.FastQC.Sequence.SequenceFormatException: ID line didn't start with '@'
    at uk.ac.babraham.FastQC.Sequence.FastQFile.readNext(FastQFile.java:158)
    at uk.ac.babraham.FastQC.Sequence.FastQFile.next(FastQFile.java:125)
    at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:76)
    at java.lang.Thread.run(Thread.java:748)

How should I fix this

**Comment by biocodz** [comment]
@Riverhuang42 May I ask the detailed steps you performed, like
Input file: `xxx.fastq` (file size?)
Validate: `fastqc xxx.fastq`
Align: `sortmerna --reads xxx.fastq` (the whole command with all the flags, please)
Filter rRNA: `the whole command` -> xxx_out.fastq
Validate: `fastqc xxx_out.fastq`
Thank you

**Comment by Riverhuang42** [comment]
Input: merge.fastq  33,405,484 kb
Validate: fastqc merge.fastq
Align: sortmerna --ref silva-euk-18s-id95.fasta,./index/silva-euk-18s-db:silva-euk-28s-id98.fasta,./index/silva-euk-28s-db --reads merge.fastq --num_alignments 1 --fastx --aligned reads_rRNA --other reads_non_rRNA --log -a 16 -m 6400 --paired_in -v
Output: reads_non_rRNA.fastq  33,121,316KB (which I found blank lines in it, and  causing the problem)

do you have any idea why it generates blank lines?

**Comment by TianyiChang** [comment]
Hi, I am facing the same issue. Have you found out how to solve it?

**Comment by biocodz** [comment]
@TianyiChang 
Hi,
did you try the latest release [4.2.0](https://github.com/biocore/sortmerna/releases/tag/v4.2.0)?
No need to use merging/unmerging scripts anymore
biocodz.

**Comment by TianyiChang** [comment]
Hi, 

It seems that it only generate one other.fa file for non-rRNA in the 4.2 version so if I still need to unmerge it to get my forward and reverse reads?

Best,

**Comment by biocodz** [comment]
Creating separate output files is a feature of >4.1.x. If it only generates a single file then the reason is either a bug or an incorrect use.
You can re-open this issue and describe the steps taken including the execution trace like the one [here](https://github.com/biocore/sortmerna/wiki/Sample-execution-trace)

**Comment by TianyiChang** [comment]
Hi Biocore

The v4.2 version has solved this problem, thank you so much for your contribution to the software! 

There is only one thing I am a bit confused about: does the suffix  “ _rev" and “_fwd”  of the outputs means anything? For instance, the “aligned_fwd" means the reads mapped to the sense strands of rRNA sequences, but what about the “other_fwd" if they did not hit to anything in the rRNA databases? Or if the “_fwd” and “_rev” just correspond to the input files read1 and read2? 

Many thanks,
Tianyi

**Comment by biocodz** [comment]
Good to hear you have found the solution!
`_fwd` and `_rev` suffixes are used when paired reads are processed with the `-out2` option. Aligned reads from the first reads file (FWD) are put into `aligned_fwd`, and the aligned reads from the second (REV) reads file are put into the `aligned_rev`. The same for the non-aligned (other) reads. See [issue 202](https://github.com/biocore/sortmerna/issues/202).

**Comment by TianyiChang** [comment]
Super! Thanks a lot for your explanation.

Best,
Tianyi
