### ISSUE TITLE
-memory flag 

### ISSUE THREAD

**Issue by Katharina01** [biocore/sortmerna#193]
using sortmerna with the -m flag 
sortmerna [...] -m 4096 [...] givens the following output: 
  ERROR: [Line 1184: /root/sortmerna-3.0.3/src/sortmerna/options.cpp] 'm' is not one of the options.
sortmerna version: 3.0.3.

Any feedback would be greatly appreciated as runs with default settings take VERY long on RNAseq data.

**Comment by ekopylova** [comment]
Hello,

This option has been removed a while back, can you please use the latest version and let me know how it goes? Happy to help with installation,

Jenya

**Comment by ekopylova** [comment]
I see now you are using version 3.0.3, indeed this is one of the latest and the -m option doesn't exist anymore.

What is the size of your input files? Do you expect a lot of rRNA (e.g. was there  rRNA depletion done?)? Can you specify the exact command you are using? Thanks,

⁣

**Comment by Katharina01** [comment]
Ah, this makes sense. I used -m in a previous version successfully and was hoping to do so in the current version as the manual for version 3.0.3 on github explicitly states " The user can adjust the amount of memory allocated for loading the reads through the command option -m. [...]" 

command: 
sortmerna --ref $WORK/rRNA_databases/silva-bac-16s-id90.fasta,$WORK/index/silva-bac-16s-db:\
$WORK/rRNA_databases/silva-bac-23s-id98.fasta,$WORK/index/silva-bac-23s-db:\
$WORK/rRNA_databases/silva-euk-18s-id95.fasta,$WORK/index/silva-euk-18s-db:\
$WORK/rRNA_databases/silva-euk-28s-id98.fasta,$WORK/index/silva-euk-28s-db \
--reads $WORK/$COMBI \
--aligned $WORK/$ALIGNED \
--other $WORK/$REJECTS \
--paired_in --fastx --sam -d $WORK/$KEYVALUE -a 18 --log -v
file size range: 20-40GB

**Comment by biocodz** [comment]
Reference to `m` flag  was left in the manual by mistake (overlooked). Removed now. It will appear in the release 3.0.4 coming in couple days

**Comment by Katharina01** [comment]
coming back to the original issue experienced- the very long run times:
In the absence of the -m flag (or functional equivalent), is there a way to adjust settings such as to shorten run times?

**Comment by ekopylova** [comment]
Hello,

Do you need SAM alignments or is it OK to simply filter rRNA vs non-rRNA? With the SAM option, the program tries to find better alignments per read, even if the read has already been classified as rRNA. If you remove that option (--sam), it should run faster.

Also, do you expect a lot of rRNA In your sample?

If you are able to share your data, we can run it on the cloud and see what else can be done to improve the runtime. Let me know and I’ll create a project where you can upload the data, it will be secure and you will have access to seeing all the analysis. Please contact me via e-mail for this (jenya[dot]kopylov[at]gmail[dot]com).

Thanks,
Jenya

**Comment by biocodz** [comment]
@Katharina01 Could you also share the program execution trace i.e. whatever it writes on the screen?

**Comment by biocodz** [comment]
Closing for the lack of activity. The original issue (`-m` option) was resolved.
