### ISSUE TITLE
stuck processes after running the "merge script"

### ISSUE THREAD

**Issue by jc-lang** [biocore/sortmerna#196]
Hi guys, 

I'm a baby on the bioinformatics field but maybe some of you can help me...
So the problem is that after decompressing my fastq files and running the "merge" script, the system load average stays quite high without any running processes. I found out that there are processes that "stuck" (also `htop`) but I cannot kill them. So what I did before is reboot the server and everything is fine again. But this is not a good way I think so maybe you have a clue why this always happens? 

This is the command I ran for the merging:
`home/julia/sortmerna/scripts/merge-paired-reads.sh /home/julia/projects/phd/2_CTR_R1.fastq /home/julia/projects/phd/2_CTR_R2.fastq /home/julia/projects/phd/sortmerna/2_CTR_interleaved.fq
   Processing /home/julia/projects/phd/2_CTR_R1.fastq ..
   Processing /home/julia/projects/phd/2_CTR_R2.fastq ..
   Interleaving /home/julia/projects/phd/2_CTR_R1.fastq and /home/julia/projects/phd/2_CTR_R2.fastq ..
   Done.
`

and these are the processes that seem to stuck now:
`top - 09:23:31 up 15 days, 11 min,  3 users,  load average: 47.00, 46.99, 46.85
Threads: 983 total,   1 running, 982 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 26413494+total, 25416308 free, 52143644 used, 18657499+buff/cache
KiB Swap: 38501372 total, 38456428 free,    44944 used. 21098585+avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                                                                              
  494 root      39  19       0      0      0 D  0.0  0.0   0:22.28 khugepaged                                                                                                                                           
56420 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   0:00.00 java                                                                                                                                                 
56422 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:35.85 java                                                                                                                                                 
56423 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:33.89 java                                                                                                                                                 
56424 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:30.61 java                                                                                                                                                 
56425 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:38.21 java                                                                                                                                                 
56426 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:34.01 java                                                                                                                                                 
56427 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:34.17 java                                                                                                                                                 
56428 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:30.09 java                                                                                                                                                 
56429 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:31.64 java                                                                                                                                                 
56430 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:33.27 java                                                                                                                                                 
56431 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:33.87 java                                                                                                                                                 
56432 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:22.32 java                                                                                                                                                 
56433 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:27.83 java                                                                                                                                                 
56434 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:32.27 java                                                                                                                                                 
56435 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:25.13 java                                                                                                                                                 
56436 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:26.15 java                                                                                                                                                 
56437 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:24.62 java                                                                                                                                                 
56438 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:27.96 java                                                                                                                                                 
56439 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:23.77 java                                                                                                                                                 
56440 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:34.98 java                                                                                                                                                 
56441 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:26.49 java                                                                                                                                                 
56442 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:30.79 java                                                                                                                                                 
56443 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:26.16 java                                                                                                                                                 
56444 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:29.75 java                                                                                                                                                 
56445 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:25.03 java                                                                                                                                                 
56446 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:24.49 java                                                                                                                                                 
56447 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:33.82 java                                                                                                                                                 
56448 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:27.16 java                                                                                                                                                 
56449 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:30.00 java                                                                                                                                                 
56450 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:22.94 java                                                                                                                                                 
56451 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:27.76 java                                                                                                                                                 
56452 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:26.54 java                                                                                                                                                 
56453 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:29.79 java                                                                                                                                                 
56454 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:32.62 java                                                                                                                                                 
56455 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:24.84 java                                                                                                                                                 
56456 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:25.46 java                                                                                                                                                 
56457 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:24.45 java                                                                                                                                                 
56458 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:32.50 java                                                                                                                                                 
56459 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:26.48 java                                                                                                                                                 
56460 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:35.04 java                                                                                                                                                 
56461 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:24.67 java                                                                                                                                                 
56462 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:24.15 java                                                                                                                                                 
56463 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   2:34.20 java                                                                                                                                                 
56488 root      20   0  0.142t 0.047t  12696 D  0.0 19.1   0:00.92 java                                                                                                                                                 
57467 julia     20   0   27776   3500   1380 D  0.0  0.0   0:00.03 htop                                                                                                                                                 
`

**Comment by biocodz** [comment]
It looks like there are multiple memory hungry processes are running on your system. Java's hunger for memory is well-known. It's possible for the system to stuck in memory swaps. 
What are the sizes of your inflated reads files i.e.
```
ls -l /home/julia/projects/phd/2_CTR_R1.fastq 
ls -l /home/julia/projects/phd/2_CTR_R2.fastq
```

**Comment by jc-lang** [comment]
The decompressed files are around 40 GB. What can I do to prevent the java-hunger?

**Comment by biocodz** [comment]
@jc-lang  Just to be clear, Sortmerna and the shell scripts it provides have nothing to do with Java. They just add load to your machine, which already seems to be well loaded. I have no idea what those java processes are. Without the access to your machine it's hard to tell what's going on there. Your sysadmin should be able to answer this question better.
I would stop Java while running sortmerna and the merge/unmerge scripts. Sortmerna uses a lot of memory to store its indices. And, of course, the larger the files, the more memory it needs. You can tell Sortmerna to use less memory by splitting indices, but then the whole process will take longer to run.

**Comment by jc-lang** [comment]
Ok thanks! I just talked to the other server user and everybody agreed on not running java while sortmerna things are running. Till now that worked fine!
