### ISSUE TITLE
Raise "Index Statistics calculation Start ...Aborted (core dumped)" problem!

### ISSUE THREAD

**Issue by battlerb** [biocore/sortmerna#201]
Hi there,

I'm glad to see you update sortmerna to version 4.0.0. But I got a issue when I tried to run it on my PC (Ubuntu 18.04.3, 8 Core, 16 Thread, 32G Memory). After indexing those database fasta files, then the error "Index Statistics calculation Start ...Aborted (core dumped)" raised.

![Screenshot from 2019-12-05 21-46-20](https://user-images.githubusercontent.com/50813246/70241800-9d59ab00-17aa-11ea-8c7b-952117ab90a9.png)

**Comment by biocodz** [comment]
Thanks for reporting this.
Please, remove the `/home/tianyu/sortmerna/run/kvdb/` on each new run i.e.
```
rm -rf /home/tianyu/sortmerna/run/kvdb/
```
`kvdb` is not reusable (yet), unlike the 'idx'
Meanwhile, I'll look how to handle the ugly 'segfault':-) Probably, just prompt the user to purge the `kvdb`

**Comment by battlerb** [comment]
Thanks for your really fast reply. 

I see, thanks for your help. By the way, do I have any solution to build a permanently index instead of indexing in every run?

**Comment by biocodz** [comment]
As you can see from the execution trace, the index is verified on each run, and IF it exists, and the hashes are OK, the index IS Re-used.
In your case, the trace says:
`[index:104] Found 24 non-empty index files. Skipping indexing`
Remember NOT to delete `/home/tianyu/sortmerna/run/idx/`. Otherwise it will, of course, be rebuilt.
As I mentioned  'the index' Is re-usable (unlike kvdb)

**Comment by battlerb** [comment]
Oh, sorry I thought I need to delete entire workdir, now I know what to do. But I got another problem when I tried to run it from very beginning. 

![Screenshot from 2019-12-05 22-41-37](https://user-images.githubusercontent.com/50813246/70245291-caa95780-17b0-11ea-9d7b-387843a25c0c.png)
![Screenshot from 2019-12-05 22-43-53](https://user-images.githubusercontent.com/50813246/70245292-cb41ee00-17b0-11ea-9ecf-4c0a316ed5ba.png)

And my command is: ~/Programs/SortmeRNA/bin/sortmerna --ref ~/Programs/SortmeRNA/data/rRNA_databases/rfam-5.8s-database-id98.fasta --ref ~/Programs/SortmeRNA/data/rRNA_databases/rfam-5s-database-id98.fasta --ref ~/Programs/SortmeRNA/data/rRNA_databases/silva-bac-16s-id90.fasta --ref ~/Programs/SortmeRNA/data/rRNA_databases/silva-bac-23s-id98.fasta --ref ~/Programs/SortmeRNA/data/rRNA_databases/silva-arc-16s-id95.fasta --ref ~/Programs/SortmeRNA/data/rRNA_databases/silva-arc-23s-id98.fasta --ref ~/Programs/SortmeRNA/data/rRNA_databases/silva-euk-18s-id95.fasta --reads clean_data/C20190628m_L4_1_val_1.fq.gz --reads clean_data/C20190628m_L4_2_val_2.fq.gz --fastx -blast 1 -num_alignments 1 --other --paired_out --workdir sortmerna

**Comment by biocodz** [comment]
Wow, haven't seen yet a failing indexing:-)
The screenshots are not very handy to look at. 
I really need the whole trace from the start as there is some pre-run checks shown.
Can you copy-paste the trace like below ( or mail to me directly `biocodz at protonmail.com`):
```
[run] Running: sortmerna -ref data/silva-bac-16s-database-id85.fasta -reads data/set4_mate_pairs_metatranscriptomics_1.fastq.gz -reads data/set4_mate_pairs_metatranscriptomics_2.fastq.gz -num_alignments 1 -v

[process:1188] === Options processing starts ... ===

Found value: C:/Users/biocodz/a01_code/sortmerna/dist/t1/release\bin\sortmerna
Found flag: -ref
Found value: data/silva-bac-16s-database-id85.fasta of previous flag: -ref
Found flag: -reads
Found value: data/set4_mate_pairs_metatranscriptomics_1.fastq.gz of previous flag: -reads
Found flag: -reads
Found value: data/set4_mate_pairs_metatranscriptomics_2.fastq.gz of previous flag: -reads
Found flag: -num_alignments
Found value: 1 of previous flag: -num_alignments
Found flag: -threads
Found value: 6:2:2 of previous flag: -threads
Found flag: -a
Found value: 5 of previous flag: -a
Found flag: -v
[opt_workdir:1006] 'workdir' option was not provided. Using USERDIR to set the working directory: [C:/Users/biocodz\sortmerna/run]
[process:1271] Processing option: a with value: 5

WARNING: Option '-a' was Deprecated in favour of '-threads'. Redirecting to 'threads' ...
[process:1271] Processing option: num_alignments with value: 1
[process:1271] Processing option: reads with value: data/set4_mate_pairs_metatranscriptomics_1.fastq.gz
[opt_reads:74] Processing reads file [1] out of total [2] files
[process:1271] Processing option: reads with value: data/set4_mate_pairs_metatranscriptomics_2.fastq.gz
[opt_reads:74] Processing reads file [2] out of total [2] files
[process:1271] Processing option: ref with value: data/silva-bac-16s-database-id85.fasta
[opt_ref:168] Processing reference [1] out of total [1] references
[process:1271] Processing option: threads with value: 6:2:2

WARNING: Using more than a single Read thread is reserved for future implementation. Now using 1 thread

WARNING: Using more than a single Write thread is reserved for future implementation. Now using 1 thread
[process:1271] Processing option: v with value:

[process:1291] === Options processing done ===

[test_kvdb_path:1127] Key-value DB location (C:/Users/biocodz\sortmerna/run/kvdb)
[dirExists:111] Path does not exist: C:/Users/biocodz\sortmerna/run/kvdb
[test_kvdb_path:1155] Database (C:/Users/biocodz\sortmerna/run/kvdb) will be created
[validate:1313] No output format has been chosen (fastx/sam/blast/otu_map). Using default 'blast'
```

**Comment by battlerb** [comment]
Thanks for your reply. I have sent you an email about my issue. Please check your mailbox, you can find an email from cuitianyu66@qq.com.

**Comment by biocodz** [comment]
@battlerb Thanks for the information. So far I'm baffled. The indexing fails on the last file.  The  [test 17](https://github.com/biocore/sortmerna/blob/master/scripts/test.jinja.yaml#L347) that uses the same input, runs OK both on Linux and Windows on my laptop.

I wonder if there is a size quota set on your home directory? Is your PC on a network, or is it your own?

What is the output of the following
```
df -h
du -sh ~/
cat /etc/fstab
quota -q
repquota -a
```

**Comment by battlerb** [comment]
Thanks for your help. Yes, it is my own PC. I do not think I have any size quota set on my /home. 


The command output is showing below: 


tianyu@tianyu-MS-7B93:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev             16G     0   16G   0% /dev
tmpfs           3.2G  3.6M  3.2G   1% /run
/dev/nvme0n1p2   75G   15G   57G  20% /
tmpfs            16G   61M   16G   1% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs            16G     0   16G   0% /sys/fs/cgroup
/dev/loop1      4.2M  4.2M     0 100% /snap/gnome-calculator/406
/dev/loop0      150M  150M     0 100% /snap/gnome-3-28-1804/67
/dev/loop2       15M   15M     0 100% /snap/gnome-characters/296
/dev/sdb2       100M   38M   62M  38% /boot/efi
/dev/loop3       55M   55M     0 100% /snap/core18/1066
/dev/loop4       89M   89M     0 100% /snap/core/7270
/dev/loop5       43M   43M     0 100% /snap/gtk-common-themes/1313
/dev/loop6      1.0M  1.0M     0 100% /snap/gnome-logs/61
/dev/loop7      216M  216M     0 100% /snap/wine-platform-runtime/54
/dev/nvme0n1p3  154G   50G   97G  34% /home
/dev/loop8      3.8M  3.8M     0 100% /snap/gnome-system-monitor/100
tmpfs           3.2G   28K  3.2G   1% /run/user/121
tmpfs           3.2G   32K  3.2G   1% /run/user/1000



tianyu@tianyu-MS-7B93:~$ sudo du -sh ~/
[sudo] password for tianyu: 
49G	/home/tianyu/



tianyu@tianyu-MS-7B93:~$ sudo cat /etc/fstab
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
# / was on /dev/nvme0n1p2 during installation
UUID=db349143-8ac3-4ebb-9908-60621bdae50b /               ext4    errors=remount-ro 0       1
# /boot/efi was on /dev/sdc2 during installation
UUID=1021-1051  /boot/efi       vfat    umask=0077      0       1
# /home was on /dev/nvme0n1p3 during installation
UUID=4db66855-d32e-4605-ba27-89fedaa011d8 /home           ext4    defaults        0       2
/swapfile                                 none            swap    sw              0       0



However the 'quota -q' and 'repquota -a' did not output anything.




Regard,
Tianyu
------------------ Original ------------------

**Comment by biocodz** [comment]
Got your info. While I'm pondering over it, could you possibly try the following:

Purge the run/idx/ and
1. specify less than 7 refs e.g 2 or even 1
2. change the order of references on command line

Thanks

**Comment by biocodz** [comment]
The file `silva-euk-18s-id95.fasta` seems to be corrupted on your machine.
Comparing the indexing on my machine with yours, the following is seen:

```
rfam-5.8s-database-id98.fasta of size: 2280449 under index name idx/2169995244134016533
rfam-5.8s-database-id98.fasta of size: 2280449 under index name idx/2169995244134016533  mine

rfam-5s-database-id98.fasta of size: 8525326 under index name idx/13019673092862722585
rfam-5s-database-id98.fasta of size: 8525326 under index name idx/13019673092862722585  mine

silva-euk-18s-id95.fasta of size: 2623488 under index name idx/2700646386527218729
silva-euk-18s-id95.fasta of size: 13259584 under index name idx/2700646386527218729 mine
```
Note how the file size on your side 2623488 is different from mine 13259584 for `silva-euk-18s-id95.fasta`

How did you install the sortmerna?
What's the output of

```
ls -l ~/Programs/SortmeRNA/data/rRNA_databases/silva-euk-18s-id95.fasta
cksum ~/Programs/SortmeRNA/data/rRNA_databases/silva-euk-18s-id95.fasta
```

**Comment by battlerb** [comment]
I just decreased the number of reference sequence to 2. It is still running and did not report any error so far. I will let you know when it get done.

**Comment by battlerb** [comment]
tianyu@tianyu-MS-7B93:~/Programs/SortmeRNA/data/rRNA_databases$ cksum silva-euk-18s-id95.fasta 
852674569 2623488 silva-euk-18s-id95.fasta

tianyu@tianyu-MS-7B93:~/Programs/SortmeRNA/data/rRNA_databases$ ls -lh silva-euk-18s-id95.fasta 
-rw-r--r-- 1 tianyu tianyu 2.6M Dec  5 19:49 silva-euk-18s-id95.fasta

It seems my reference is not complete, which leads to my issue.

**Comment by biocodz** [comment]
You can just download the file from gtihub:
```
wget https://github.com/biocore/sortmerna/blob/master/data/rRNA_databases/silva-euk-18s-id95.fasta
```

**Comment by battlerb** [comment]
Thanks, I have solved my issue. I re-downloaded those reference fasta files and tested again, it worked perfectly

**Comment by biocodz** [comment]
Good news! 
In the upcoming release 4.0.1 we will add a better validation of all files
