### ISSUE TITLE
How to un-merge paired read in SortMeRNA 4+

### ISSUE THREAD

**Issue by rohitsuratekar** [biocore/sortmerna#202]
In previous version, there was dedicated script (_unmerge-paired-reads.sh_) which was useful in un-merging paired end reads after rRNA filtering is done. Is there any option in current version (4.0.0) where I can un-merge my paired end reads? Is there any third party tool is available for this? 

Currently, I can think of splitting it myself by just separating every second read in output fastq file just like old version (like [this](https://github.com/biocore/sortmerna/blob/5cfa3ab28792dc3130fd880d2615f2bb039715d1/scripts/unmerge-paired-reads.sh)).  However, is it the correct way of doing it?

**Comment by biocodz** [comment]
There is currently no option and no built-in functionality for writing two separate files for aligned reads. We will add it an upcoming release. 
Meanwhile the old 'unmerge' script can be used just fine.

**Comment by rohitsuratekar** [comment]
@biocodz `-out2` sounds good ! I recently used old 'unmerge' script and it works like a charm.

**Comment by biocodz** [comment]
The option `-out2` was introduced in release `4.1.0`.
