### ISSUE TITLE
Question: parameters for sRNA-seq data

### ISSUE THREAD

**Issue by OnlyHigh** [biocore/sortmerna#203]
Hello,
I've trying to filter out unwanted RNA data such as tRNAs and rRNA from sRNA-seq data using the following CMD:
```
sortmerna -a 4 -L 12 --fastx --ref rRNA.fasta --other $samplename"-stna-1.fq.gz" --workdir ~/1_Trimming/sortmerna/ --reads $samplename".fq.gz"
```

Even if the command line works I found many less rRNA reads, and it says the minimum and maximum read length is 50 bp, 

Are there someother parameters I need to tune to filter correctly the rRNAs with sortmeRNA?

Thanks, 
Luis Alfonso.

**Comment by ekopylova** [comment]
Hello Luis,

Which SMR version are you running?
Did you create the database rRNA.fasta? How many sequences are in it?
Do you expect many more rRNAs than what was identified?
Do you have many short reads in your data?

Thanks!!
Jenya

**Comment by OnlyHigh** [comment]
Hello Jenya,
I'm using 4.0.0 version (the latest one),
I created the database with the nuc-rRNA, mt-rRNA and the endosimbiont rRNA (the data is from a bacteriome),
I expect around 50% of rRNA and I'm getting 2%, 
The size of the reads is from 10 to 60 with the median around 20 bp (TruSeq Small RNA library),

Cheers

**Comment by ekopylova** [comment]
Hello @OnlyHigh , SMR works by first identifying short matches between your read and the database (18 nucleotides by default with possibility of 1 error - mismatch or indel), if your read is shorter than 18 nt, then the algorithm cannot work, therefore SMR skips those reads. You can try using a shorter match length by setting the parameter ```-L```, for example ```-L 16```. We have tested with k-mers lengths down to ```-L 14```. Note, reducing ```-L``` will increase the runtime.

Another issue could be that your reads have many errors with respect to your database (e.g. the database is too small or your reads have more errors than the threshold). You could try to increase the e-value to a higher number, e.g. ```-e 100``` to be more lenient.

If you send me a FASTA file with 10 sequences you expect to match to the database, as well as your database, then I can take a look further on what can be done. Please send to gmail at address jenya.kopylov

Thanks!

**Comment by OnlyHigh** [comment]
Hello Jenya, 
I'll try those parameters and see if they work better (or if they don't work I'll send you the email)
