### ISSUE TITLE
typo 

### ISSUE THREAD

**Issue by GaioDany** [biocore/sortmerna#204]
Hi guys, in your user man page 
bash sortmerna-4.0.0-Linux.sh --skip-license
should be linux not capital. copy pasted the command and didn't see what the problem was right away. thank u

**Comment by biocodz** [comment]
@GaioDany 
Thanks for noticing.  Fixed (changed the letter to Capital to match the distro file name [sortmerna-4.0.0-Linux.sh](https://github.com/biocore/sortmerna/releases/download/v4.0.0/sortmerna-4.0.0-Linux.sh)
