### ISSUE TITLE
Sortmerna didn't filter rRNA reads as expected.

### ISSUE THREAD

**Issue by Kennyluo4** [biocore/sortmerna#207]
Hello,
I'm using SMR v4.0.0 to filter rRNA reads in my small RNA seq data.
I collected the rRNA for my species, which includes rRNA sequence from NCBI, Silva and RNACentral. Besides, I also put a long rDNA scaffold sequence from the genome database, and removed redundant sequence. 
The adaptor and low quality bases were trimmed using cutadapt before filtering.
I ran the program as:
`sortmerna -m 4096 -a 6 --fastx --blast --workdir . --ref ~/ufrc/../rRNA_index.fasta --reads test.fq --other test2_mir.fq`

I did the QC after the filtering, there were some overrepresented reads in the data which were blasted to rRNA. 
For example. CCCTTGTCGCTTCGATTCGT occurred 201101 times in the test data, and blast to nr result showed that it is rRNA. I searched this sequence in the rRNA_index.fasta file I prepared. And it can perfectly match to the rDNA scaffold at multiple loci.  I tried to adjust -L and --id but the result is similar. 
Is it because the subject (scaffold) is too long and it do not remove reads aligned to it? How can I solve this issue?

After revisiting the manual, I guess the --best and  --num-alignments might lead to this result, the default --best is 1, which report 1 best hit. I didn't quite understand this two parameters before. Does this mean the other perfect match reads will not be reported/filtered? If so, it seems very dangerous to set the default best hit as 1. Besides, I don't see the default setting for --num-alignments. I will try to set both as 0 to see if the filter is complete.

Regards,
Kenny

**Comment by biocodz** [comment]
@Kennyluo4 Hi, thank you for the input. 
`-best` and `-num_alignments` are mutually exclusive options i.e. either one of them can be used at a time. 
`-best` can be used together with `-min_lis` to specify the minimum number of seed hits prior attempting the alignment. By default `-min_lis` is 2 i.e. at least two seeds have to be found on a reference prior the alignment. You can try `-min_lis 1` to specify a single seed hit.
Please, try `-num_aligments 0`, or `-best 0 -min_lis 1` to obtain max number of matches.

I guess the docs on these two options need an improvement.

**Comment by Kennyluo4** [comment]
> @Kennyluo4 Hi, thank you for the input.
> `-best` and `-num_alignments` are mutually exclusive options i.e. only one of them can be used at a time. An error is thrown when both options are specified.
> 
> `-best` can be used together with `-min_lis` to specify the minimum number of seed hits prior attempting the alignment. By default `-min_lis` is 2 i.e. at least two seeds have to be found on a reference prior the alignment. You can try `-min_lis 1` to specify a single seed hit.
> 
> Please, try `-num_alignments 0`, or `-best 0 -min_lis 1` to obtain max number of matches.
> You can also play with the seed length (18 nt by default) e.g. `-L 10` for a more fine-grained search
> 
> I guess the docs on these two options need an improvement.

Thanks for the information. I didn't know the `-min_lis` setting before. However the filtering is not affected by these parameters.  Those commands are what I have tried:
`sortmerna -m 4096 -a 4 -L 8 --fastx --blast 1 --workdir test --num_alignments 0 --ref /path/rRNA_index.fasta --reads test.fq --other test2_mir.fq`
result:
>    Total reads passing E-value threshold = 300025 (2.00)
>    Total reads failing E-value threshold = 14699975 (98.00)

`sortmerna -m 4096 -a 4 -L 8 --fastx --blast 1 --workdir test --best 0 --ref /path/rRNA_index.fasta --reads test.fq --other test2_mir.fq`
result:
> Total reads passing E-value threshold = 300025 (2.00)
> Total reads failing E-value threshold = 14699975 (98.00)

`sortmerna -m 4096 -a 4 -L 10 --fastx --blast 1 --workdir test --best 0 -min_lis 1 --ref /path/rRNA_index.fasta --reads test.fq --other test2_mir.fq`
result:
>Total reads passing E-value threshold = 300024 (2.00)
>Total reads failing E-value threshold = 14699976 (98.00)

I searched the rRNA read CCCTTGTCGCTTCGATTCGT in "other.fq" and it's still there. Interesting thing is, other rRNA reads with a few bases longer than this fragment is filtered out such as CCCTTGTCGCTTCGATTCGTCCCTCC.
To test if it's because of the rRNA file I used, I tried SMR using silva-euk-28s-id98.fasta and silva-euk-18s-id95.fasta. Here is the result:
 >   Total reads passing E-value threshold = 7848 (0.05)
>    Total reads failing E-value threshold = 14992152 (99.95)

And the sequence CCCTTGTCGCTTCGATTCGT is still not filtered out. Surprisingly, I can search it in silva-euk-28s-id98.fasta and find a perfect match. 
I really don't know to to deal with it now.

**Comment by ekopylova** [comment]
Hello,

Could you provide us with the test reads file?

Thanks,
Jenya

⁣

**Comment by Kennyluo4** [comment]
Hi Jenya,
Here is the link to my test data: https://drive.google.com/file/d/1gBFzOLWEVNAiC6Q9wfA5qlR0wwlxG8EW/view?usp=sharing
Thanks for taking time looking into it.
Kenny

**Comment by biocodz** [comment]
@Kennyluo4 Thank you for the input. 

I tested your data. The reads are very short with min length of 18 nt, and max of 45 nt. 

The sortmerna algorithm evaluates Statistical Significance  of each alignment, and apparently in your case, many alignments are ignored because they don't pass the filtering threshold, in spite the local similarity. 

You should use `-e` option to relax the threshold. By default `-e` is 1. Increasing it to e.g. `-e 100` relaxes the threshold. 

For example
```
sortmerna -ref sortmerna/data/rRNA_databases/silva-euk-28s-id98.fasta -reads smr_iss_207_20200123_test.fq.gz -fastx -blast 1
```
gives
```
 Results:
    Total reads passing E-value threshold = 1696 (0.01)
    Total reads failing E-value threshold = 14998304 (99.99)
    Minimum read length = 18
    Maximum read length = 45
    Mean read length    = 22

 Coverage by database:
    sortmerna/data/rRNA_databases/silva-euk-28s-id98.fasta		0.01
```

Using `-e 100`
```
sortmerna -ref sortmerna/data/rRNA_databases/silva-euk-28s-id98.fasta -reads smr_iss_207_20200123_test.fq.gz -e 100 -fastx -blast 1
```

gives
```
 Results:
    Total reads passing E-value threshold = 798426 (5.32)
    Total reads failing E-value threshold = 14201574 (94.68)
    Minimum read length = 18
    Maximum read length = 45
    Mean read length    = 22

 Coverage by database:
    sortmerna/data/rRNA_databases/silva-euk-28s-id98.fasta		5.32
```

As you can see, many more reads get filtered

**Comment by Kennyluo4** [comment]
@biocodz 
Thank you very much for testing the data. I tried the `-e 100` and did see more filtered reads. But there are still a few  rRNA reads left, I guess I just need to increase `-e` value more. 
Besides, could you please explain how does the `-e` work? I didn't see detailed explanation on this option from the manual or `--help`.  And if I try to filter longer read data(e.g. 125 bp), should I worry about this issue?

**Comment by biocodz** [comment]
Explaining the `-e` is not trivial considering the Sortmerna algorithm was the subject of a bioinformatics PHD thesis.
	
The `-e E` value allows to modify the minimal alignment score required for an alignment to be considered 'statistically significant'.
	
Here is the original formula used to calculate the cut-off alignment score
```
E = K*m*n*exp(-λS)
	E is the expectation value
	S is the alignement score
	K,λ are parameters of the Gumbel distribution
	m,n are characteristic lengths of the reads, and references correspondingly.
	K,m,n,λ are all calculated from reference and reads data, and the scoring matrix.
```
Because the exponential dependency between E and S, a big change in E is required to affect S
In the tests described above:
With `-e 1` (default)
```
	Gumbel lambda = 0.612082
        Gumbel K = 0.345772
        Minimal SW score based on E-value = 55
```
With `-e 100`
```
        Gumbel lambda = 0.612082
        Gumbel K = 0.345772
        Minimal SW score based on E-value = 47
```
		
You can try `-e 1000` and higher values to futher relax the filtering threshold.

**Comment by Kennyluo4** [comment]
@biocodz  Thanks for the explaination. It's very useful to know about the algorithm behind the options.
