### ISSUE TITLE
Stuck / looping prior to prior to processing reads files

### ISSUE THREAD

**Issue by louellette** [biocore/sortmerna#208]
I'm running on a ubuntu 16.04 server with plenty of memory and cpu available.  I have successfully run on one set of files but now, with the second set of files the sortmerna task runs at 100% cpu and never ends.  Attached output.  Any help is much appreciated.  
[sortmerna issue.txt](https://github.com/biocore/sortmerna/files/4098667/sortmerna.issue.txt)

**Comment by biocodz** [comment]
Hi,
The directory `/test/dev/louellette/sortmerna/run/kvdb/*` has to be Empty prior each new run.
Note that index files `/test/dev/louellette/sortmerna/run/idx/*`, on the other hand, can be reused i.e. the indexing only needs to be done once.

**Comment by louellette** [comment]
Removing the files didn't help.  I even tried deleting the entire /test/dev/louellette/sortmerna directory and rebuilding the indexes but I'm still looping somewhere before starting to read the reads files.  I tried several sets of files.  Any other suggestions?

**Comment by louellette** [comment]
I gunzipped my read files and deleted my run directory and started from scratch with the uncompressed read files and I got it to work.  Sorry for the trouble.

**Comment by biocodz** [comment]
@louellette
I haven't had problems processing compressed files in many tests and runs so far.  Would be good to find the root cause of your problem. 
In any case it's good to know you have managed to resolve the problem for now. Thanks for the input.
