### ISSUE TITLE
[pop:108] write_queue Popped readKilled: 

### ISSUE THREAD

**Issue by QianqianJena** [biocore/sortmerna#213]
Dear SortMeRNA users,
When running sortmerna 4.0 program for my samples, it interrupted and shown the above message.
Does anyone come across this problem and have any idea why it comes?
By the way, does anyone have further comments and suggestions on speeding up the sortmerna program?
It runs so slowly for my samples compared to sortmerna 2.1.
Here is the command:
sortmerna -ref rRNA_databases/silva-bac-16s-id90.fasta -ref rRNA_databases/silva-bac-23s-id98.fasta -ref rRNA_databases/silva-arc-16s-id95.fasta -ref /rRNA_databases/silva-arc-23s-id98.fasta -ref rRNA_databases/silva-euk-18s-id95.fasta -ref rRNA_databases/silva-euk-28s-id98.fasta -ref rRNA_databases/rfam-5s-database-id98.fasta -ref rRNA_databases/rfam-5.8s-database-id98.fasta -reads f_qc.fastq -reads r_qc.fastq --workdir mrna_4.0 --fastx --other mrna_non.fastq --paired_in -v -a 10. 
I look forward to your reply.
Thank you very much.
Best regards,
Qianqian

**Comment by biocodz** [comment]
@QianqianJena 
Hi,
this is a second issue opened by you, and you haven't provided any feedback on the previous one [issue 212](https://github.com/biocore/sortmerna/issues/212)
It creates confusion, as it is hard to tell if the issues are the same or different.
Thank you

**Comment by QianqianJena** [comment]
Hi,
I sent the email regarding my last issue to you by the email address last Friday. 
I have no idea why you don't get it.
I will upload my email to the last issue.
Best,
Qianqian

**Comment by biocodz** [comment]
Got it now! Thanks. Investigating ...

**Comment by egoetz223** [comment]
Hello, was this issue ever resolved? I am having the same problem with 4.0. 

My command: 
sortmerna -ref /home/egoetz/nas2/SILVA_138_SSURef_NR99_Bacteria.fasta -reads /home/egoetz/nas1/cuvier_upload/S78_01_L001_R1_001_trim_paired.fastq -reads /home/egoetz/nas1/cuvier_upload/S78_01_L001_R2_001_trim_paired.fastq -workdir SortmeRNA_outputs_bact_S78/ -fastx -v

The last three lines of the  were:
Processor proc_52 thread 139762505467648 started
[run:70] thread: 139763243796224 started
[pop:108] readKillede Popped read number: 2600011

My output files are also empty. 

I should mention that I successfully ran sortmerna on other, smaller files... so maybe this has something to do with the size? 

Thanks,
Elly

**Comment by biocodz** [comment]
would be good to have a look at your [execution trace](https://github.com/biocore/sortmerna#execution-trace)
What's the size of your files i.e.
```
ls -l /home/egoetz/nas1/cuvier_upload/S78_01_L001_R1_001_trim_paired.fastq
wc -l /home/egoetz/nas1/cuvier_upload/S78_01_L001_R1_001_trim_paired.fastq
```
?

How long does it take from the start until the error happens?

**Comment by egoetz223** [comment]
Hi,

Thank you for your response!

It takes about an hour until the error happens. 

S78_01_L001_R1_001_trim_paired.fastq is 3.1G, 31734760 lines. 
S78_01_L001_R2_001_trim_paired.fastq is 2.9G, 31734760 lines. 

The reference database (SILVA_138_SSURef_NR99_Bacteria.fasta) is 645M.

**My execution trace:**

$sortmerna -ref /home/egoetz/nas2/SILVA_138_SSURef_NR99_Bacteria.fasta -reads /home/egoetz/nas1/cuvier_upload/S198_01_L001_R1_001_trim_paired.fastq -reads /home/egoetz/nas1/cuvier_upload/S198_01_L001_R2_001_trim_paired.fastq -workdir SortmeRNA_outputs_bact/ -fastx -v

[process:1369] === Options processing starts ... ===

Found value: sortmerna
Found flag: -ref
Found value: /home/egoetz/nas2/SILVA_138_SSURef_NR99_Bacteria.fasta of previous flag: -ref
Found flag: -reads
Found value: /home/egoetz/nas1/cuvier_upload/S198_01_L001_R1_001_trim_paired.fastq of previous flag: -reads
Found flag: -reads
Found value: /home/egoetz/nas1/cuvier_upload/S198_01_L001_R2_001_trim_paired.fastq of previous flag: -reads
Found flag: -workdir
Found value: SortmeRNA_outputs_bact/ of previous flag: -workdir
Found flag: -fastx
Previous flag: -fastx is Boolean. Setting to True
Found flag: -v
[opt_workdir:1066] Using WORKDIR: ["/home/egoetz/SortmeRNA_outputs_bact/"] as specified
[process:1453] Processing option: fastx with value: 
[process:1453] Processing option: reads with value: /home/egoetz/nas1/cuvier_upload/S198_01_L001_R1_001_trim_paired.fastq
[opt_reads:73] Processing reads file [1] out of total [2] files
[process:1453] Processing option: reads with value: /home/egoetz/nas1/cuvier_upload/S198_01_L001_R2_001_trim_paired.fastq
[opt_reads:73] Processing reads file [2] out of total [2] files
[process:1453] Processing option: ref with value: /home/egoetz/nas2/SILVA_138_SSURef_NR99_Bacteria.fasta
[opt_ref:166] Processing reference [1] out of total [1] references
[opt_ref:220] File ["/home/egoetz/nas2/SILVA_138_SSURef_NR99_Bacteria.fasta"] exists and is readable
[process:1453] Processing option: v with value: 

[process:1473] === Options processing done ===

[validate_kvdbdir:1252] Key-value DB location "/home/egoetz/SortmeRNA_outputs_bact/kvdb"
[validate_kvdbdir:1288] Creating KVDB directory: "/home/egoetz/SortmeRNA_outputs_bact/kvdb"
[validate_aligned_pfx:1307] Checking output directory: "/home/egoetz/SortmeRNA_outputs_bact/out"

  Program:      SortMeRNA version 4.2.0
  Copyright:    2016-2020 Clarity Genomics BVBA:
                Turnhoutseweg 30, 2340 Beerse, Belgium
                2014-2016 Knight Lab:
                Department of Pediatrics, UCSD, La Jolla
                2012-2014 Bonsai Bioinformatics Research Group:
                LIFL, University Lille 1, CNRS UMR 8022, INRIA Nord-Europe
  Disclaimer:   SortMeRNA comes with ABSOLUTELY NO WARRANTY; without even the
                implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
                See the GNU Lesser General Public License for more details.
  Contributors: Jenya Kopylova   jenya.kopylov@gmail.com
                Laurent Noé      laurent.noe@lifl.fr
                Pierre Pericard  pierre.pericard@lifl.fr
                Daniel McDonald  wasade@gmail.com
                Mikaël Salson    mikael.salson@lifl.fr
                Hélène Touzet    helene.touzet@lifl.fr
                Rob Knight       robknight@ucsd.edu

[main:63] Running command:
sortmerna -ref /home/egoetz/nas2/SILVA_138_SSURef_NR99_Bacteria.fasta -reads /home/egoetz/nas1/cuvier_upload/S198_01_L001_R1_001_trim_paired.fastq -reads /home/egoetz/nas1/cuvier_upload/S198_01_L001_R2_001_trim_paired.fastq -workdir SortmeRNA_outputs_bact/ -fastx -v 

  Parameters summary: 
    K-mer size: 19
    K-mer interval: 1
    Maximum positions to store per unique K-mer: 10000

  Total number of databases to index: 1

[build_index:1189] Begin indexing file /home/egoetz/nas2/SILVA_138_SSURef_NR99_Bacteria.fasta of size: 676211974 under index name SortmeRNA_outputs_bact/idx/3653619276191977187
  Collecting nucleotide distribution statistics ..  done  [6.592046 sec]

  start index part # 0: 
    (1/3) building burst tries .. done  [299.242046 sec]
    (2/3) building CMPH hash .. done  [218.989034 sec]
    (3/3) building position lookup tables .. done [2681.168600 sec]
    total number of sequences in this part = 226387
      temporary file was here: SortmeRNA_outputs_bact/sortmerna_keys_39295.txt
      writing kmer data to SortmeRNA_outputs_bact/idx/3653619276191977187.kmer_0.dat

      writing burst tries to SortmeRNA_outputs_bact/idx/3653619276191977187.bursttrie_0.dat
      writing position lookup table to SortmeRNA_outputs_bact/idx/3653619276191977187.pos_0.dat

  start index part # 1: 
    (1/3) building burst tries .. done  [288.695137 sec]
    (2/3) building CMPH hash .. done  [32.871100 sec]
    (3/3) building position lookup tables .. done [2626.072098 sec]
    total number of sequences in this part = 205636
      temporary file was here: SortmeRNA_outputs_bact/sortmerna_keys_39295.txt
      writing kmer data to SortmeRNA_outputs_bact/idx/3653619276191977187.kmer_1.dat

      writing burst tries to SortmeRNA_outputs_bact/idx/3653619276191977187.bursttrie_1.dat
      writing position lookup table to SortmeRNA_outputs_bact/idx/3653619276191977187.pos_1.dat
      writing nucleotide distribution statistics to SortmeRNA_outputs_bact/idx/3653619276191977187.stats
    done.

[calculate:107] Starting statistics calculation on file: '/home/egoetz/nas1/cuvier_upload/S198_01_L001_R1_001_trim_paired.fastq'  ...   [calculate:225] Done statistics on file. Elapsed time: 6.01 sec. all_reads_count= 9228993
[calculate:107] Starting statistics calculation on file: '/home/egoetz/nas1/cuvier_upload/S198_01_L001_R2_001_trim_paired.fastq'  ...   [calculate:225] Done statistics on file. Elapsed time: 5.80 sec. all_reads_count= 18457986
[store_to_db:421] Stored Reads statistics to DB:
    min_read_len= 36 max_read_len= 301 all_reads_count= 18457986 all_reads_len= 2775334983 total_reads_mapped= 0 total_reads_mapped_cov= 0 reads_matched_per_db= TODO is_total_reads_mapped_cov= 0 is_stats_calc= 0

[init:101] Testing file: "/home/egoetz/SortmeRNA_outputs_bact/out/aligned.fastq"
[init:218] Testing file: "/home/egoetz/SortmeRNA_outputs_bact/out/aligned.log"

[align:359] ==== Starting alignment ====

[align:369] Using default number of Processor threads equals num CPU cores: 128
Number of cores: 128 Read threads:  1 Write threads: 1 Processor threads: 128
[ThreadPool:36] initialized Pool with: [130] threads

[ReadsQueue:57] [read_queue] created with [1] Pushers
[ReadsQueue:57] [write_queue] created with [128] Pushers
[Refstats:32] Index Statistics calculation Start ...[Refstats:42] Done. Time elapsed: 0.65 sec

[align:409] Loading index 0 part 1/2 ... done [5.61] sec
[align:422] Loading references  ... done [0.83] sec
Processor proc_21 thread 140332670899968 started
Processor proc_23 thread 140332645721856 started
Processor proc_22 thread 140332771546880 started
Processor proc_47 thread 140332452689664 started
Processor proc_59 thread 140332343584512 started
Processor proc_63 thread 140332301620992 started
Processor proc_70 thread 140332242872064 started
Processor proc_96 thread 140332066625280 started
Processor proc_97 thread 140332058232576 started
Processor proc_108 thread 140331957520128 started
Processor proc_123 thread 140331873593088 started
Processor proc_31 thread 140332561794816 started
Processor proc_30 thread 140332654114560 started
Processor proc_36 thread 140332519831296 started
Processor proc_16 thread 140332779939584 started
Processor proc_35 thread 140332545009408 started
Processor proc_38 thread 140332494653184 started
Processor proc_39 thread 140332503045888 started
[write:19] Writer writer_0 thread 140333325203200 started
Processor proc_41 thread 140332637329152 started
Processor proc_44 thread 140332486260480 started
Processor proc_24 thread 140332628936448 started
Processor proc_3 thread 140333216163584 started
Processor proc_29 thread 140332570187520 started
Processor proc_45 thread 140332469475072 started
Processor proc_42 thread 140332477867776 started
Processor proc_17 thread 140332788332288 started
Processor proc_32 thread 140332620543744 started
Processor proc_28 thread 140332612151040 started
Processor proc_43 thread 140332578580224 started
Processor proc_48 thread 140332444296960 started
Processor proc_50 thread 140332419118848 started
Processor proc_6 thread 140333199378176 started
Processor proc_49 thread 140332427511552 started
Processor proc_20 thread 140332679292672 started
Processor proc_57 thread 140332402333440 started
Processor proc_51 thread 140332410726144 started
Processor proc_52 thread 140332393940736 started
Processor proc_55 thread 140332377155328 started
Processor proc_58 thread 140332335191808 started
Processor proc_53 thread 140332435904256 started
Processor proc_56 thread 140332368762624 started
Processor proc_54 thread 140332360369920 started
Processor proc_61 thread 140332310013696 started
Processor proc_60 thread 140332318406400 started
Processor proc_19 thread 140332687685376 started
Processor proc_69 thread 140332259657472 started
Processor proc_62 thread 140332284835584 started
Processor proc_72 thread 140332234479360 started
Processor proc_65 thread 140332351977216 started
Processor proc_66 thread 140332268050176 started
Processor proc_64 thread 140332461082368 started
Processor proc_67 thread 140332251264768 started
Processor proc_74 thread 140332226086656 started
Processor proc_68 thread 140332276442880 started
Processor proc_75 thread 140332326799104 started
Processor proc_18 thread 140332905764608 started
Processor proc_27 thread 140332595365632 started
Processor proc_88 thread 140332091803392 started
Processor proc_84 thread 140332108588800 started
Processor proc_89 thread 140332049839872 started
Processor proc_79 thread 140332125374208 started
Processor proc_90 thread 140332075017984 started
Processor proc_77 thread 140332133766912 started
Processor proc_93 thread 140332033054464 started
Processor proc_95 thread 140332024661760 started
Processor proc_76 thread 140332209301248 started
Processor proc_71 thread 140332293228288 started
Processor proc_94 thread 140332385548032 started
Processor proc_83 thread 140332158945024 started
Processor proc_26 thread 140332603758336 started
Processor proc_86 thread 140332083410688 started
Processor proc_85 thread 140332142159616 started
Processor proc_73 thread 140332217693952 started
Processor proc_87 thread 140332175730432 started
Processor proc_99 thread 140332041447168 started
Processor proc_100 thread 140332007876352 started
Processor proc_78 thread 140332116981504 started
Processor proc_102 thread 140331991090944 started
Processor proc_92 thread 140332200908544 started
Processor proc_101 thread 140331999483648 started
Processor proc_91 thread 140332167337728 started
Processor proc_111 thread 140331907163904 started
Processor proc_104 thread 140331940734720 started
Processor proc_82 thread 140332150552320 started
Processor proc_105 thread 140331965912832 started
Processor proc_112 thread 140331915556608 started
Processor proc_109 thread 140331923949312 started
Processor proc_106 thread 140331949127424 started
Processor proc_81 thread 140332184123136 started
Processor proc_98 thread 140332100196096 started
Processor proc_2 thread 140333308417792 started
Processor proc_110 thread 140331932342016 started
Processor proc_103 thread 140331982698240 started
Processor proc_113 thread 140331881985792 started
Processor proc_114 thread 140331898771200 started
Processor proc_115 thread 140331890378496 started
Processor proc_107 thread 140331974305536 started
Processor proc_124 thread 140331814844160 started
Processor proc_80 thread 140332192515840 started
Processor proc_118 thread 140331848414976 started
Processor proc_117 thread 140331856807680 started
Processor proc_25 thread 140332662507264 started
Processor proc_116 thread 140331865200384 started
Processor proc_7 thread 140333190985472 started
Processor proc_125 thread 140332016269056 started
Processor proc_120 thread 140331823236864 started
Processor proc_122 thread 140331806451456 started
Processor proc_119 thread 140331831629568 started
Processor proc_121 thread 140331840022272 started
Processor proc_126 thread 140331798058752 started
Processor proc_37 thread 140332586972928 started
Processor proc_127 thread 140331789666048 started
Processor proc_8 thread 140332914157312 started
Processor proc_9 thread 140332821903104 started
Processor proc_11 thread 140332813510400 started
Processor proc_14 thread 140332939335424 started
Processor proc_0 thread 140333174200064 started
Processor proc_13 thread 140332947728128 started
Processor proc_4 thread 140333224556288 started
Processor proc_34 thread 140332528224000 started
Processor proc_40 thread 140332511438592 started
Processor proc_12 thread 140333182592768 started
Processor proc_5 thread 140333207770880 started
Processor proc_10 thread 140332805117696 started
Processor proc_15 thread 140332796724992 started
Processor proc_33 thread 140332553402112 started
Processor proc_46 thread 140332536616704 started
Processor proc_1 thread 140332956120832 started
[run:70] thread: 140333316810496 started
[pop:108] read_queue Popped read number: 3149999Killed

**Comment by biocodz** [comment]
The process has been killed right at the start of the alignment. Feels almost like the system watchdog killed it.
What's the output of 
```
uname -a
ulimit -a
df -h
ls -l SortmeRNA_outputs_bact/idx/
```

Would be good also to see the top output but the time until the crash is too short, so you might not be able to catch the screenshot. 
Just in case as soon as the process starts, run `top` and shift-H, followed by shift-V and scroll to 'sortmerna' i.e. something like:

```
top - 17:11:08 up 27 min,  2 users,  load average: 2.00, 4.27, 4.55
Threads: 231 total,   2 running, 168 sleeping,   0 stopped,   0 zombie
%Cpu(s): 17.3 us,  0.6 sy,  0.0 ni, 82.1 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 15835412 total,  9975288 free,  1655204 used,  4204920 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 13843480 avail Mem

 PID USER   PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
7753 root   20   0 1002388 132192  41940 S  0.0  0.8   0:01.10   `- python
7769 root   20   0 3307884 772992   6228 S  0.0  4.9   4:08.34       `- sortmerna
7783 root   20   0 3307884 1.282g   6228 S  0.0  8.5   0:11.51        `- rocksdb:low0
7784 root   20   0 3307884 1.282g   6228 S  0.0  8.5   0:13.45        `- rocksdb:low1
7785 root   20   0 3307884 1.282g   6228 S  0.0  8.5   0:16.80        `- rocksdb:low2
7786 root   20   0 3307884 1.282g   6228 S  0.0  8.5   0:18.90        `- rocksdb:low3
7787 root   20   0 3307884 1.282g   6228 S  0.0  8.5   0:19.35        `- rocksdb:low4
7788 root   20   0 3307884 1.282g   6228 S  0.0  8.5   0:19.15        `- rocksdb:low5
7789 root   20   0 3307884 1.282g   6228 S  0.0  8.5   0:19.33        `- rocksdb:low6
7790 root   20   0 3307884 1.282g   6228 S  0.0  8.5   0:19.41        `- rocksdb:low7
7791 root   20   0 3307884 1.282g   6228 S  0.0  8.5   0:19.21        `- rocksdb:low8
7792 root   20   0 3307884 1.282g   6228 S  0.0  8.5   0:19.29        `- rocksdb:low9
7793 root   20   0 3307884 1.282g   6228 S  0.0  8.5   0:00.00        `- rocksdb:low10
7794 root   20   0 3307884 1.282g   6228 S  0.0  8.5   0:00.00        `- rocksdb:low11
7795 root   20   0 3307884 1.282g   6228 S  0.0  8.5   0:00.00        `- rocksdb:low12
7796 root   20   0 3307884 1.282g   6228 S  0.0  8.5   0:00.00        `- rocksdb:low13
7797 root   20   0 3307884 1.282g   6228 S  0.0  8.5   0:00.00        `- rocksdb:low14
7798 root   20   0 3307884 1.282g   6228 S  0.0  8.5   0:07.56        `- rocksdb:low15
7799 root   20   0 3307884 1.282g   6228 S  0.0  8.5   0:49.49        `- rocksdb:high0
7800 root   20   0 3307884 1.282g   6228 S  0.0  8.5   0:39.17        `- rocksdb:high1
7801 root   20   0 3307884 1.282g   6228 S  0.0  8.5   0:31.42        `- rocksdb:high2
7802 root   20   0 3307884 1.282g   6228 S  0.0  8.5   0:45.47        `- rocksdb:high3
7803 root   20   0 3307884 1.282g   6228 S  0.0  8.5   0:00.00        `- sortmerna
7819 root   20   0 3307884 1.282g   6228 S  0.0  8.5   0:00.00        `- rocksdb:dump_st
7820 root   20   0 3307884 1.282g   6228 S  0.0  8.5   0:00.00        `- rocksdb:pst_st
7821 root   20   0 3307884 1.282g   6228 R 91.4  8.5   4:35.09        `- sortmerna
7822 root   20   0 3307884 1.282g   6228 R 91.0  8.5   3:42.21        `- sortmerna
7823 root   20   0 3307884 1.282g   6228 S 44.5  8.5   4:08.55        `- sortmerna
7824 root   20   0 3307884 1.282g   6228 R 90.0  8.5   4:35.01        `- sortmerna
7825 root   20   0 3307884 1.282g   6228 R 88.4  8.5   4:34.03        `- sortmerna
7826 root   20   0 3307884 1.282g   6228 R 93.0  8.5   4:34.55        `- sortmerna
7827 root   20   0 3307884 1.282g   6228 R 93.4  8.5   4:35.19        `- sortmerna
7828 root   20   0 3307884 1.282g   6228 R 88.0  8.5   3:41.76        `- sortmerna
7829 root   20   0 3307884 1.282g   6228 R 93.7  8.5   4:35.07        `- sortmerna
```

**Comment by biocodz** [comment]
Don't see anything wrong. The index files are big (pos_0 ~2GiB) but the system has enough resources to handle them.

The alignment starts OK but chokes on some read.

I would try testing the same reads against databases provided with the sortmerna distribution.

Using 128 threads makes no sense with this version of Sortmerna due [issue 231](https://github.com/biocore/sortmerna/issues/231). I suggest no more than 32 threads. It may improve the performance.

**Comment by egoetz223** [comment]
Hi, 

Sorry for the delay. I tried running it with the databases provided and it was successful. I am going to continue using these for my analyses.

Thank you for all your help
