### ISSUE TITLE
Change name of --fastx and --other output files

### ISSUE THREAD

**Issue by Roman-Si** [biocore/sortmerna#215]
Hello,
is there a way to change the name of the output files of --fastx and --other or are they always aligned.fq and other.fq ?
For example i tried this:
for file1 in *.fq
do
$sortmeRNA --a 20 --ref $dbs/silva-euk-28s-id98.fasta --reads $file1 --workdir ${file1%%.fq}".sortmeRna" --fastx ${file1%%.fq}".rRNA.fq" --other ${file1%%.fq}".other.fq"
echo ''$file1 ready `date`''
done

or even ' --fastx rRna.fq --other noRrna.fq'
but i still get: aligned.fq  aligned.log  other.fq 
in my /out/ directory. 

Thanks,
Romanos

**Comment by biocodz** [comment]
Hi,

`fastx` and `other` are boolean options i.e do not take an argument. The output names are preset

**Comment by Roman-Si** [comment]
Ok, thank you!

**Comment by biocodz** [comment]
You can easily change the location for the output using `workdir` option if you need to separate the runs

**Comment by Roman-Si** [comment]
I did it and separated the runs. I wanted to run a FastQC to all the files at once but results get overwritten because of the names. But no problem, i will change the names manually after sortmeRna.
