### ISSUE TITLE
Output compressed FASTQ files

### ISSUE THREAD

**Issue by olivierrue** [biocore/sortmerna#220]
Hello,
It's great that sortmerna now takes compressed FASTQs as input!It would be nice if it could directly generate compressed FASTQs as well, which is very problematic when you want to analyze many samples in parallel. Is this a possible improvement?

**Comment by biocodz** [comment]
This was already requested awhile ago [Issue 175](https://github.com/biocore/sortmerna/issues/175)
Hang on, we plan this for  the next release.

**Comment by biocodz** [comment]
latest version [v.4.3.3](https://github.com/biocore/sortmerna/releases/tag/v4.3.3) does this. If the input files are gzipped, the output is also gzipped.
