### ISSUE TITLE
program stuck while processing gzipped files (v4.2.0)

### ISSUE THREAD

**Issue by zhunshi** [biocore/sortmerna#221]
Hi, 
I am using SortMeRNA version 4.2.0 on samples less than 20M reads. `--threads` was set to 4, but only one is used. It took more than12 hours. Why is this happening?  
Here is the command:  
`sortmerna --ref silva-bac-16s-id90.fasta --ref silva-bac-23s-id98.fasta --ref rfam-5s-database-id98.fasta --fastx --workdir out/test --paired_in --threads 4 --reads test.1.gz --reads test.2.gz --out2 --other out/test/out/test`  

Thanks in advance.  
  
Best,  
Zhun

**Comment by biocodz** [comment]
Could you provide the execution trace like [this one](https://github.com/biocore/sortmerna/wiki/Sample-execution-trace)?

**Comment by zhunshi** [comment]
[stdout.txt](https://github.com/biocore/sortmerna/files/4412972/stdout.txt)

Attached please find the stdout message that has been in this state for more than 2 days.

**Comment by biocodz** [comment]
The program is not running. It's stuck right before indexing starts - no need to wait.
I don't think 'threads' has anything to do with it.
Seems there is a problem with the index directory. What's the output of
```
ls -lrt out/GZMU0048
ls -lrt out/GZMU0048/idx
```

**Comment by zhunshi** [comment]
Here is the list of  work directory :  
```
$ ls -lrt out/GZMU0048  
total 12  
drwxr-xr-x 2 username usergroup 4096 Mar 30 23:48 out  
drwxr-xr-x 2 username usergroup 4096 Mar 30 23:48 idx  
drwxr-xr-x 2 username usergroup 4096 Mar 30 23:51 kvdb
```  
  
```
$ ls -lrt out/GZMU0048/idx
total 551992
-rw-r--r-- 1 username usergroup   1048576 Mar 30 23:50 15734375058464002811.kmer_0.dat
-rw-r--r-- 1 username usergroup 110426764 Mar 30 23:50 15734375058464002811.bursttrie_0.dat
-rw-r--r-- 1 username usergroup 165396916 Mar 30 23:50 15734375058464002811.pos_0.dat
-rw-r--r-- 1 username usergroup    204965 Mar 30 23:50 15734375058464002811.stats
-rw-r--r-- 1 username usergroup   1048576 Mar 30 23:51 17299952793705614139.kmer_0.dat
-rw-r--r-- 1 username usergroup  77025268 Mar 30 23:51 17299952793705614139.bursttrie_0.dat
-rw-r--r-- 1 username usergroup 114228004 Mar 30 23:51 17299952793705614139.pos_0.dat
-rw-r--r-- 1 username usergroup     72005 Mar 30 23:51 17299952793705614139.stats
-rw-r--r-- 1 username usergroup   1048576 Mar 30 23:51 13019673092862722585.kmer_0.dat
-rw-r--r-- 1 username usergroup  39363244 Mar 30 23:51 13019673092862722585.bursttrie_0.dat
-rw-r--r-- 1 username usergroup  53450972 Mar 30 23:51 13019673092862722585.pos_0.dat
-rw-r--r-- 1 username usergroup   1881036 Mar 30 23:51 13019673092862722585.stats
```

**Comment by zhunshi** [comment]
I have run script with default options, but got the same results as previous try.   
When a subset of the sample with 1000 reads was used, the script now works. But why is this ?

**Comment by biocodz** [comment]
Seems the program has a problem with your reads file.
After the indexing is done, the statistics on the reads files is calculated e.g.:
```
[calculate:107] Starting statistics calculation on file: './qc/NG-16660_IS1_lib274081_6037_6_f_qc.fastq.gz'  ...   [inflatez:169] xINFO: infl
[calculate:225] Done statistics on file. Elapsed time: 185.09 sec. all_reads_count= 50207959
```
As you can see It took ~3 min on ~50M reads (done in the main i.e. single thread).
I know sortmerna was successfully used on much larger files (> 100M reads).

**Comment by zhunshi** [comment]
Yes, the program can not process my gzipped files. When using decompressed files, the program works fine.

**Comment by biocodz** [comment]
Could you tell how was your gz file created? Did you use a standard 'gzip'? If yes, what's the output of
```
gzip --version
uname -a
```
Could you create a small 'gz' file with some 100 reads and test it?

**Comment by zhunshi** [comment]
I combined two or more fastq files using `cat` command. 
```
$ cat 1.fq.gz 2.fq.gz > test.fq.gz
```

And the gzip content as follows:  
```
$ gzip -l test.1.fq.gz
         compressed        uncompressed  ratio   uncompressed_name
          476812206           374666011 -27.3%    test.1.fq
```

Maybe these files compressed in the wrong way, and this could be the reason the program was stuck.

**Comment by biocodz** [comment]
I don't think you can combine compressed files like that.
Try instead:
```
gzip -c 1.fq.gz > test.fq.gz
gzip -c 2.fq.gz >> test.fq.gz
```
I would first try processing just a single file, say 1.fq.gz to make sure it works. You can interrupt the processing once it runs OK.

**Comment by zhunshi** [comment]
You are right. Programs can properly handle my original gzipped files.  

My problem is solved. Thanks very much.

**Comment by biocodz** [comment]
Glad to hear! You can close this issue then.

**Comment by ppericard** [comment]
I would just like to point out that it is permitted by the gzip format to concatenate 2 gzip files using cat (https://stackoverflow.com/questions/8005114/fast-concatenation-of-multiple-gzip-files).
Therefore, such a file is a valid gzip file and should be able to be used as input for SortMeRNA.

**Comment by biocodz** [comment]
I'll look into it.
