### ISSUE TITLE
Program always finished with [pop:108] write_queue PoKilledad number: for some samples when using 16s rRNA reference

### ISSUE THREAD

**Issue by phongphak** [biocore/sortmerna#240]
Hi,
I'm using SortMeRNA 4.2 on 7 metagenomic samples. When I run with the following command:

`sortmerna --ref silva-euk-18s-id95.fasta --ref silva-euk-28s-id98.fasta --ref rfam-5s-database-id98.fasta --ref rfam-5.8s-database-id98.fasta --ref silva-arc-16s-id95.fasta --ref silva-bac-16s-id90.fasta --ref silva-arc-23s-id98.fasta --ref silva-bac-23s-id98.fasta --reads forward.fq.gz --reads reverse.fq.gz --workdir outDir --threads 50 -m 80000`

Only 5 samples that can be finished properly, while the others always end with:

Processor proc_35 thread 139827265619712 started
Processor proc_15 thread 139827315975936 started
Processor proc_38 thread 139826904897280 started
Processor proc_41 thread 139826846148352 started
Processor proc_45 thread 139826837755648 started
[write:19] Writer writer_0 thread 139827324368640 started
Processor proc_9 thread 139826980431616 started
Processor proc_49 thread 139827156612864 started
Processor proc_21 thread 139827148220160 started
Processor proc_10 thread 139826854541056 started
Processor proc_25 thread 139827139827456 started
Processor proc_24 thread 139827022395136 started
Processor proc_27 thread 139827114649344 started
Processor proc_26 thread 139826921682688 started
Processor proc_29 thread 139827005609728 started
Processor proc_32 thread 139826879719168 started
Processor proc_31 thread 139827240441600 started
Processor proc_33 thread 139827349546752 started
Processor proc_14 thread 139826829362944 started
Processor proc_13 thread 139827307583232 started
Processor proc_36 thread 139827911563008 started
Processor proc_37 thread 139826795792128 started
Processor proc_16 thread 139826770614016 started
Processor proc_39 thread 139826988824320 started
[run:70] thread: 139826871326464 started
Processor proc_40 thread 139827341154048 started
Processor proc_18 thread 139827123042048 started
Processor proc_44 thread 139827131434752 started
Processor proc_43 thread 139827274012416 started
Processor proc_46 thread 139827282405120 started
Processor proc_47 thread 139827014002432 started
Processor proc_42 thread 139826779006720 started
Processor proc_19 thread 139826972038912 started
Processor proc_22 thread 139827299190528 started
Processor proc_48 thread 139826938468096 started
[pop:108] write_queue PoKilledad number: 453257872

Anyway, if I exclude silva-arc-16s-id95.fasta and silva-bac-16s-id90.fasta from the analysis, all of 7 samples will be done without any problem. So could you guide me how can I fix this issue. Thank you in advance for you help.

Best,
Phongphak

**Comment by biocodz** [comment]
Did you try excluding references other than `silva-arc-16s-id95.fasta` and `silva-bac-16s-id90.fasta`?
Wonder if its the number of references or a particular reference that causes the problem.
What's the size of your reads files i.e.
```
ls -l forward.fq.gz
ls -l reverse.fq.gz
```

**Comment by phongphak** [comment]
> Did you try excluding references other than `silva-arc-16s-id95.fasta` and `silva-bac-16s-id90.fasta`?
> Wonder if its the number of references or a particular reference that causes the problem.
> What's the size of your reads files i.e.
> 
> ```
> ls -l forward.fq.gz
> ls -l reverse.fq.gz
> ```

The first sample are 5997214467 and 6016761339, the second are 5734049439 and 5858132944. Anyway, I didn't try excluding the other.

**Comment by biocodz** [comment]
I would need to see the whole [execution-trace](https://github.com/biocore/sortmerna#execution-trace)

**Comment by phongphak** [comment]
> I would need to see the whole [execution-trace](https://github.com/biocore/sortmerna#execution-trace)

Sorry for late reply. Here's a whole execution-trace.

[log.txt](https://github.com/biocore/sortmerna/files/4607332/log.txt)

Anyway it's not exactly that same as what I posted, because it was redirected and I don't know why it's not the same as standard output, but I can't wait for about 12 hours to capture the whole stdout (screen or tmux do not let me do that as well). So hope this is useful. Please let me know if you need anything else. Thank you.

**Comment by biocodz** [comment]
Thank you for the input. We are looking into it. 
However, this problem can be related to the [issue 231](https://github.com/biocore/sortmerna/issues/231), which arises when a large amount of threads is used, and the reads files are big, in your case 50 threads and ~140M reads. 4.2.0 has a memory leak, and a problem with the reads queue used internally, which becomes a bottleneck that gets worse with the growing number of threads. We are currently working on the fix. In couple days it should be ready for testing.

**Comment by phongphak** [comment]
> Thank you for the input. We are looking into it.
> However, this problem can be related to the [issue 231](https://github.com/biocore/sortmerna/issues/231), which arises when a large amount of threads is used, and the reads files are big, in your case 50 threads and ~140M reads. 4.2.0 has a memory leak, and a problem with the reads queue used internally, which becomes a bottleneck that gets worse with the growing number of threads. We are currently working on the fix. In couple days it should be ready for testing.

Good to hear it. So I have to wait for a new version, right?

**Comment by biocodz** [comment]
Yep. Hopefully it won't take long. Folks uses SMR for ever more demanding applications and on HPCs, which reveal bugs that are not obvious on a single workstation or a laptop.

**Comment by biocodz** [comment]
[v4.3.3](https://github.com/biocore/sortmerna/releases/tag/v4.3.3) works much better with large number of threads
