### ISSUE TITLE
Problem to run indexdb_rna in sortmerna 3.0.2 in computer cluster

### ISSUE THREAD

**Issue by luizdomeignoz** [biocore/sortmerna#241]
I am having problem to index my RNA databases working with sortmerna 3.0.2 in a cluster. 
In this cluster the sortmerna is installed as a singularity image and I need to run it in the interactive mode (bsub -q interactive -Is singularity exec $SORTMERNAIMG sortmerna).

I'm running:  bsub -q interactive -Is singularity exec $SORTMERNAIMG sortmerna indexdb_rna      --ref project/uma_kristen_deangelis/Mn_PROJECT/TEST_Samples_RNA_March_2020/SortMeRNA/silva-bac-16s-id90.fasta,/project/uma_kristen_deangelis/Mn_PROJECT/TEST_Samples_RNA_March_2020/SortMeRNA/index/silva-bac-16s-id90_accession_taxonomy.txt -v

ERROR: [Line 1174: /home/dnanexus/sortmerna/src/sortmerna/options.cpp] 'n' is not one of the options.

I downloaded the RNA databases from the GitHub. But I'm guessing I should access the database the is installed within the sortmerna in the cluster?  Have anyone gone into this problem? 

Thank you very much,
Luiz

**Comment by biocodz** [comment]
Could you provide the [execution-trace](https://github.com/biocore/sortmerna#execution-trace)?

**Comment by luizdomeignoz** [comment]
Sorry it did not produce an execution-trace. This is all I get from running it:

bsub -q interactive -Is singularity exec $SORTMERNAIMG sortmerna indexdb_rna -ref silva-euk-18s-id95.fasta,db_idx_silva-euk-18s-id95  -v --log

Job <5708852> is submitted to queue <interactive>.
<<Waiting for dispatch ...>>
<<Starting on c38b08>>

  ERROR: [Line 1174: /home/dnanexus/sortmerna/src/sortmerna/options.cpp] 'n' is not one of the options.
  usage:   ./sortmerna --ref db.fasta,db.idx --reads file.fa --aligned base_name_output [OPTIONS]:
  OR
  usage:   ./sortmerna --ref db.fasta,db.idx --reads-gz file.fa.gz --aligned base_name_output 

I guess it is because the job didn't run any step. I'm not sure if I'm correctly calling the indexdb_rna function for the ghpcc.

**Comment by biocodz** [comment]
starting v3.0.0 `indexdb_rna` name was changed to `indexdb`. Also it's better to use the latest version 4.2.0.

**Comment by luizdomeignoz** [comment]
Thank you. I corrected the function. Now I got another error message as you can see below. Can I download the index files from somewhere? Sadly I can't use the version 4.2.0 because it is not available in the cluster I have access to. Thank you!

bsub -q interactive -Is singularity exec $SORTMERNAIMG indexdb silva-bac-16s-id90.fasta,silva-bac-16s-db  -v

  ERROR: p is not one of the options

**Comment by biocodz** [comment]
Can you try using full paths i.e. `$DBHOME/silva-bac-16s-id90.fasta,...`?

**Comment by luizdomeignoz** [comment]
I'm running the full path. I pasted here only the code for simplicity. I'm guessing my index file is not correct. What is the index file format input to the indexdb function?

bsub -q interactive -Is singularity exec $SORTMERNAIMG indexdb /project/uma_kristen_deangelis/Mn_PROJECT/TEST_Samples_RNA_March_2020/SortMeRNA/silva-bac-16s-id90.fasta,/project/uma_kristen_deangelis/Mn_PROJECT/TEST_Samples_RNA_March_2020/SortMeRNA/index/silva-bac-16s-db  -v 

ERROR: p is not one of the options

**Comment by biocodz** [comment]
Running `indexdb_rna -h` lists the usage. 
`indexdb_rna --ref ...`. You are missing the flag `--ref`

**Comment by luizdomeignoz** [comment]
Thank you!
