### ISSUE TITLE
silva reference database used by sortmerna nowhere to be found 

### ISSUE THREAD

**Issue by GaioTransposon** [biocore/sortmerna#242]
Hello,

I ran the following: 

for i in `ls /sortmerna_16S/plate_*.gz`; do N=$(basename $i); sortmerna --ref /shared/homes/xxxxx/sortmerna-2.1b/rRNA_databases/silva-bac-16s-id90.fasta --reads $i -fastx -blast 1 --num_alignments 1 --workdir /shared/homes/xxxxx/sortmerna_aligned/$N; done

I have now my 16S tags named like: StaEpi81, Unc00r03, CorEffi4, etc...

I couldn t find the corresponding Silva database with these tags anywhere on the web. Names given by sortmerna using this database not matching any of the current databases such as the following releases: 119,123, 128, 132, 138 + the current one with 14,956 bact and 2,297 archaeal references as by here : https://mothur.org/wiki/silva_reference_files/#release-102

Any suggestions? 

Thank you!

**Comment by ekopylova** [comment]
Hello!

You can find the associated taxonomies [here](https://github.com/biocore/sortmerna/blob/master/data/rRNA_databases/silva_ids_acc_tax.tar.gz) (mentioned in the [README](https://github.com/biocore/sortmerna#taxonomies)). Is this what you are looking for?

Jenya

**Comment by GaioDany** [comment]
Awesome! thank you so much! I so much wish I messaged you earlier!

**Comment by ekopylova** [comment]
No worries. Also, in a future release we will include the full taxonomy strings directly in the sequence file. The databases have been recently tested and we will incorporate these asap.

**Comment by biocodz** [comment]
latest databases are packaged with each release. See e.g. [database.tar.gz in v4.3.3](https://github.com/biocore/sortmerna/releases/download/v4.3.3/database.tar.gz)
