### ISSUE TITLE
other reference databases?  - enhancement

### ISSUE THREAD

**Issue by GaioTransposon** [biocore/sortmerna#243]
Hello !

Is it possible to use any RNA database (besides the ones provided) with sortmerna or is this not recommended? 

Here is why I ask: 

I have been trying to feed the sortmerna output to Tax4Fun, which it _should_ recognize the taxa names as the reference DB used with sortmerna was the silva-bac-16s-id90 one. 

However, it does not get recognise it, and the taxa assigned also look a bit different from other datasets created using silva as a database (from other users). I was wondering if the problem of the taxa not getting recognized by Tax4Fun is due to the "slightly different" silva database used by sortmerna (as I understand it is parsed from the xml by the sortmerna people). 

My goal is to get a rough functional analysis based on taxa (16S). Also happy to hear any alternatives/suggestions

thank you! 
dany

**Comment by ekopylova** [comment]
Yes, it is possible to use other databases. QIIME2 is often used with [Greengenes 16S](https://docs.qiime2.org/2020.2/data-resources/#marker-gene-reference-databases) (v. 13_8).  SILVA release 138 (for [SSU 16S/18S](https://www.arb-silva.de/no_cache/download/archive/current/Exports/) - SILVA_138_SSURef_NR99_tax_silva_trunc.fasta.gz with the taxonomy strings in sequence ID) and release 132 ([LSU 23S/28S](https://www.arb-silva.de/no_cache/download/archive/release_132/Exports/)  - SILVA_132_LSURef_tax_silva_trunc.fasta.gz) are also very good and these versions will be included shortly with SortMeRNA, clustered at various thresholds to provide "super fast", "fast" or "sensitive" classification. Lastly, for 5S/5.8S we will be using the seed databases from [RFAM](http://rfam.xfam.org/family/5_8S_rRNA#tabview=tab2), without any modification.

Likely there are others, however I have the most experience with those listed above.
