### ISSUE TITLE
Always get a "Segmentation fault (core dumped)" error

### ISSUE THREAD

**Issue by RayanaFeltrin** [biocore/sortmerna#245]
Hey there!
Recently I had some problems using SortMeRNA v2.1b, since one of my fastq files got corrupted. Then I tried v3.0.4, using the following command:

`/home/curupi/tools/bin/sortmerna --ref /home/curupi/tools/sortmerna-3.0.4/rRNA_databases/silva-bac-16s-id90.fasta,/home/curupi/tools/sortmerna-3.0.4/index/silva-bac-16s-db:/home/curupi/tools/sortmerna-3.0.4/rRNA_databases/silva-bac-23s-id98.fasta,/home/curupi/tools/sortmerna-3.0.4/index/silva-bac-23s-db:/home/curupi/tools/sortmerna-3.0.4/rRNA_databases/silva-arc-16s-id95.fasta,/home/curupi/tools/sortmerna-3.0.4/index/silva-arc-16s-db:/home/curupi/tools/sortmerna-3.0.4/rRNA_databases/silva-arc-23s-id98.fasta,/home/curupi/tools/sortmerna-3.0.4/index/silva-arc-23s-db:/home/curupi/tools/sortmerna-3.0.4/rRNA_databases/silva-euk-18s-id95.fasta,/home/curupi/tools/sortmerna-3.0.4/index/silva-euk-18s-db:/home/curupi/tools/sortmerna-3.0.4/rRNA_databases/silva-euk-28s-id98.fasta,/home/curupi/tools/sortmerna-3.0.4/index/silva-euk-28s:/home/curupi/tools/sortmerna-3.0.4/rRNA_databases/rfam-5s-database-id98.fasta,/home/curupi/tools/sortmerna-3.0.4/index/rfam-5s-db:/home/curupi/tools/sortmerna-3.0.4/rRNA_databases/rfam-5.8s-database-id98.fasta,/home/curupi/tools/sortmerna-3.0.4/index/rfam-5.8s-db --reads /home/curupi/data/pulchella/fastq/trim/workdir/Adpul2_S11_paired.trim.fastq --sam --num_alignments 1 --fastx --aligned /home/curupi/data/pulchella/fastq/trim/workdir/Adpul2_S11_paired.trim.fastq_rRNA --other /home/curupi/data/pulchella/fastq/trim/workdir/Adpul2_S11_paired.fastq_non_rRNA --paired_in -a 2 --log -v`

However, I got a "Segmentation fault (core dumped)" error. Therefore, I also tried v3.0.0, with the following command...

`/home/curupi/tools/sortmerna-3.0.0/sortmerna --ref /home/curupi/tools/sortmerna-3.0.4/rRNA_databases/silva-bac-16s-id90.fasta,/home/curupi/tools/sortmerna-3.0.4/index/silva-bac-16s-db:/home/curupi/tools/sortmerna-3.0.4/rRNA_databases/silva-bac-23s-id98.fasta,/home/curupi/tools/sortmerna-3.0.4/index/silva-bac-23s-db:/home/curupi/tools/sortmerna-3.0.4/rRNA_databases/silva-arc-16s-id95.fasta,/home/curupi/tools/sortmerna-3.0.4/index/silva-arc-16s-db:/home/curupi/tools/sortmerna-3.0.4/rRNA_databases/silva-arc-23s-id98.fasta,/home/curupi/tools/sortmerna-3.0.4/index/silva-arc-23s-db:/home/curupi/tools/sortmerna-3.0.4/rRNA_databases/silva-euk-18s-id95.fasta,/home/curupi/tools/sortmerna-3.0.4/index/silva-euk-18s-db:/home/curupi/tools/sortmerna-3.0.4/rRNA_databases/silva-euk-28s-id98.fasta,/home/curupi/tools/sortmerna-3.0.4/index/silva-euk-28s:/home/curupi/tools/sortmerna-3.0.4/rRNA_databases/rfam-5s-database-id98.fasta,/home/curupi/tools/sortmerna-3.0.4/index/rfam-5s-db:/home/curupi/tools/sortmerna-3.0.4/rRNA_databases/rfam-5.8s-database-id98.fasta,/home/curupi/tools/sortmerna-3.0.4/index/rfam-5.8s-db --reads Adpul2_S11_paired.trim.fastq --sam --num_alignments 1 --fastx --aligned Adpul2_S11_paired.trim.fastq_rRNA --other Adpul2_S11_paired.fastq_non_rRNA --paired_in -a 2 --log -v`

... and also got the same "Segmentation fault (core dumped)" error! Then I tried the last version, 4.2.0:

`/home/curupi/tools/bin/sortmerna -ref /home/curupi/tools/sortmerna-2.1b/rRNA_databases/silva-bac-16s-id90.fasta -ref /home/curupi/tools/sortmerna-2.1b/rRNA_databases/silva-bac-23s-id98.fasta -ref /home/curupi/tools/sortmerna-2.1b/rRNA_databases/silva-arc-16s-id95.fasta -ref /home/curupi/tools/sortmerna-2.1b/rRNA_databases/silva-arc-23s-id98.fasta -ref /home/curupi/tools/sortmerna-2.1b/rRNA_databases/silva-euk-18s-id95.fasta -ref /home/curupi/tools/sortmerna-2.1b/rRNA_databases/silva-euk-28s-id98.fasta -ref //home/curupi/tools/sortmerna-2.1b/rRNA_databases/rfam-5s-database-id98.fasta -ref /home/curupi/tools/sortmerna-2.1b/rRNA_databases/rfam-5.8s-database-id98.fasta --reads Adpul2_S11_paired.trim.fastq --sam --num_alignments 1  --fastx --aligned Adpul2_S11_paired.trim.fastq_rRNA --other Adpul2_S11_paired.fastq_non_rRNA --threads 2 -v --paired_in`

... but still got the same error! May you guys please help me?
Thank you in advance!

**Comment by biocodz** [comment]
if copy-pasting, please, ensure no `lost whitespace`, and no `added new line` characters corrupt your command line.

**Comment by RayanaFeltrin** [comment]
Thanks for your reply!
Actually there were some extra spaces in my command line when I was running v4.2.0, but although I have corrected this issue and tried to run it again, I still didn't get to run the software appropriately... and got the following error:

_[ReadsQueue:57] [read_queue] created with [1] Pushers
[ReadsQueue:57] [write_queue] created with [2] Pushers
terminate called after throwing an instance of 'Sls::error'
[Refstats:32] Index Statistics calculation Start ...Aborted (core dumped)_ 

Anyway, I also tried to run v3.0.4 again after double-checking my command.. then it seemed that the software did run, but in a very fast way, resulting in this message:

_[Refstats:32] Index Statistics calculation Start ... Done. Time elapsed: 6.50 sec
[generateReports:872] Done Reports generation
[~ReadsQueue:69] Destructor called on write_queue  recs.size= 0 pushed: 0  popped: 0
[~ReadsQueue:69] Destructor called on read_queue  recs.size= 0 pushed: 0  popped: 0
Thread  140135664715520 job done
Thread  140135656322816 job done
Output.closefiles called. Flushed and closed_

Then, I got a look at the .log file, and as you can see, no percentage was generated:

_/home/curupi/tools/sortmerna-3.0.4/rRNA_databases/silva-bac-16s-id90.fasta          0.00
    /home/curupi/tools/sortmerna-3.0.4/rRNA_databases/silva-bac-23s-id98.fasta          0.00
    /home/curupi/tools/sortmerna-3.0.4/rRNA_databases/silva-arc-16s-id95.fasta          0.00
    /home/curupi/tools/sortmerna-3.0.4/rRNA_databases/silva-arc-23s-id98.fasta          0.00
    /home/curupi/tools/sortmerna-3.0.4/rRNA_databases/silva-euk-18s-id95.fasta          0.00
    /home/curupi/tools/sortmerna-3.0.4/rRNA_databases/silva-euk-28s-id98.fasta          0.00
    /home/curupi/tools/sortmerna-3.0.4/rRNA_databases/rfam-5s-database-id98.fasta               0.00
    /home/curupi/tools/sortmerna-3.0.4/rRNA_databases/rfam-5.8s-database-id98.fasta             0.00_

What can I do to solve this?
Thank you in advance!

**Comment by biocodz** [comment]
have you generated the indices i.e. `indexdb --ref ...`?

**Comment by RayanaFeltrin** [comment]
Yes, I have! In the same directory of the file "indexdb_rna", I run the following command:

`indexdb_rna --ref /home/curupi/tools/sortmerna-3.0.4/rRNA_databases/silva-bac-16s-id90.fasta,/home/curupi/tools/sortmerna-3.0.4/index/silva-bac-16s-db:/home/curupi/tools/sortmerna-3.0.4/rRNA_databases/silva-bac-23s-id98.fasta,/home/curupi/tools/sortmerna-3.0.4/index/silva-bac-23s-db:/home/curupi/tools/sortmerna-3.0.4/rRNA_databases/silva-arc-16s-id95.fasta,/home/curupi/tools/sortmerna-3.0.4/index/silva-arc-16s-db:/home/curupi/tools/sortmerna-3.0.4/rRNA_databases/silva-arc-23s-id98.fasta,/home/curupi/tools/sortmerna-3.0.4/index/silva-arc-23s-db:/home/curupi/tools/sortmerna-3.0.4/rRNA_databases/silva-euk-18s-id95.fasta,/home/curupi/tools/sortmerna-3.0.4/index/silva-euk-18s-db:/home/curupi/tools/sortmerna-3.0.4/rRNA_databases/silva-euk-28s-id98.fasta,/home/curupi/tools/sortmerna-3.0.4/index/silva-euk-28s:/home/curupi/tools/sortmerna-3.0.4/rRNA_databases/rfam-5s-database-id98.fasta,/home/curupi/tools/sortmerna-3.0.4/index/rfam-5s-db:/home/curupi/tools/sortmerna-3.0.4/rRNA_databases/rfam-5.8s-database-id98.fasta,/home/curupi/tools/sortmerna-3.0.4/index/rfam-5.8s-db`

**Comment by biocodz** [comment]
Considering you have access to v4.2.0, I would suggest to use it.
Could you try running the simplified command like:
`sortmerna -ref /home/curupi/tools/sortmerna-2.1b/rRNA_databases/silva-bac-16s-id90.fasta -reads Adpul2_S11_paired.trim.fastq -fastx  -threads 2 -v -paired_in`
and provide the whole trace the command outputs?

**Comment by RayanaFeltrin** [comment]
Right.. I ran the mentioned command and the output returned the parameter options.. here is a part of it:

 _[ADVANCED OPTIONS] (see SortMeRNA user manual for more details): 
    --passes           INT,INT,INT     three intervals at which to place the seed on the read         L,L/2,3
                                         (L is the seed length set in ./indexdb_rna)
    --edges            INT             number (or percent if INT followed by % sign) of               4
                                         nucleotides to add to each edge of the read
                                         prior to SW local alignment 
    --num_seeds        INT             number of seeds matched before searching                       2
                                         for candidate LIS 
    --full_search      BOOL            search for all 0-error and 1-error seed                        off
                                         matches in the index rather than stopping
                                         after finding a 0-error match (<1% gain in
                                         sensitivity with up four-fold decrease in speed)
    --pid              BOOL            add pid to output file names                                   off_


   _[HELP]:
     -h                BOOL            help
     --version         BOOL            SortMeRNA version number_

**Comment by biocodz** [comment]
are you sure using 4.2.0?

**Comment by RayanaFeltrin** [comment]
Well, when I ran this command, I was in the bin directory that came out when I had ran `bash sortmerna-4.2.0-Linux.sh --skip-license`. However, when I run `sortmerna --version`, it displays _SortMeRNA version 2.1, 01/02/2016_. I have already put the bin directory (/home/curupi/tools/bin/sortmerna) in ~/.bashrc, but the version does not change!

**Comment by biocodz** [comment]
You can do the following to keep different versions of SMR side-by-side:
Create a directory of your choosing e.g. /home/curupi/sortmerna/4.2.0/
```
mkdir -p /home/curupi/sortmerna/4.2.0
bash sortmerna-4.2.0-Linux.sh --skip-license --prefix=/home/curupi/sortmerna/4.2.0
ls -l /home/curupi/sortmerna/4.2.0/bin/sortmerna
/home/curupi/sortmerna/4.2.0/bin/sortmerna --version
```
Now run your test
```
/home/curupi/sortmerna/4.2.0/bin/sortmerna -ref ...
```

**Comment by RayanaFeltrin** [comment]
Yay, now it ran!!!
It's normal to end with...

_[generateReports:1120] === Done Reports generation ===_

_[~ReadsQueue:68] Destructor called on write_queue  recs.size= 0 pushed: 0  popped: 0
[~ReadsQueue:68] Destructor called on read_queue  recs.size= 0 pushed: 58121500  popped: 58121500
Thread  140151334356736 job done
Thread  140151242036992 job done
[closefiles:885] Flushed and closed_

... isn't it?

**Comment by biocodz** [comment]
Yup, that's good. Now you can try adding another reference to your command line, and play with other options.

**Comment by RayanaFeltrin** [comment]
Great!!! Thank you so much for the help!
