### ISSUE TITLE
Missing db.idx file

### ISSUE THREAD

**Issue by marco91sol** [biocore/sortmerna#246]
Dear all, 

I've used the following command for creating an index file of silva-bac-16s-id90.fasta,

**indexdb_rna --ref ./rRNA_databases/silva-bac-16s-id90.fasta,./index/silva-bac-16s-db -v**

Then, Id like to run sortmerna command and to set --ref with the reference file, but I have no db.idx file. How I should run it?

I tried to put in the --ref the normal fasta file and I obviously obtain the following output:

FASTA reference file name /path/to/silva-bac-16s-id90.fasta must be followed  by an index
 name.

**Comment by biocodz** [comment]
you should pass to 'sortmerna' exactly the same '--ref' as used with 'indexdb_rna' i.e.
```
sortmerna --ref ./rRNA_databases/silva-bac-16s-id90.fasta,./index/silva-bac-16s-db ...
```
