### ISSUE TITLE
separate paired-end reads output into 'paired aligned' and 'singleton aligned'

### ISSUE THREAD

**Issue by jlli6t** [biocore/sortmerna#247]
Hi,

With version 4.2.0, if set `--fastx` and `--other` True,  but `--paired_in` and `--paired_out` False, with one pair of reads that just one of them aligned to db, what will SMR output?

I checked the document, seems this kind of situation is not listed in Table 3?

Thanks

**Comment by ekopylova** [comment]
By default, sequences not matching to the rRNA databases are output to ```--other```. Thus, if one paired read matches and other doesn't, the matched reads goes into the aligned output and the other read into the ```--other``` file.

**Comment by jlli6t** [comment]
Thank u, would you mind seperate these hits into different output files as well in the future?

**Comment by ekopylova** [comment]
Hello @jlli6t, if you specify ```--paired_in```, then both reads will be output to the aligned file, even if one read did not align. If you specify ```--paired_out```, both reads will be output to the ```--other``` file, even if one read did align. If you don't specify either of ```--paired_in``` or ```--paired_out```, aligned reads will go to the alignment file and unaligned reads to the ```--other``` file. What additional option are you looking for?

**Comment by jlli6t** [comment]
Sorry I did't make it clear enough. U added `--out2`, no matter `--paired_in` or `--paired_out`, or without both, there will be a fwd and rev output separately.  If both `--paired_in` and `--paired_out` are set to False, then the fwd and rev output sequences they are actually not exactly pair each other.  while user set both `--paired_in` and `--paired_out` as False, and a pair of read just one matched db and the other not, I am wondering if you will separate this matched read into aligned output and the other one goes into another file other than fwd or rev output in the future , in this case, the fwd and rev will pair each other.

**Comment by biocodz** [comment]
1. If (`paired_in` OR `paired_out`) + `out2` => 2 files are output (FWD and REV), and both files will have Equal number of reads (some reads can be non-aligned).
2. If two `reads` + No (`paired_in` OR `paired_out`)  + `out2` => 2 files are output, which may have different number of reads (only aligned)
3. if one interleaved `reads` + `paired` + `out2` => 2 files are output as in case 2

I'm not sure if you are asking for yet another option

**Comment by jlli6t** [comment]
Yes, I am wondering, while input reads are pair-end reads, set `out2` + No  `paired_in` OR `paired_out`, would you mind seperate just-one-end-read-aligned reads into to seperate files to make sure reads in aligned_fwd.fastq and aligned_rev.fastq still pair each other, and the just-one-end-read aligned reads go to other files like single-end reads.

**Comment by biocodz** [comment]
If I understand correctly, you would like to separate reads that have '`both FWD And REV aligned`' from those that have only '`One FWD Or REV aligned`'.

The '`both FWD And REV`' could go into say '`fwd_matched.fq`' and '`rev_matched.fq`', and the '`One FWD Or REV`' into '`fwd_unmatched.fq`' and '`rev_unmatched.fq`'.

This could be done. We can mark this thread as a feature request. 
This would happen after a couple major bugs we currently have are fixed.

**Comment by ppericard** [comment]
@biocodz , this would be a bit more complicated.
In SMR v4 if you have paired-end data you would input it in the 2 files format (reads_1.fq & reads_2.fq). When using this format, you have to guarantee that all reads are paired (which means the exact same number of reads in both files).
What SMR could do, which would greatly simplify the user life and post-processing pipeline, is outputting reads using the same format.
Which means that if neither `--paired_in` nor `--paired_out` are set, you would need to output at most 8 different fastx files:

`aligned_paired_1.fastq` & `aligned_paired_2.fastq` (these files contain all the paired-reads that were both aligned against the database; the files are paired and contain exactly the same number of reads)
`aligned_unpaired_1.fastq` & `aligned_unpaired_2.fastq` (those would contain the singleton reads from either the first or the second input file, that aligned against the DB)

And the same thing for reads that did not align:
`other_paired_1.fastq` & `other_paired_2.fastq` (these files contain all the paired-reads that did not align against the database; the files are paired and contain the same number of reads)
`other_unpaired_1.fastq` & `other_unpaired_2.fastq` (those would contain the singleton reads from either the first or the second input file, that did not align against the DB)

@jlli6t , can you confirm that this would resolve your problem ?

**Comment by biocodz** [comment]
@ppericard  Yep, that details pretty much exactly what I meant to say.

**Comment by ppericard** [comment]
About the naming of files, you can call singleton reads files `unpaired` or `singletons` but not `single` because it could be confused with single-read sequencing (a.k.a not paired-end)

**Comment by jlli6t** [comment]
@biocodz @ppericard Yep, that's exactly what I am wondering. 
And hmmm I have to say yes, there will be 8 output fastq files when input reads are PE and without `--paired_in` or `--paired_out` set. Thank u very much for all of your work done

**Comment by vragh** [comment]
What's the best way to emulate the 8-file output setup mentioned by @ppericard with the current version of SMR in the meantime? In my specific case, I only want the `other_` portion of those 8 files. Would specifying `--paired_out` & `--out2` suffice?

**Comment by biocodz** [comment]
The salt of this thread is the `absolute` separation of non-aligned and aligned reads. 

Currently `no` version of sortmerna can guarantee such separation if either `paired_in/out` are specified, because they order the logic to keep the paired reads `together`. If neither `paired_in/out` are used then the `absolute` separation is guaranteed but the reads won't be treated as paired.

If you use `paired_in/out` and want to figure out what reads are non-aligned, you would have to run the process second time using `other` `without` `paired_in/out`, and then compare the produced files by whatever means are available to you.

**Comment by biocodz** [comment]
[v4.3.3](https://github.com/biocore/sortmerna/releases/tag/v4.3.3) does this. Relevant options `-out2` and `-sout`. See e.g. [test 41](https://github.com/biocore/sortmerna/blob/v4.3.3/scripts/test.jinja.yaml#L2607) which generates 8 files:
```
aligned_paired_fwd.fq.gz
aligned_paired_rev.fq.gz
aligned_singleton_fwd.fq.gz
aligned_singleton_rev.fq.gz
other_paired_fwd.fq.gz
other_paired_rev.fq.gz
other_singleton_fwd.fq.gz
other_singleton_rev.fq.gz
```
