### ISSUE TITLE
non rRNA reads output not generated?

### ISSUE THREAD

**Issue by paulsalachan** [biocore/sortmerna#251]
Hi,

I am using the SMR v4.2, but I am a bit confused with one of the options. In table 2 you state: 

"A_0 | Neither of the two paired reads is aligned | No output is generated"

Isn't (at least one of ) the point of SMR to generate an output if the reads don't align to rRNA? By not generating an output, am I loosing all the non rRNA reads?
I see that there is an option `--other` which outputs the non rRNA reads to a separate file, but from my understanding of reading the github wiki (https://github.com/biocore/sortmerna/wiki/2.-User-manual-(todo)#filtering-paired-end-reads), the `--other` option is only for the "A_1" scenario, when "A single out of a pair of reads is aligned".

Could you clarify whether the `--other` option also outputs the non rRNA reads in the "A_O" scenario?

Thanks,
Paul

**Comment by biocodz** [comment]
`-other` option is exactly for outputting non-aligned reads into a separate file. If used on paired reads, and with the option `-paired_out`, then 'non-aligned' reads file may actually contain some aligned reads because `-paired_out` means both paired reads are considered non-aligned when even a single of them is non-aligned.

**Comment by paulsalachan** [comment]
Thanks for the reply. So the description for the "A_0" scenario, that "No output is generated" must be wrong and the `--other` option is for both "A_0" and "A_1" scenarios?

**Comment by biocodz** [comment]
If `-other` is specified, the non-aligned output is produced no matter the scenario.

**Comment by paulsalachan** [comment]
Great, thanks!
