### ISSUE TITLE
Installation 4.2.0

### ISSUE THREAD

**Issue by madelineclaire12** [biocore/sortmerna#252]
I am having some difficulty installing and running Sortmerna version 4.2.0. When I run the installation commands I get a directory titled "sortmerna-4.2.0-Linux" that contains only one folder titled "bin" that contains the "sortmerna" program but no data folder for the references. So to run the sortmerna --ref REF_PATH --reads READS_PATH command, I am not sure where the REF_PATH is. It looks like the data directory didn't get installed. 

I'm not sure if this is a problem with installation or on my end. 

Thanks for the help!

**Comment by biocodz** [comment]
You would need to download [sources zip](https://github.com/biocore/sortmerna/archive/v4.2.0.zip) or [tar.gz](https://github.com/biocore/sortmerna/archive/v4.2.0.tar.gz). The reference data is in `sortmerna-4.2.0/data/` folder

**Comment by madelineclaire12** [comment]
Thanks, works perfectly now!
