### ISSUE TITLE
ERROR: no output format has been chosen (fastx/sam/blast/otu_map/log).

### ISSUE THREAD

**Issue by EdiMedi123** [biocore/sortmerna#253]
Hey!

I am using the following line:

`./sortmerna --ref /home/bilbo/BioinfoTools/sortmerna-2.1b/rRNA_databases/silva-bac-16s-id90.fasta,/home/bilbo/BioinfoTools/sortmerna-2.1b/index/silva-bac-16s-db --reads /home/bilbo/Janek_Edi_MG_MT/output_reverse_paired_edina_1_MT_S3.fasta --aligned /home/bilbo/BioinfoTools/sortmerna-2.1b/Output_Test`

And I get the following error message:

ERROR: no output format has been chosen (fastx/sam/blast/otu_map/log).

I tried to use different inputs, I tried to attach a file format to the output file, and many more things but i have no idea what the problem is.

If anybody has an idea what my problem is I would be really thankful :)

Thanks,
Edina

**Comment by biocodz** [comment]
Is your command generated by a script? Is it a single well-formatted line without extraneous characters?

**Comment by EdiMedi123** [comment]
It is not a script, it is a single line.
I had the feeling that though the official format is 

`./sortmerna --ref db.fasta,db.idx --reads file.fa --aligned base_name_output [OPTIONS]`

and only --ref & --reads & --aligned are mandatory that I need to add another ouput option like that:

`./sortmerna --ref /home/bilbo/BioinfoTools/sortmerna-2.1b/rRNA_databases/silva-bac-16s-id90.fasta,/home/bilbo/BioinfoTools/sortmerna-2.1b/index/silva-bac-16s-db --reads /home/bilbo/Janek_Edi_MG_MT/output_forward_paired_edina_1_MT_S3_TEST.fastq.gz --aligned /home/bilbo/BioinfoTools/sortmerna-2.1b/Output_Test.fastq.gz --fastx /home/bilbo/Janek_Edi_MG_MT/output_reverse_paired_edina_1_MT_S3`

(**--fastx /home/bilbo/Janek_Edi_MG_MT/output_reverse_paired_edina_1_MT_S3** is what I am talking about)

And now I dont get the Error message anymore but only the "manual" :

![grafik](https://user-images.githubusercontent.com/68325424/87540912-b3184280-c6a0-11ea-9dd8-b08afadca785.png)

**Comment by biocodz** [comment]
If I understand correctly when using `--fastx` the program works OK - correct?
Indeed, only 3 parameters are mandatory, and if it doesn't work with just the 3 - it's a bug.
Please, try the latest version if possible.

**Comment by ppericard** [comment]
@biocodz, if a user uses only the 3 mandatory parameters and no other (no --fastx, --other, --sam, --blast, ...) then what is the output of sortmerna ?
Doesn't the user need to indicate at least one output format ?

**Comment by EdiMedi123** [comment]
If I only use 3 parameters I get:
ERROR: no output format has been chosen (fastx/sam/blast/otu_map/log). 

And if I use more parameters nothing happens so no error is being shown but the manual is being shown.

I am using sortmerna-2.1b - I thought this was the latest version?

**Comment by ppericard** [comment]
@EdiMedi123 , with Sortmerna 2.1b you need to indicate at least one output format. These parameters are flag, they dont expect a filename after. So this should work:
`./sortmerna --ref /home/bilbo/BioinfoTools/sortmerna-2.1b/rRNA_databases/silva-bac-16s-id90.fasta,/home/bilbo/BioinfoTools/sortmerna-2.1b/index/silva-bac-16s-db --reads /home/bilbo/Janek_Edi_MG_MT/output_forward_paired_edina_1_MT_S3_TEST.fastq.gz --aligned /home/bilbo/BioinfoTools/sortmerna-2.1b/Output_Test.fastq.gz --fastx`

**Comment by biocodz** [comment]
@EdiMedi123 [the list of releases](https://github.com/biocore/sortmerna/releases)

**Comment by EdiMedi123** [comment]
Perfect this works thank you so much!


I do have one last question: Can SortmeRNA use .gz or do I need to unpack it? Now I used a fasta file as input and that worked.
