### ISSUE TITLE
SortMeRNA writing to output file is slow

### ISSUE THREAD

**Issue by Troshchk** [biocore/sortmerna#256]
The SortMeRNA itself is finished quite fast ( I used a chunk to test it out, so it took around 20 mins), but writing to the output (aligned and other reads) take about 2 hours. Is this behavior expected?

My command:
``` sortmerna -ref /rRNA_db/rfam-5.8s-database-id98.fasta  -ref /rRNA_db/rfam-5s-database-id98.fasta -ref /rRNA_db/silva-euk-18s-id95.fasta -ref /rRNA_db/silva-euk-28s-id98.fasta  --fastx --num_alignments 1  --workdir ${FOLDER}/${name}_sort --reads $i --aligned "${i}_aligned" --other  "${i}_norRNA" ```

**Comment by biocodz** [comment]
Could  you please provide the [execution-trace](https://github.com/biocore/sortmerna#execution-trace).
What's the size of your output files i.e. `ls -l aligned.fq other.fq`?
