### ISSUE TITLE
SortMeRna to use with metagenomic data

### ISSUE THREAD

**Issue by FifichaM** [biocore/sortmerna#257]
Hi everybody im new in bioinformatics im learning by myself , and Im analysing metagenome set (microbiota data from children) Im following the Asaim workflow, and I was wondering if SortMeRna works with metagenomic data ( not metatranscriptomic) what good will it do for my research ? ty

**Comment by ekopylova** [comment]
Hi @FifichaM, SortMeRNA works with metagenomics data as well. It has been tested thoroughly with Illumina / short read data. Is your main purpose to filter rRNA sequences?

Jenya

**Comment by FifichaM** [comment]
no, SortMeRna is included in the workflow of Asaim and I dont understand why I need to filter rRna sequences in metagenomics data

**Comment by ekopylova** [comment]
Hi @FifichaM ,
For shotgun metagenomics, you can use SortMeRNA to rapidly identify 16S sequences and feed the alignments to a tool such as MATAM, to provide taxonomy identification with high resolution. This will not require full metagenome assembly of all your data. I encourage you to read their paper for further details:

MATAM: reconstruction of phylogenetic marker genes from short sequencing reads in metagenomes, Pierre Pericard, Yoann Dufresne, Loïc Couderc, Samuel Blanquart and Hélène Touzet, 2018, Bioinformatics

https://academic.oup.com/bioinformatics/article/34/4/585/4457361

Jenya
