### ISSUE TITLE
-out 2 reads are not paired??

### ISSUE THREAD

**Issue by terancewong** [biocore/sortmerna#259]
Hi there,
I have an issue on -out 2 reads. After doing me sortmerna, I would like to have reads separated into forward and reverse files, but after I typed -out 2, and i looked into the details of the automatically-produced fwd and rev files, they are not paired. In other words, both forward and reverse files contain /2 reads only (instead of forward reads being /1, and reverse reads being /2). May I know how I could solve this issue? I want mRNA instead of rRNA, so my command is seen as below.
"sortmerna -ref /home/xuelei/tools/sortmerna-4.2.0-Linux/bin/rfam-5.8s-database-id98.fasta \ -ref /home/xuelei/tools/sortmerna-4.2.0-Linux/bin/rfam-5s-database-id98.fasta \ -ref /home/xuelei/tools/sortmerna-4.2.0-Linux/bin/silva-arc-16s-id95.fasta \ -ref /home/xuelei/tools/sortmerna-4.2.0-Linux/bin/silva-arc-23s-id98.fasta \ -ref /home/xuelei/tools/sortmerna-4.2.0-Linux/bin/silva-bac-16s-id90.fasta \ -ref /home/xuelei/tools/sortmerna-4.2.0-Linux/bin/silva-bac-23s-id98.fasta \ -ref /home/xuelei/tools/sortmerna-4.2.0-Linux/bin/silva-euk-18s-id95.fasta \ -ref /home/xuelei/tools/sortmerna-4.2.0-Linux/bin/silva-euk-28s-id98.fasta \ -reads /home/xuelei/20200109_novogene/stenopus_2/cutadapt/unclassified/pairfq/B_NC_forward.fq -reads /home/xuelei/20200109_novogene/stenopus_2/cutadapt/unclassified/pairfq/B_NC_reverse.fq --aligned B_NC_rRNA --other B_NC_clean -v --paired_in --fastx -out2

I am looking forward to your advice, thanks!

Yours Sincerely,
Terry

**Comment by biocodz** [comment]
This looks like the same question asked in the [issue 209](https://github.com/biocore/sortmerna/issues/209). Please, check the link for the answer. 

In the future, please, delete a message put into a wrong thread prior duplicating it.
