### ISSUE TITLE
could i run sortmerna with multiple paired-end sample?

### ISSUE THREAD

**Issue by leehs96** [biocore/sortmerna#261]
when i run this tool with bunch of samples
like "sample1_1.fq, sample1_2.fq, sample2_1.fq, sample2_2.fq.......sample9_1.fq, sample9_2.fq"

i am using shell script to execute with just one command

like 
------------------------------------------------------------------------------------------------------
#! bin/bash

sortmerna --ref /mnt/e/hslee/rRNA/sortmerna-4.2.0/data/rRNA_databases/silva-euk-28s-id98.fasta --ref /mnt/e/hslee/rRNA/sortmerna-4.2.0/data/rRNA_databases/silva-euk-18s-id95.fasta --ref /mnt/e/hslee/rRNA/sortmerna-4.2.0/data/rRNA_databases/rfam-5.8s-database-id98.fasta --reads /mnt/e/hslee/pink1/fastq/trimm/sample1_1.fq  --reads /mnt/e/hslee/pink1/fastq/trimm/sample1_2.fq  --fastx --paird-in -threads 8

sortmerna --ref /mnt/e/hslee/rRNA/sortmerna-4.2.0/data/rRNA_databases/silva-euk-28s-id98.fasta --ref /mnt/e/hslee/rRNA/sortmerna-4.2.0/data/rRNA_databases/silva-euk-18s-id95.fasta --ref /mnt/e/hslee/rRNA/sortmerna-4.2.0/data/rRNA_databases/rfam-5.8s-database-id98.fasta --reads /mnt/e/hslee/pink1/fastq/trimm/sample2_1.fq  --reads /mnt/e/hslee/pink1/fastq/trimm/sample2_2.fq --fastx --paird-in -threads 8

sortmerna --ref /mnt/e/hslee/rRNA/sortmerna-4.2.0/data/rRNA_databases/silva-euk-28s-id98.fasta --ref /mnt/e/hslee/rRNA/sortmerna-4.2.0/data/rRNA_databases/silva-euk-18s-id95.fasta --ref /mnt/e/hslee/rRNA/sortmerna-4.2.0/data/rRNA_databases/rfam-5.8s-database-id98.fasta --reads /mnt/e/hslee/pink1/fastq/trimm/sample3_1.fq  --reads /mnt/e/hslee/pink1/fastq/trimm/sample3_2.fq  --fastx --paird-in -threads 8

------------------------------------------------------------------------------------------------------
it works well for first operation (sample1_1, sample2_2)
but the next time
it throws WARNING message and whole process is killed

WARNING: [validate_kvdbdir:1274] Path: "/home/hslee/sortmerna/run/kvdb" exists with the following content:                                       
"000003.log"                                                                                                                                     "CURRENT"                                                                                                                                        "IDENTITY"                                                                                                                                       "LOCK"                                                                                                                                           "LOG"                                                                                                                                            "MANIFEST-000001"                                                                                                                                "OPTIONS-000005" 

is there any method that processing bunch of samples with just one execute???

thanks

**Comment by biocodz** [comment]
If you are only using a single machine then only a single sample at a time can be processed. Just delete 'kvdb' directory prior running a new sample.

I you are on an HPC cluster, you could launch a few parallel jobs on a few compute instances similar to what's described here [issue 216](https://github.com/biocore/sortmerna/issues/216).

**Comment by leehs96** [comment]
OK. 
Thank you for answering
