### ISSUE TITLE
question about reference database

### ISSUE THREAD

**Issue by veramazzara** [biocore/sortmerna#262]
Hi there,
I'm processing human cell line RNAseq data and I want to filter raw reads from rRNA sequences using the SortMeRNA tool but I have some questions:

is it preferable to create a custom human rRNA database or is it possible to use the reference fasta files already embedded in the package?

thanks 

Vera

**Comment by ekopylova** [comment]
Hello @veramazzara ,

The default database includes 18S/28S sequences and should be sufficient to remove human rRNA.

We included the new database is in the latest release (with over 100 ```Homo sapiens``` rRNA clusters). Look [here](https://github.com/biocore/sortmerna/releases/tag/v4.2.0)  for ```database.tar.gz``` download link under Assets.
