### ISSUE TITLE
Worked for some files, but halted at one. Log file seems to show no progressing.

### ISSUE THREAD

**Issue by ryandikdan** [biocore/sortmerna#263]
I made a script which runs sortmerna to filter out rRNA reads, which worked well for the first 3 files but now it appears stuck. It did not generate the empty output files yet, but it did generate the work directory along with the LOG in kvdb which is shown below

```
** Compaction Stats [default] **
Level    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Sum      0/0    0.00 KB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0
 Int      0/0    0.00 KB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0

** Compaction Stats [default] **
Priority    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Uptime(secs): 52800.2 total, 600.0 interval
Flush(GB): cumulative 0.000, interval 0.000
AddFile(GB): cumulative 0.000, interval 0.000
AddFile(Total Files): cumulative 0, interval 0
AddFile(L0 Files): cumulative 0, interval 0
AddFile(Keys): cumulative 0, interval 0
Cumulative compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Interval compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Stalls(count): 0 level0_slowdown, 0 level0_slowdown_with_compaction, 0 level0_numfiles, 0 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 0 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 0 total count

** File Read Latency Histogram By Level [default] **

** Compaction Stats [default] **
Level    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Sum      0/0    0.00 KB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0
 Int      0/0    0.00 KB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0

** Compaction Stats [default] **
Priority    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Uptime(secs): 52800.2 total, 0.0 interval
Flush(GB): cumulative 0.000, interval 0.000
AddFile(GB): cumulative 0.000, interval 0.000
AddFile(Total Files): cumulative 0, interval 0
AddFile(L0 Files): cumulative 0, interval 0
AddFile(Keys): cumulative 0, interval 0
Cumulative compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Interval compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Stalls(count): 0 level0_slowdown, 0 level0_slowdown_with_compaction, 0 level0_numfiles, 0 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 0 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 0 total count

** File Read Latency Histogram By Level [default] **
2020/09/24-12:19:25.308856 7f136c7f8700 [db_impl/db_impl.cc:850] ------- DUMPING STATS -------
```

I'm not sure if something has gone wrong since it seems to still be running, but is showing no processing. Below is how my command runs on our slurm implementation
```
for i in *_1.fq.gz
do
srun sortmerna -ref /programs/sortmerna/data/rRNA_databases/silva-arc-16s-id95.fasta -ref /programs/sortmerna/data/rRNA_databases/silva-arc-23s-id98.fasta -ref /programs/sortmerna/data/rRNA_databases/silva-euk-18s-id95.fasta -ref /programs/sortmerna/data/rRNA_databases/silva-euk-28s-id98.fasta -ref /programs/sortmerna/data/rRNA_databases/silva-bac-16s-id90.fasta -ref /programs/sortmerna/data/rRNA_databases/silva-bac-23s-id98.fasta -reads ${i::-8}_1.fq.gz -reads ${i::-8}_2.fq.gz --other ../filtered_redone_fq/${i::-8} --fastx --out2 --paired_out --workdir /sortmerna_workdir/$i/
done
```

**Comment by michoug** [comment]
Hi, I have the same issue

**Comment by ryandikdan** [comment]
Could it be that since this sample has far more rRNA reads in it, that it takes much longer? The other samples took maybe a couple hours but this one took days and never finished.

**Comment by ekopylova** [comment]
@ryandikdan , indeed samples that have more rRNA will take longer to run because alignment is also performed for each read match (whereas alignment is mostly skipped for non-rRNA reads due to lack of number of matching k-mers to the database). Your sample is still running? How large is your file? Did you expect it to have more rRNA? @biocodz any suggestions to investigate? Thanks!!

**Comment by michoug** [comment]
Hi,
in my case, the issue was that the files were compressed, with the uncompressed files, it works but it is very slow.

**Comment by biocodz** [comment]
Please, provide the [trace](https://github.com/biocore/sortmerna#execution-trace). Otherwise not much can be said about the problem.

**Comment by biocodz** [comment]
please, instead of 
```
cat 1.fq.gz 2.fq.gz > new.fq.gz
```
try 
```
cat 1.fq.gz 2.fq.gz | gzip > new.fq.gz
```

**Comment by ryandikdan** [comment]
I tried this way of combining the files, but while it doesn't hold up the program anymore, it seems to skip these files through some error. I've attached the log file, since it's hard to show the relevant parts. For samples labeled 0h-AO* 
[slurm.hal0174.2015346.out.log](https://github.com/biocore/sortmerna/files/5387709/slurm.hal0174.2015346.out.log)
it says that the header is messed up. 
`[0;31mERROR[0m: [calculate:160]  the line [‹ ý¼ž^ Ä½Ùv#;-ø^ÿqOÎiÍ1GpæK?õÒêÿÿ”&&C¶˜v¦¥«SiËšJ66 õÿw»Ýyß\vÿÏÉîvûÿ7ýÛÑíeÿ¿«ÖÚ^­ÕW›îÆ?õU[›îju„»éxµé…éø¾4jøó] is not FASTA/Q header
[calculate:107] Starting statistics calculation on file: '0h-AO-1_1.fq.gz'  ...   srun: error: hal0174: task 0: Exited with exit code 1`
Any further guidance for combining these fq.gz files to get them to work would be appreciated.

The other files seem to work fine.

**Comment by biocodz** [comment]
Could you please provide for each original i.e. non-combined file the following:
```
ls -l FILE
file FILE
gzip -l FILE
```
e.g.
```
ls -l SRR1635864_1_20M.fastq.gz
  -rwxrwxrwx 1 biocodz biocodz 418104788 May 25 19:52 SRR1635864_1_20M.fastq.gz

file SRR1635864_1_20M.fastq.gz
  SRR1635864_1_20M.fastq.gz: gzip compressed data, was "SRR1635864_1_20M.fastq", last modified: Mon May 25 23:52:06 2020, from Unix

gzip -l SRR1635864_1_20M.fastq.gz
         compressed        uncompressed  ratio uncompressed_name
          418104788          1386773538  69.9% SRR1635864_1_20M.fastq
```

**Comment by ryandikdan** [comment]
Wow, very interesting:
`(base) ryan@DESKTOP-OILOPCQ:/mnt/f/All data$ ls -l 0h-AO-1more_1.fq.gz
-rwxrwxrwx 1 ryan ryan 2432478419 Sep  3 02:19 0h-AO-1more_1.fq.gz
(base) ryan@DESKTOP-OILOPCQ:/mnt/f/All data$ file 0h-AO-1more_1.fq.gz
0h-AO-1more_1.fq.gz: gzip compressed data, last modified: Wed Aug 26 08:30:47 2020, from Unix
(base) ryan@DESKTOP-OILOPCQ:/mnt/f/All data$ gzip -l 0h-AO-1more_1.fq.gz
         compressed        uncompressed  ratio uncompressed_name
         2432478419          1307320003 -86.1% `0h-AO-1more_1.fq`
It seems the gzip is rather strange... Do you think uncompressing then recompressing would fix it? I'm quite confused about negative compression.

**Comment by biocodz** [comment]
you can try to recompress them:
```
gzip -cd old.gz | gzip > new.gz
gzip -l new.gz
```

**Comment by ryandikdan** [comment]
I did this for a file and it was totally unchanged. Upon looking it up, it just seems to be an overflow error on determining compression percentage that happens with gzip files of a certain size, although I am confused as to only these newer files have the problem.

**Comment by biocodz** [comment]
Seems gzip has trouble with the file. 
Could you please try
```
gzip -tv file.gz
```

**Comment by ryandikdan** [comment]
For both files, the ones that work and ones that don't, all say OK

**Comment by biocodz** [comment]
I'd just try inflating a couple of problematic files and run the alignment on flat files. All the failed runs as seen from the log, failed at the very start because the inflation failed (the raw binary data returned), and the program couldn't even count the reads.

**Comment by ryandikdan** [comment]
I gunzipped a test file and it appears to work. I'll just unzip them before running then, thanks for all the guidance! I still wonder why the gz in these cases were giving issues...

**Comment by biocodz** [comment]
have you tried the troubleshooting hints from my last message?

**Comment by ryandikdan** [comment]
It doesn't appear to be a tar, outputting:
`tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors`
When I look through it with less, both the fq.gz and the fq it looks totally normal. Line counts are divisible by 4 and are the same comparing paired end data.
Here's an excerpt from the fq:
`      1 @V300063421L2C001R0030000001/1
      2 CCCCGTCGCTACTACCGATTGGATGGTTTAGTGAGGCCCTCGGATCGGCCCCGCCGGGGTCGGCCCACGGCCCTGGCGGAGCGCTGAGAAGACGGTCGAA
      3 +
      4 F=GGFFFGGGFBEEGEFFGFFFGGGFFGGGGFGFFFGFFFFGFFFFFGFGFGF@FEEF>EGGFFGF<F@FGFBFFGG4FFFGGF?E=GEGC=C;F?GB@F
      5 @V300063421L2C001R0030000032/1
      6 GGCAGATCTTGGTGGTAGTAGCAAATATTCAAACGAGAACTTTGAAGGCCGAAGTGGAGAAGGCTTCCATGTGAACAGCAGTTGAACATGGGTCAGTCGG
      7 +
      8 E0FFFFFFFFFDFFEFGFFGFFFFFFFFFFFFFFFFFFFFFFFFFFFBFFF;FFFFFAFFFF?FFFFFFF?FFFFFFBFFDFFFFFFGGFCFFFAFFFFF
      9 @V300063421L2C001R0030000059/1
     10 AAGCAAATATTCAAACGAGAACTTTGAAGGCCGAAGTGGAGAAGGCTTCCATGTGAACAGCAGTTGAACATGGGTCAGTCGGTCCTGAGAGATGGGCGAG
     11 +
     12 F'FFFFFFFFFFFFFFFFF8FFFFFFFFFCFFEFFFFFEFFFFFDFFFFFFFFFFFFFFFFFEFFFFF:GFFFFFFFFGFFF;FFFFEFFFFFFFF>FF;
     13 @V300063421L2C001R0030000159/1
     14 CATGCCCTTTGTACACACCGCCCGTCGCTACTACCGATTGGATGGTTTAGTGAGGCCCTCGGATCGGCCCCGCCGGGGTCGGCCCACGGCCCTGGCGGAG
     15 +
     16 F)FFFFGFGFGFGGGFGFFFFFFFF@?FFGFGGFFFFFGFFFGFFFFFEFFGCFGFFFFGFFCFFFGEFFFFFGFFGFFGFFFFFCFFFFFG;FFGF@0F`
and here's an excerpt from the fq.gz:
`      1 @V300063421L2C001R0030000019/1
      2 CCTCTGATCGTTTTTTCACTGACCCGGTGAGGCGGGGGGACGAGCCCCGAGGGGCTCTCGCTTCTGGCGCCAAGCGCCCGGCCGCGCCCCGGCCGGGCGC
      3 +
      4 F(FEFD?FFDFDFFEFEEFFF<FFFFDEF9D@FC<@BDEAEE>EFFFFF=C?@EEEFEFFEEFFFC>EC9E@E>DFD1F=*CE/=CD'EF9<7E&7CF/F
      5 @V300063421L2C001R0030000069/1
      6 CCTGGCATGCTAACTAGTTACGCGACCCCCGAGCGGTCGGCGTCCCCCAACTTCTTAGAGGGACAAGTGGCGTTCAGCCACCCGAGATTGAGCAATAACA
      7 +
      8 G=DEFFFFGGGFFFEFDGGGGDGF=EGGGFADGDEFFFFEGGF?FFGF@GDFFBEGACFGFA<GFDFAE;9GFCF8GFEAFGG,B?8GGE(DEEGBBGGF
      9 @V300063421L2C001R0030000070/1
     10 CCTGGTTAATTCCGATAACGAACGAGACTCTGGCATGCTAACTAGTTACGCGACCCCCGAGCGGTCGGCGTCCCCCAACTTCTTAGAGGGACAAGTGGCG
     11 +
     12 F>FGF=GFFGGGGFFGFGFFFFFGFFFFGFGFFFFGFGGGGFFFGFGFFFFF9FGFGGFFFGFFFFFFFGFDGFGFEG?GFGGF=CBEGFGFFFGDFFGF
     13 @V300063421L2C001R0030000098/1
     14 CACCTGTTGAGCTTGACTCTAGTCTGGCACGGTGAAGAGACATGAGAGGTGTAGAATAAGTGGGAGGCCCCCGGCGCCCCCCCGGTGTCCCCGCGAGGGG
     15 +
     16 F@FFFFFFFFFFGFFFFFFFGFFFGFEFF7FFFFFFFFFGFFFFGFGFFFFFFFFFFFFFFFFFFFFFFFFFFFGFFEFFFGF;F;FBBFFFEFABFDFF`

**Comment by biocodz** [comment]
can you try to gzip a file back again and check what `gzip -l` says? Does it still show a negative compression ratio?

**Comment by ryandikdan** [comment]
Yes I did that before and it was negative still.

**Comment by biocodz** [comment]
Seems like a bug in sortmerna inflation code, which uses zlib. If `less` manages the files OK, so should zlib. But I cannot troubleshoot without a problematic file. No files I used ever caused this problem.

**Comment by ryandikdan** [comment]
Actually it looks like it was working for these files then threw this error
```
[pop:108] wrislurmstepd: error: Detected 1 oom-kill event(s) in step 2445924.0 cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
```
The run had 200Gb of memory so I don't think it's a memory problem. Can I send you a file so you can look at it?

**Comment by biocodz** [comment]
Sure, if you could provide a download link, I'd have a look - biocodz at protonmail dot com - (if  necessary)

**Comment by PaulAONeill** [comment]
same here - had to give up on sortme (sorry)

**Comment by biocodz** [comment]
please use the latest [v4.3.3](https://github.com/biocore/sortmerna/releases/tag/v4.3.3)
