### ISSUE TITLE
SortMeRNA 4.2 goes into recursive read queue, write queue loop

### ISSUE THREAD

**Issue by yeodynasty** [biocore/sortmerna#264]
Dear users,

I've run SortMeRNA 4.2 with empty files in the out/ folder and no progress after two days. 
I suspect there is an issue.

Briefly, alignment has started, but the program quickly goes into a recursive loop:

[run:70] thread: 47647310247680 started
[pop:108] read_queue Popped read number: 49999
[pop:108] write_queue Popped read number: 50000
[pop:108] read_queue Popped read number: 99999
[pop:108] write_queue Popped read number: 99999
[pop:108] read_queue Popped read number: 149999
[pop:108] write_queue Popped read number: 150000
....

The execution trace file and the log file in the kvdb folder are attached.

Profile of my read files are: 
(name : size : line count)
1. clean_HEADBANDSTEM_1.fastq.gz : 11429480753 : 45851940 
2. clean_HEADBANDSTEM_2.fastq.gz : 11405098058 : 45103207

My shell script for submission are: 
----

#!/bin/sh
#$ -V
## Join standard error and standard output into one file
#$ -j y
## Specify mpi
#$ -pe mpi 16

rm -rf /gpfshome/hockchuan/sortmerna/run/kvdb/HEADBANDSTEM/

/gpfshome/hockchuan/sortmerna/sortmerna --ref /gpfshome/hockchuan/sortmerna/rRNA_databases/silva-bac-16s-id90.fasta \
--ref /gpfshome/hockchuan/sortmerna/rRNA_databases/silva-bac-23s-id98.fasta \
--ref /gpfshome/hockchuan/sortmerna/rRNA_databases/silva-arc-16s-id95.fasta \
--ref /gpfshome/hockchuan/sortmerna/rRNA_databases/silva-arc-23s-id98.fasta \
--ref /gpfshome/hockchuan/sortmerna/rRNA_databases/silva-euk-18s-id95.fasta \
--ref /gpfshome/hockchuan/sortmerna/rRNA_databases/silva-euk-28s-id98.fasta \
--ref /gpfshome/hockchuan/sortmerna/rRNA_databases/rfam-5s-database-id98.fasta \
--ref /gpfshome/hockchuan/sortmerna/rRNA_databases/rfam-5.8s-database-id98.fasta \
--reads /gpfsdata/JangiLab/hockchuan/170302/3.rep_combined/clean_HEADBANDSTEM_1.fastq.gz \
--reads /gpfsdata/JangiLab/hockchuan/170302/3.rep_combined/clean_HEADBANDSTEM_2.fastq.gz \
--fastx \
--sam \
--paired_in \
--out2 \
-e 1 \
--threads $NSLOTS \
-m 32768 \
--kvdb /gpfshome/hockchuan/sortmerna/run/kvdb/HEADBANDSTEM/ 

----  

Please kindly assist.
Sincerely, HC

[KVDB_LOG.txt](https://github.com/biocore/sortmerna/files/5289280/KVDB_LOG.txt)
[ExecutionTrace.txt](https://github.com/biocore/sortmerna/files/5289281/ExecutionTrace.txt)

**Comment by yeodynasty** [comment]
Further details about my gz version and files:

[hockchuan@tll-rv1 3.rep_combined]$ gzip --version
gzip 1.3.12
Copyright (C) 2007 Free Software Foundation, Inc.
Copyright (C) 1993 Jean-loup Gailly.

[hockchuan@tll-rv1 3.rep_combined]$ gzip -l clean_HEADBANDSTEM_1.fastq.gz
         compressed        uncompressed  ratio uncompressed_name
        11429480753          3942839869 -189.9% clean_HEADBANDSTEM_1.fastq

[hockchuan@tll-rv1 3.rep_combined]$ gzip -l clean_HEADBANDSTEM_2.fastq.gz
         compressed        uncompressed  ratio uncompressed_name
        11405098058          3890181109 -193.2% clean_HEADBANDSTEM_2.fastq

**Comment by yeodynasty** [comment]
Details about my system:

[hockchuan@tll-rv1 3.rep_combined]$ uname -a
Linux tll-rv1 2.6.32-358.el6.x86_64 #1 SMP Fri Feb 22 00:31:26 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

**Comment by biocodz** [comment]
Not sure the meaning of "the program quickly goes into a recursive loop"
Could you provide the [trace](https://github.com/biocore/sortmerna#execution-trace)?

**Comment by biocodz** [comment]
Your reads files are quite big (~500M reads total), so aligning them against 8 databases takes time. 
Your trace is OK and shows the progress as expected.
The alignment was done OK and it took on average 5 hours per DB, 40 hours in total.
```
[align:462] Done index 0 Part: 1 Time: 16908.45 sec
[align:462] Done index 1 Part: 1 Time: 16430.84 sec
[align:462] Done index 2 Part: 1 Time: 15194.41 sec
[align:462] Done index 3 Part: 1 Time: 14807.28 sec
[align:462] Done index 4 Part: 1 Time: 18735.41 sec
[align:462] Done index 5 Part: 1 Time: 20861.02 sec
[align:462] Done index 6 Part: 1 Time: 14830.42 sec
[align:462] Done index 7 Part: 1 Time: 14213.56 sec
[align:469] ==== Done alignment ====

[postProcess:206] ==== Starting Post-processing (alignment statistics report) ====
```
Your trace ends on the second stage of the processing - the 'statistics report'. All together there are 3 stages, the first one 'alignment' being the longest.

The files of this size should be processed on HPC using many more threads than 16, but this is currently not possible due to a bug, which should be fixed in the upcoming release.

**Comment by yeodynasty** [comment]
Hi, 
since mine is a plant species, I'll just remove the prokaryote and Archaea databases to double up my speed.

Thank you for your assistance.
