### ISSUE TITLE
Unusual coverage values in aligned.log

### ISSUE THREAD

**Issue by cwoehle** [biocore/sortmerna#266]
Hello,

I recently tried to use SortMeRNA to differentiate different rRNA type contents based on the
databases in the data/rRNA_databases folder. Generally, the results look good just for archaea rRNA the numbers are extremely large, while archaea hits are basically absent from the data.
I think here might be a problem caused by the number of hits being too low to be calculated/displayed properly.

I would be grateful for any clarification or hints on how to proceed.
Can I simply tread them as ~0.0 ?

Best wishes,
Christian

Here is some relevant content of the aligned.log file:

```
Results:
    Total reads passing E-value threshold = 1566762 (51.23)
    Total reads failing E-value threshold = 1491594 (48.77)
    Minimum read length = 15
    Maximum read length = 151
    Mean read length    = 148

 Coverage by database:
    /home/cwoehle/tools/sortmerna/data/rRNA_databases/rfam-5.8s-database-id98.fasta		3.87
    /home/cwoehle/tools/sortmerna/data/rRNA_databases/rfam-5s-database-id98.fasta		0.02
    /home/cwoehle/tools/sortmerna/data/rRNA_databases/silva-arc-16s-id95.fasta		603158833266688.00
    /home/cwoehle/tools/sortmerna/data/rRNA_databases/silva-arc-23s-id98.fasta		603158833266688.00
    /home/cwoehle/tools/sortmerna/data/rRNA_databases/silva-bac-16s-id90.fasta		0.67
    /home/cwoehle/tools/sortmerna/data/rRNA_databases/silva-bac-23s-id98.fasta		2.68
    /home/cwoehle/tools/sortmerna/data/rRNA_databases/silva-euk-18s-id95.fasta		2.46
    /home/cwoehle/tools/sortmerna/data/rRNA_databases/silva-euk-28s-id98.fasta		41.46
```

I used SortMeRNA version 4.2.0 with the following command:

`sortmerna --threads 32 --reads F_S2_L001_R1_001.fastq.gz --reads F_S2_L001_R2_001.fastq.gz --workdir F --ref /home/cwoehle/tools/sortmerna/data/rRNA_databases/rfam-5.8s-database-id98.fasta --ref /home/cwoehle/tools/sortmerna/data/rRNA_databases/rfam-5s-database-id98.fasta --ref /home/cwoehle/tools/sortmerna/data/rRNA_databases/silva-arc-16s-id95.fasta --ref /home/cwoehle/tools/sortmerna/data/rRNA_databases/silva-arc-23s-id98.fasta --ref /home/cwoehle/tools/sortmerna/data/rRNA_databases/silva-bac-16s-id90.fasta --ref /home/cwoehle/tools/sortmerna/data/rRNA_databases/silva-bac-23s-id98.fasta --ref /home/cwoehle/tools/sortmerna/data/rRNA_databases/silva-euk-18s-id95.fasta --ref /home/cwoehle/tools/sortmerna/data/rRNA_databases/silva-euk-28s-id98.fasta
`

**Comment by biocodz** [comment]
Looks like a bug in printout of very small numbers. 
Coverage of 51.16 = ( 3.87 + 0.02 + 0.67 + 2.68 + 2.46 + 41.46)  leaves (51.23 - 51.16) = 0.07 for both 'arc' files, so your assumption of ~0.0 is about correct.
We'll fix this in upcoming release.
Thanks for reporting.

**Comment by biocodz** [comment]
include in release 4.3.6
