### ISSUE TITLE
[Refstats:32] Index Statistics calculation Start ...Aborted (core dumped)

### ISSUE THREAD

**Issue by silviabrochet** [biocore/sortmerna#267]
**SOLVED (I re-did the indexing and suddenly it works...)

Hello.
I am trying to use sortmerna and I am running into issues. I tried to fix it looking on internet but it gets quite difficult to find solutions for this version (the latest one) so I decided to write you. One thing that I have doubts about = I dowloaded the reference files separately because I am using the computer of a colleague that had to install sortmerna for me (as a conda environment).

My command:
/opt/anaconda/pkgs/sortmerna-4.2.0-0/bin/sortmerna -ref /home/silvia/invivo_RNAseq/fastq/sortmerna/silva-bac-16s-id90.fasta -ref /home/silvia/invivo_RNAseq/fastq/sortmerna/silva-bac-23s-id98.fasta -ref /home/silvia/invivo_RNAseq/fastq/sortmerna/silva-arc-16s-id95.fasta -ref /home/silvia/invivo_RNAseq/fastq/sortmerna/silva-arc-23s-id98.fasta -ref /home/silvia/invivo_RNAseq/fastq/sortmerna/silva-euk-18s-id95.fasta -ref /home/silvia/invivo_RNAseq/fastq/sortmerna/silva-euk-28s-id98.fasta -ref /home/silvia/invivo_RNAseq/fastq/sortmerna/rfam-5s-database-id98.fasta -ref /home/silvia/invivo_RNAseq/fastq/sortmerna/rfam-5.8s-database-id98.fasta -reads SB_01_L7_R1_001_trimmed.fastq -fastx -aligned "SB_01_L7_R1_001_rRNA" -other "SB_01_L7_R1_001_non-rRNA" -threads 15 -v

My error:
(sortmerna) silvia@pipiyolin:~/invivo_RNAseq/fastq$ /opt/anaconda/pkgs/sortmerna-4.2.0-0/bin/sortmerna -ref /home/silvia/invivo_RNAseq/fastq/sortmerna/silva-bac-16s-id90.fasta -ref /home/silvia/invivo_RNAseq/fastq/sortmerna/silva-bac-23s-id98.fasta -ref /home/silvia/invivo_RNAseq/fastq/sortmerna/silva-arc-16s-id95.fasta -ref /home/silvia/invivo_RNAseq/fastq/sortmerna/silva-arc-23s-id98.fasta -ref /home/silvia/invivo_RNAseq/fastq/sortmerna/silva-euk-18s-id95.fasta -ref /home/silvia/invivo_RNAseq/fastq/sortmerna/silva-euk-28s-id98.fasta -ref /home/silvia/invivo_RNAseq/fastq/sortmerna/rfam-5s-database-id98.fasta -ref /home/silvia/invivo_RNAseq/fastq/sortmerna/rfam-5.8s-database-id98.fasta -reads SB_01_L7_R1_001_trimmed.fastq -fastx -aligned "SB_01_L7_R1_001_rRNA" -other "SB_01_L7_R1_001_non-rRNA" -threads 15 -v

[process:1369] === Options processing starts ... ===

Found value: /opt/anaconda/pkgs/sortmerna-4.2.0-0/bin/sortmerna
Found flag: -ref
Found value: /home/silvia/invivo_RNAseq/fastq/sortmerna/silva-bac-16s-id90.fasta of previous flag: -ref
Found flag: -ref
Found value: /home/silvia/invivo_RNAseq/fastq/sortmerna/silva-bac-23s-id98.fasta of previous flag: -ref
Found flag: -ref
Found value: /home/silvia/invivo_RNAseq/fastq/sortmerna/silva-arc-16s-id95.fasta of previous flag: -ref
Found flag: -ref
Found value: /home/silvia/invivo_RNAseq/fastq/sortmerna/silva-arc-23s-id98.fasta of previous flag: -ref
Found flag: -ref
Found value: /home/silvia/invivo_RNAseq/fastq/sortmerna/silva-euk-18s-id95.fasta of previous flag: -ref
Found flag: -ref
Found value: /home/silvia/invivo_RNAseq/fastq/sortmerna/silva-euk-28s-id98.fasta of previous flag: -ref
Found flag: -ref
Found value: /home/silvia/invivo_RNAseq/fastq/sortmerna/rfam-5s-database-id98.fasta of previous flag: -ref
Found flag: -ref
Found value: /home/silvia/invivo_RNAseq/fastq/sortmerna/rfam-5.8s-database-id98.fasta of previous flag: -ref
Found flag: -reads
Found value: SB_01_L7_R1_001_trimmed.fastq of previous flag: -reads
Found flag: -fastx
Previous flag: -fastx is Boolean. Setting to True
Found flag: -aligned
Found value: SB_01_L7_R1_001_rRNA of previous flag: -aligned
Found flag: -other
Found value: SB_01_L7_R1_001_non-rRNA of previous flag: -other
Found flag: -threads
Found value: 15 of previous flag: -threads
Found flag: -v
[process:1453] Processing option: aligned with value: SB_01_L7_R1_001_rRNA
[process:1453] Processing option: fastx with value: 
[process:1453] Processing option: other with value: SB_01_L7_R1_001_non-rRNA
[process:1453] Processing option: reads with value: SB_01_L7_R1_001_trimmed.fastq
[opt_reads:73] Processing reads file [1] out of total [1] files
[process:1453] Processing option: ref with value: /home/silvia/invivo_RNAseq/fastq/sortmerna/silva-bac-16s-id90.fasta
[opt_ref:166] Processing reference [1] out of total [8] references
[opt_ref:220] File ["/home/silvia/invivo_RNAseq/fastq/sortmerna/silva-bac-16s-id90.fasta"] exists and is readable
[process:1453] Processing option: ref with value: /home/silvia/invivo_RNAseq/fastq/sortmerna/silva-bac-23s-id98.fasta
[opt_ref:166] Processing reference [2] out of total [8] references
[opt_ref:220] File ["/home/silvia/invivo_RNAseq/fastq/sortmerna/silva-bac-23s-id98.fasta"] exists and is readable
[process:1453] Processing option: ref with value: /home/silvia/invivo_RNAseq/fastq/sortmerna/silva-arc-16s-id95.fasta
[opt_ref:166] Processing reference [3] out of total [8] references
[opt_ref:220] File ["/home/silvia/invivo_RNAseq/fastq/sortmerna/silva-arc-16s-id95.fasta"] exists and is readable
[process:1453] Processing option: ref with value: /home/silvia/invivo_RNAseq/fastq/sortmerna/silva-arc-23s-id98.fasta
[opt_ref:166] Processing reference [4] out of total [8] references
[opt_ref:220] File ["/home/silvia/invivo_RNAseq/fastq/sortmerna/silva-arc-23s-id98.fasta"] exists and is readable
[process:1453] Processing option: ref with value: /home/silvia/invivo_RNAseq/fastq/sortmerna/silva-euk-18s-id95.fasta
[opt_ref:166] Processing reference [5] out of total [8] references
[opt_ref:220] File ["/home/silvia/invivo_RNAseq/fastq/sortmerna/silva-euk-18s-id95.fasta"] exists and is readable
[process:1453] Processing option: ref with value: /home/silvia/invivo_RNAseq/fastq/sortmerna/silva-euk-28s-id98.fasta
[opt_ref:166] Processing reference [6] out of total [8] references
[opt_ref:220] File ["/home/silvia/invivo_RNAseq/fastq/sortmerna/silva-euk-28s-id98.fasta"] exists and is readable
[process:1453] Processing option: ref with value: /home/silvia/invivo_RNAseq/fastq/sortmerna/rfam-5s-database-id98.fasta
[opt_ref:166] Processing reference [7] out of total [8] references
[opt_ref:220] File ["/home/silvia/invivo_RNAseq/fastq/sortmerna/rfam-5s-database-id98.fasta"] exists and is readable
[process:1453] Processing option: ref with value: /home/silvia/invivo_RNAseq/fastq/sortmerna/rfam-5.8s-database-id98.fasta
[opt_ref:166] Processing reference [8] out of total [8] references
[opt_ref:220] File ["/home/silvia/invivo_RNAseq/fastq/sortmerna/rfam-5.8s-database-id98.fasta"] exists and is readable
[process:1453] Processing option: threads with value: 15
[process:1453] Processing option: v with value: 

[process:1473] === Options processing done ===

[validate_kvdbdir:1245] 'workdir' option was not provided. Using USERDIR to set the working directory: ""
[validate_kvdbdir:1252] Key-value DB location "/home/silvia/sortmerna/run/kvdb"
[validate_idxdir:1233] IDX directory: "/home/silvia/sortmerna/run/idx" exists and is not empty

  Program:      SortMeRNA version 4.2.0

[main:63] Running command:
/opt/anaconda/pkgs/sortmerna-4.2.0-0/bin/sortmerna -ref /home/silvia/invivo_RNAseq/fastq/sortmerna/silva-bac-16s-id90.fasta -ref /home/silvia/invivo_RNAseq/fastq/sortmerna/silva-bac-23s-id98.fasta -ref /home/silvia/invivo_RNAseq/fastq/sortmerna/silva-arc-16s-id95.fasta -ref /home/silvia/invivo_RNAseq/fastq/sortmerna/silva-arc-23s-id98.fasta -ref /home/silvia/invivo_RNAseq/fastq/sortmerna/silva-euk-18s-id95.fasta -ref /home/silvia/invivo_RNAseq/fastq/sortmerna/silva-euk-28s-id98.fasta -ref /home/silvia/invivo_RNAseq/fastq/sortmerna/rfam-5s-database-id98.fasta -ref /home/silvia/invivo_RNAseq/fastq/sortmerna/rfam-5.8s-database-id98.fasta -reads SB_01_L7_R1_001_trimmed.fastq -fastx -aligned SB_01_L7_R1_001_rRNA -other SB_01_L7_R1_001_non-rRNA -threads 15 -v 
[Index:95] Index file ["/home/silvia/sortmerna/run/idx/15734375058464002811.bursttrie_0.dat"] already exists and is not empty.
[Index:95] Index file ["/home/silvia/sortmerna/run/idx/15734375058464002811.pos_0.dat"] already exists and is not empty.
[Index:95] Index file ["/home/silvia/sortmerna/run/idx/15734375058464002811.kmer_0.dat"] already exists and is not empty.
[Index:95] Index file ["/home/silvia/sortmerna/run/idx/15734375058464002811.stats"] already exists and is not empty.
[Index:116] Found 4 non-empty index files. Skipping indexing.
[Index:117] TODO: a better validation using an index descriptor to decide on indexing
[calculate:107] Starting statistics calculation on file: 'SB_01_L7_R1_001_trimmed.fastq'  ...   [calculate:225] Done statistics on file. Elapsed time: 13.67 sec. all_reads_count= 33693718
[store_to_db:421] Stored Reads statistics to DB:
    min_read_len= 36 max_read_len= 151 all_reads_count= 33693718 all_reads_len= 5043446684 total_reads_mapped= 0 total_reads_mapped_cov= 0 reads_matched_per_db= TODO is_total_reads_mapped_cov= 0 is_stats_calc= 0

[init:101] Testing file: "/home/silvia/invivo_RNAseq/fastq/SB_01_L7_R1_001_rRNA.fastq"
[init:131] Testing file: "/home/silvia/invivo_RNAseq/fastq/SB_01_L7_R1_001_non-rRNA.fastq"
[init:218] Testing file: "/home/silvia/invivo_RNAseq/fastq/SB_01_L7_R1_001_rRNA.log"

[align:359] ==== Starting alignment ====

[align:376] Using number of Processor threads set in run options: 15
Number of cores: 40 Read threads:  1 Write threads: 1 Processor threads: 15
[ThreadPool:36] initialized Pool with: [17] threads

[ReadsQueue:57] [read_queue] created with [1] Pushers
[ReadsQueue:57] [write_queue] created with [15] Pushers
terminate called after throwing an instance of 'Sls::error'
**[Refstats:32] Index Statistics calculation Start ...Aborted (core dumped)**

I hope you can help me to fix it.
Best,
Silvia Brochet

**Comment by biocodz** [comment]
This error was reported many times here. The search for  [Core dumped](https://github.com/biocore/sortmerna/issues?q=is%3Aissue+core+dumped) returns 8 results with the causes including corrupted command line and files.

**Comment by ppericard** [comment]
@biocodz the pb with a core dump is that the user has no idea what's happening and how to deal with it. Ideally, the software would make some checks on the command line at startup and the files at startup or while reading them in order to catch the error and throw a more explicit error message before crashing.
For non-informatician users, a core dump is something that will at best stop them completely, at worst they will just use another software to perform the task.

**Comment by biocodz** [comment]
point taken:-)

**Comment by silviabrochet** [comment]
Maybe I can try to ask one more question since we are here: is it possible that the sortmerna takes like 8 hours to process one single fastq file? Am I doing something wrong?

**Comment by biocodz** [comment]
depending on the reads' files size and the number of references and the hardware it may take many hours and days. [Here](https://github.com/biocore/sortmerna/blob/split_reads/scripts/test.jinja.yaml#L1748) in one of our tests on '8 reference databases + 50M reads' it took around 5 hr to perform the alignment. I've seen on this forum test data for ~500M reads on 8 refs that took ~40 hours to process

**Comment by ppericard** [comment]
@silviabrochet It will depend on the type of data you're analyzing and the sequencing depth. When working with whole metagenomic shotgun, you would expect a very small fraction of the reads to be rRNA. In this case, SortMeRNA will be very fast in discarding the non rRNA reads. But if you're working with metatranscriptomic datasets, then rRNA can represent up to 80% of all reads, and in this case, it will definitely take longer since SortMeRNA will align most of them. On big metaT datasets it could take up to a few days.

**Comment by biocodz** [comment]
please use the latest [v4.3.3](https://github.com/biocore/sortmerna/releases/tag/v4.3.3). It scales much better and can use any number of threads to accelerate the processing
