### ISSUE TITLE
V4.2-What is the difference between the two files in database?

### ISSUE THREAD

**Issue by xing592798030** [biocore/sortmerna#275]
What is the difference smr_v4.3_default_db.fasta and smr_v4.3_sensitive_db_rfam_seeds.fasta? Does the latter include the former? Should I choose one or can I use both?

**Comment by ekopylova** [comment]
Hello @xing592798030 !

Happy New Year!!

The differences between the databases is the % ID for clustering the sequences for each kingdom + rRNA component.
Specifically, 

smr_v4.3_default_db.fasta -> bac-16S 90%, 5S & 5.8S seeds, rest 95% (benchmark accuracy: 99.899%)
smr_v4.3_sensitive_db_rfam_seeds.fasta -> all 97%, except RFAM database which includes the full seed database sequences (benchmark accuracy: 99.907%)

As you can see from the benchmark, the accuracy (based on sensitivity and selectivity) is very good for both, however the "sensitive" database will run at least 2x slower.

Let me know if you are looking for more info,

Best,
Jenya

**Comment by xing592798030** [comment]
ok, I got it. thank you very much! Happy New Year!

Best,
Charles
