### ISSUE TITLE
build_index failed due wrong reference file format

### ISSUE THREAD

**Issue by MarioGutierrezR** [biocore/sortmerna#279]
Hello! I'm new to Sortmerna. I am trying to filter rRNAs from my paired-end RNA-seq data with the following command:
```
sortmerna -ref silva-bac-16s-id90.fasta -ref silva-bac-23s-id98.fasta -ref silva-euk-18s-id95.fasta -ref silva-euk-28s-id98.fasta -reads /home/mario/arabidopsis_seq/Col0M300A_S16_R1_001.fastq -reads /home/mario/arabidopsis_seq/Col0M300A_S16_R2_001.fastq
```

It shows this error: ERROR: [build_index:1230] Each read header of the database fasta file must begin with '>';
check sequence # 0

I've been searching for similar errors, but no one seems to have had this problem. I've also checked the fasta files, but nothing seems to be wrong.
Thanks for your help!

**Comment by biocodz** [comment]
Could you, please, provide the [execution trace](https://github.com/biocore/sortmerna#execution-trace)

**Comment by MarioGutierrezR** [comment]
![trace1](https://user-images.githubusercontent.com/74079902/105049054-dfd35b00-5a31-11eb-8940-eb1bfaa730b0.png)
![trace2](https://user-images.githubusercontent.com/74079902/105049150-faa5cf80-5a31-11eb-88c1-b806529e43aa.png)
![trace3](https://user-images.githubusercontent.com/74079902/105049218-0abdaf00-5a32-11eb-9694-bc73051e4a25.png)
Sorry I couldn't manage to copy the text.

**Comment by MarioGutierrezR** [comment]
![trace1](https://user-images.githubusercontent.com/74079902/105049897-caaafc00-5a32-11eb-9f9f-d2ca346d269c.png)
![trace2](https://user-images.githubusercontent.com/74079902/105049913-ce3e8300-5a32-11eb-8287-5cab9371603e.png)
![trace3](https://user-images.githubusercontent.com/74079902/105049936-d4ccfa80-5a32-11eb-8f2b-90e083c691f2.png)
Sorry I couldn't manage to copy the text.

**Comment by MarioGutierrezR** [comment]
![trace1](https://user-images.githubusercontent.com/74079902/105050272-38572800-5a33-11eb-8246-7c4bd1a2aa35.png)
![trace2](https://user-images.githubusercontent.com/74079902/105050283-3b521880-5a33-11eb-95bd-f55dbd4b3ab5.png)
![trace3](https://user-images.githubusercontent.com/74079902/105050289-3e4d0900-5a33-11eb-80a0-90f1ac0424ec.png)
Sorry I couldn't manage to copy the text.

**Comment by MarioGutierrezR** [comment]
![idx](https://user-images.githubusercontent.com/74079902/105054327-7c4c2c00-5a37-11eb-8b41-7c83127b91d2.png)

**Comment by biocodz** [comment]
could  you, please, repeat the run with `-v` option. The index seems to be already built but the program tries to index again.

**Comment by MarioGutierrezR** [comment]
![vop](https://user-images.githubusercontent.com/74079902/105060497-17480480-5a3e-11eb-8bc0-7179ba2746bb.png)
The -v option sends the same error message. This is the output of the subsequent commands.

**Comment by biocodz** [comment]
your refs files have a wrong format: html instead of the plain ascii. How did you get them onto your machine?
If you download them over the internet using a browser, then make sure they are in the 'raw' format.
To download from Github go to [rRNA_databases](https://github.com/biocore/sortmerna/tree/master/data/rRNA_databases) -> select a file like [silva-arc-16s-id95.fasta](https://github.com/biocore/sortmerna/blob/master/data/rRNA_databases/silva-arc-16s-id95.fasta) -> click the `Download` button.
After downloading check your file:
```
file silva-arc-16s-id95.fasta silva-arc-23s-id98.fasta
silva-arc-16s-id95.fasta: ASCII text, with very long lines
silva-arc-23s-id98.fasta: ASCII text, with very long lines
```
or you can just clone the whole repo i.e. `git clone https://github.com/biocore/sortmerna` to get alll the data

**Comment by MarioGutierrezR** [comment]
Right, I didn't realised that was the problem! Now that I've downloaded them correctly, it's working just fine.
I will also consider your advice! Thanks a lot!
