### ISSUE TITLE
Update SortMeRNA to use SilvaDB 138

### ISSUE THREAD

**Issue by nh13** [biocore/sortmerna#282]
Now that SilvaDB release 138 is for non-commercial, could the rRNA databases be updated? 

CC: @ekopylova 

Related to: https://github.com/nf-core/rnaseq/issues/570

rRNA databases: https://github.com/biocore/sortmerna/tree/master/data/rRNA_databases

**Comment by ekopylova** [comment]
Hello @nh13 !

We did provide new databases (SILVA 138 SSU NR99 and SILVA 138 LSU) for download in the [previous release](https://github.com/biocore/sortmerna/releases/tag/v4.2.0), however they will be included directly in the next distribution (very soon).

The differences between the linked databases is the % ID for clustering the sequences for each kingdom + rRNA component.
Specifically,

smr_v4.3_default_db.fasta -> bac-16S 90%, 5S & 5.8S seeds, rest 95% (benchmark accuracy: 99.899%)
smr_v4.3_sensitive_db_rfam_seeds.fasta -> all 97%, except RFAM database which includes the full seed database sequences (benchmark accuracy: 99.907%)

The accuracy (based on sensitivity and selectivity) is very good for both, however the "sensitive" database will run at least 2x slower.

Let me know if you have further Q's,
Jenya

**Comment by nh13** [comment]
That's awesome thank you!

**Comment by biocodz** [comment]
[database.tar.gz](https://github.com/biocore/sortmerna/releases/download/v4.3.4/database.tar.gz) is provided with each release >=4.2.0

**Comment by sghignone** [comment]
sorry for re-opening the thread.
1) I was used to run sortmerna with this command [partial]
`sortmerna --ref $HOME/DB/rRNA_databases/silva-arc-16s-id95.fasta \
	--ref $HOME/DB/rRNA_databases/silva-arc-23s-id98.fasta \
	--ref $HOME/DB/rRNA_databases/silva-bac-16s-id90.fasta \
	--ref $HOME/DB/rRNA_databases/silva-bac-23s-id98.fasta \
	--ref $HOME/DB/rRNA_databases/silva-euk-18s-id95.fasta \
	--ref $HOME/DB/rRNA_databases/silva-euk-28s-id98.fasta \
	--ref $HOME/DB/rRNA_databases/rfam-5.8s-database-id98.fasta \
	--ref $HOME/DB/rRNA_databases/rfam-5s-database-id98.fasta \
[...]`
(those files are located [here](https://github.com/biocore/sortmerna/tree/master/data/rRNA_databases))
which is the correct command to run the same analysis with the databases included in current releases?

2) is there an official script to rebuild the [silva_ids_acc_tax.tar.gz](https://github.com/biocore/sortmerna/blob/master/data/rRNA_databases/silva_ids_acc_tax.tar.gz) from the files in the current database distribution?

Many thanks in advance
s.-

**Comment by biocodz** [comment]
The latest Db is [database.tar.gz](https://github.com/biocore/sortmerna/releases/download/v4.3.4/database.tar.gz), which holds 4 different files
```
140M smr_v4.3_default_db.fasta
 64M smr_v4.3_fast_db.fasta
399M smr_v4.3_sensitive_db.fasta
379M smr_v4.3_sensitive_db_rfam_seeds.fasta
```
The command is the same, just the reference is different and just a single one (out of 4 above)  `-ref $DATA/smr_v4.3_default_db.fasta`. The [test 46](https://github.com/biocore/sortmerna/blob/master/scripts/test.jinja.yaml#L3511) uses the new DB file.

**Comment by sghignone** [comment]
I just wanted to be sure all the arc, bac and euk divisions were included in one file (sorry, I didn't check before). I suppose that if I want to search for 5.8s and 5s i should use the file with rfam seeds
