### ISSUE TITLE
SortMeRNA stuck while using fastp result

### ISSUE THREAD

**Issue by Lix1993** [biocore/sortmerna#283]
```
/share/software/SortMeRNA/current/sortmerna --version

[process:1369] === Options processing starts ... ===

Found value: /share/software/SortMeRNA/current/sortmerna
Found flag: --version
[process:1453] Processing option: version with value: 

SortMeRNA version 4.2.0
Build Date: Mar  9 2020
sortmerna_build_git_sha:@e307e3a248c21ef70b9495f029cd86f61c33b7fd@
sortmerna_build_git_date:@2020/03/09 15:58:24@

```

**Comment by Lix1993** [comment]
rawdata:

[1.fastq.gz](https://github.com/biocore/sortmerna/files/6034261/1.fastq.gz)
[2.fastq.gz](https://github.com/biocore/sortmerna/files/6034262/2.fastq.gz)

cleandata after fastp filter:

[1.clean.fastq.gz](https://github.com/biocore/sortmerna/files/6034276/1.clean.fastq.gz)
[2.clean.fastq.gz](https://github.com/biocore/sortmerna/files/6034277/2.clean.fastq.gz)

**Comment by Lix1993** [comment]
SortMeRNA works fine on rawdata:

command:

`/share/software/SortMeRNA/current/sortmerna -ref /share/blast_db/rfam_silva_rRAN_tRNA_snRNA_snoRNA_v12.3/rfam_silva_rRNA.fa  --fastx --paired_in -reads  1.fastq.gz -reads  2.fastq.gz --threads 8 --out2 --other  trim_rRNA --kvdb  sortmerna_kvdb --idx /share/blast_db/rfam_silva_rRAN_tRNA_snRNA_snoRNA_v12.3/sortmerna_index/ --workdir  sortmerna`

**Comment by Lix1993** [comment]
It stucks on fastp out at

`[Index:117] TODO: a better validation using an index descriptor to decide on indexing`

**Comment by Lix1993** [comment]
when `zcat` fastq.gz to fastq, it works,
using `gzip` to compress the fastqs, it works too.

`gzip -l` results:
![image](https://user-images.githubusercontent.com/12579295/108967784-e43b0580-76ba-11eb-8a1a-644f79371f1a.png)

**Comment by Lix1993** [comment]
I solve this by using fifo to compress fastp result,like this:

```
mkfifo clean_1.fastq clean_2.fastq 
fastp -i 1.fastq.gz -o clean_1.fastq -I 2.fastq.gz -O clean_2.fastq  &
cat clean_1.fastq | gzip > clean1.fq.gz &
cat clean_2.fastq | gzip > clean2.fq.gz &
wait
```

**Comment by biocodz** [comment]
Was this resolved, or there is still a problem?

**Comment by Lix1993** [comment]
It seems a issue like #221

**Comment by Lix1993** [comment]
I skipped that question, using 4 times as long at fastp process....

There is something different between fastp result and gzip result, but these are both valid gzipped format

**Comment by biocodz** [comment]
Thanks for the detailed problem report. SMR sensitivity to gzipped files is a known issue. I'll get to it once the upcoming release is out of the door. I'll check your files. It's good to know the 'fastp' output is problematic, as I can lookup their code.

**Comment by biocodz** [comment]
It seems that `fastp` produces some sort of concatenated gzipped chunks, i.e. a non-uniform gzipped files, similar to `bgzip` reported in [issue 272](https://github.com/biocore/sortmerna/issues/272).
Such files require a logic to demarcate the chunks during processing, which `gzip` apparently has but not `sortmerna`.

Sortmerna runs OK after re-compressing the chunked `fastp` files:
```
gzip -cd 1.clean.fastq.gz | gzip > 1.clean.d.fq.gz  # works ok
gzip -cd 2.clean.fastq.gz | gzip > 2.clean.d.fq.gz  # works ok
```

Working on the fix...
