### ISSUE TITLE
Regarding rRNA removal from metatranscriptomics

### ISSUE THREAD

**Issue by razz1618** [biocore/sortmerna#284]
Hi,
Recently I used sortmerna to separate rRNA reads from my metatranscriptomics sample. The whole process went smoothly but I got more than 50% of the reads removed as rRNA. So, I am not sure whether did I use the command wrong as rRNA was digested from samples prior to sequencing (though a small percent is expected to be retained).

Here is the command I used (I wanted to remove archaea, bacteria,eukaryotes rRNA)

sortmerna -ref /home/mcs/database/sortmerna/silva-arc-16s-id95.fasta -ref /home/mcs/database/sortmerna/silva-arc-23s-id98.fasta -ref /home/mcs/database/sortmerna/silva-bac-16s-id90.fasta -ref /home/mcs/database/sortmerna/silva-bac-23s-id98.fasta -ref /home/mcs/database/sortmerna/silva-euk-18s-id95.fasta -ref /home/mcs/database/sortmerna/silva-euk-28s-id98.fasta -reads /home/mcs/gene/shail/metatranscriptomics/Manual_analysis/1.clean_reads/sunbeam_output/qc/decontam/450-5_1.fastq.gz -reads /home/mcs/gene/shail/metatranscriptomics/Manual_analysis/1.clean_reads/sunbeam_output/qc/decontam/450-5_2.fastq.gz -num_alignments 1 -v -workdir /home/mcs/database/sortmerna/data/ --other /home/mcs/gene/shail/metatranscriptomics/Manual_analysis/2.sortmerna/450-5 --fastx --out2 --threads 80 

This is the result I got

 Results:
    Total reads passing E-value threshold = 40310236 (52.04)
    Total reads failing E-value threshold = 37152450 (47.96)
    Minimum read length = 36
    Maximum read length = 150
    Mean read length    = 148

 Coverage by database:
    /home/mcs/database/sortmerna/silva-arc-16s-id95.fasta		2.35
    /home/mcs/database/sortmerna/silva-arc-23s-id98.fasta		10.91
    /home/mcs/database/sortmerna/silva-bac-16s-id90.fasta		0.83
    /home/mcs/database/sortmerna/silva-bac-23s-id98.fasta		3.62
    /home/mcs/database/sortmerna/silva-euk-18s-id95.fasta		9.18
    /home/mcs/database/sortmerna/silva-euk-28s-id98.fasta		25.14

As I infer 52.04% of the reads relate to rRNA and 47.96 to mRNA. Is it normal or did I do some mistake (this is my first time using sortmerna).

**Comment by ekopylova** [comment]
Hello @razz1618,

The command appears correct. It seems you have a high fraction of eukaryotic rRNA (18S, 28S). Are you sure rRNA depletion was performed for all rRNA? Can you take a subsample of the reads classified to rRNA and run them through Blast ([web server](https://blast.ncbi.nlm.nih.gov/Blast.cgi?PROGRAM=blastn&PAGE_TYPE=BlastSearch&LINK_LOC=blasthome) fastest)? Are you seeing rRNA hits? Thanks!

Jenya

**Comment by razz1618** [comment]
@ekopylovaThanks.  Yes. i selected 4-5 random sequences from the aligned files and used blast. All matches to 28s rRNA and loarge sub-unit rRNA. i am not sure whether rRNA depletion was performed for all rRNA, we used a commercial sequencing company for sequencing our data. They said it is standard procedure to digest rRNA prior to sequencing.Still, i will once again make sure with them about this.

**Comment by ekopylova** [comment]
@razz1618, generally the company which performed rRNA depletion should have results of the QC after depletion (e.g. fragment analyzer measurements) which should show little or no peaks for (all lengths) ribosomal RNA. Also, of course important to clarify which depletion kit was used. Hopefully you still have enough depth with the remaining mRNA reads to perform your analysis.
