### ISSUE TITLE
 sortmerna version 4.3.1 : processing doesn't start

### ISSUE THREAD

**Issue by megha20** [biocore/sortmerna#286]
Hi,

I'm running sortmerna version 4.3.1. The fastq.gz file has ~20 million 100bp reads obtained from single-end RNA-seq.
But the sample execution trace is stuck and processing doesn't start even after 12 hours. What could be the possible error. Here's the execution trace,

[process:1372] === Options processing starts ... ===
Found value: /home/lalm/tools/miniconda2/bin/sortmerna
Found flag: -ref
Found value: /home/lalm/tools/sortmerna-master/data/rRNA_databases//rfam-5.8s-database-id98.fasta of previous flag: -ref
Found flag: -ref
Found value: /home/lalm/tools/sortmerna-master/data/rRNA_databases//rfam-5s-database-id98.fasta of previous flag: -ref
Found flag: -ref
Found value: /home/lalm/tools/sortmerna-master/data/rRNA_databases//silva-euk-28s-id98.fasta of previous flag: -ref
Found flag: -ref
Found value: /home/lalm/tools/sortmerna-master/data/rRNA_databases//silva-euk-18s-id95.fasta of previous flag: -ref
Found flag: -ref
Found value: /home/lalm/tools/sortmerna-master/data/rRNA_databases//silva-arc-23s-id98.fasta of previous flag: -ref
Found flag: -ref
Found value: /home/lalm/tools/sortmerna-master/data/rRNA_databases//silva-arc-16s-id95.fasta of previous flag: -ref
Found flag: -ref
Found value: /home/lalm/tools/sortmerna-master/data/rRNA_databases//silva-bac-23s-id98.fasta of previous flag: -ref
Found flag: -ref
Found value: /home/lalm/tools/sortmerna-master/data/rRNA_databases//silva-bac-16s-id90.fasta of previous flag: -ref
Found flag: -reads
Found value: /home/lalm/Omeprazole_RNA_seq/fastq_files/AACTGTAG-ACGCCGCA.fastq.gz of previous flag: -reads
Found flag: -workdir
Found value: /scr1/users/lalm/Omeprazole_RNA_seq/sortmerna_results/AACTGTAG-ACGCCGCA of previous flag: -workdir
Found flag: -sam
Previous flag: -sam is Boolean. Setting to True
Found flag: -fastx
Previous flag: -fastx is Boolean. Setting to True
Found flag: -aligned
Previous flag: -aligned is Boolean. Setting to True
Found flag: -other
Found value: /scr1/users/lalm/Omeprazole_RNA_seq/sortmerna_results/AACTGTAG-ACGCCGCA/AACTGTAG-ACGCCGCA_non_rRNA of previous flag: -other
Found flag: -num_alignments
Found value: 1 of previous flag: -num_alignments
Found flag: -v

**Comment by biocodz** [comment]
Waiting for 12 hours is never necessary. From the execution trace a stuck process is rather obvious,  please, see [here](https://github.com/biocore/sortmerna#execution-trace).

Please, provide the exact command you issued, which should be a single line i.e. with no line breaks or other extraneous characters.

**Comment by megha20** [comment]
Here's the command
/home/lalm/tools/miniconda2/bin/sortmerna -ref $path_2/rfam-5.8s-database-id98.fasta -ref $path_2/rfam-5s-database-id98.fasta -ref $path_2/silva-euk-28s-id98.fasta -ref $path_2/silva-euk-18s-id95.fasta -ref $path_2/silva-arc-23s-id98.fasta -ref $path_2/silva-arc-16s-id95.fasta -ref $path_2/silva-bac-23s-id98.fasta -ref $path_2/silva-bac-16s-id90.fasta -reads /home/lalm/Omeprazole_RNA_seq/fastq_files/AACTGTAG-ACGCCGCA.fastq.gz -workdir $path_1/sortmerna_results/AACTGTAG-ACGCCGCA -sam -fastx -aligned -other $path_1/sortmerna_results/AACTGTAG-ACGCCGCA/AACTGTAG-ACGCCGCA_non_rRNA -num_alignments 1 -v

**Comment by megha20** [comment]
#!/bin/sh
# script for filtering ribosomal RNAs
# define variable path
path_1="/scr1/users/lalm/Omeprazole_RNA_seq"
path_2="/home/lalm/tools/sortmerna-master/data/rRNA_databases/"
mkdir $path_1/sortmerna_results/AACTGTAG-ACGCCGCA
/home/lalm/tools/miniconda2/bin/sortmerna -ref $path_2/rfam-5.8s-database-id98.fasta -ref $path_2/rfam-5s-database-id98.fasta -ref $path_2/silva-euk-28s-id98.fasta -ref $path_2/silva-euk-18s-id95.fasta -ref $path_2/silva-arc-23s-id98.fasta -ref $path_2/silva-arc-16s-id95.fasta -ref $path_2/silva-bac-23s-id98.fasta -ref $path_2/silva-bac-16s-id90.fasta -reads /home/lalm/Omeprazole_RNA_seq/fastq_files/AACTGTAG-ACGCCGCA.fastq.gz -workdir $path_1/sortmerna_results/AACTGTAG-ACGCCGCA -sam -fastx -aligned -other $path_1/sortmerna_results/AACTGTAG-ACGCCGCA/AACTGTAG-ACGCCGCA_non_rRNA -num_alignments 1 -v

**Comment by biocodz** [comment]
Options processing has not been finished. Otherwise you would see
```
...
[process:1476] === Options processing done ===
[process:1477] Alignment type: [best:1 num_alignments:1 min_lis:2 seeds:2]
...
```

I would suggest to run first without script, just the command line, and using the minimum options e.g. a single reference, the reads, and  '-fastx', to make sure the process starts. You can interrupt it at any time, and then add more options.

**Comment by megha20** [comment]
Hi,
It works fine with all the options when running on the terminal using command line.

**Comment by ChrisTrivedi** [comment]
Hi, I'm having a similar issue while trying to run on a SLURM-scheduled HPC. Running on a fairly small dataset (~100k paired-end reads). Fs and Rs have been concatenated together. I've also tried to increase the `-m` flag as suggested in a previous post. Initially, I ran with multiple `refs`, however, tried the suggestion above to strip everything else out and run with just one ref. Unfortunately, I can't tell from the trace if there is an error as it just hangs after `Running command:`. Thanks for any feedback!

Command:
`
sortmerna -reads /oasis/scratch/comet/ctrivedi/temp_project/IR_trans/02_Trim/cat_IR17_R1s.fastq.gz -reads /oasis/scratch/comet/ctrivedi/temp_project/IR_trans/02_Trim/cat_IR17_R2s.fastq.gz -ref /home/ctrivedi/sortmerna/source/sortmerna-4.2.0/data/rRNA_databases/silva-bac-16s-id90.fasta -fastx -workdir /oasis/scratch/comet/ctrivedi/temp_project/IR_trans/025_SortRNA --out2 --other -m 48000 --threads 24 
`

Trace:
```
[process:1369] === Options processing starts ... ===

Found value: sortmerna
Found flag: -reads
Found value: /oasis/scratch/comet/ctrivedi/temp_project/IR_trans/02_Trim/cat_IR17_R1s.fastq.gz of previous flag: -reads
Found flag: -reads
Found value: /oasis/scratch/comet/ctrivedi/temp_project/IR_trans/02_Trim/cat_IR17_R2s.fastq.gz of previous flag: -reads
Found flag: -ref
Found value: /home/ctrivedi/sortmerna/source/sortmerna-4.2.0/data/rRNA_databases/silva-bac-16s-id90.fasta of previous flag: -ref
Found flag: -fastx
Previous flag: -fastx is Boolean. Setting to True
Found flag: -workdir
Found value: /oasis/scratch/comet/ctrivedi/temp_project/IR_trans/025_SortRNA of previous flag: -workdir
Found flag: --out2
Previous flag: --out2 is Boolean. Setting to True
Found flag: --other
Previous flag: --other is Boolean. Setting to True
Found flag: -m
Found value: 48000 of previous flag: -m
Found flag: --threads
Found value: 24 of previous flag: --threads
[opt_workdir:1066] Using WORKDIR: ["/oasis/scratch/comet/ctrivedi/temp_project/IR_trans/025_SortRNA"] as specified
[process:1453] Processing option: fastx with value: 
[process:1453] Processing option: m with value: 48000
[process:1453] Processing option: other with value: 
[opt_other:285] other was specified without argument. Will use default Directory and Prefix for the non-aligned output.
[process:1453] Processing option: out2 with value: 
[process:1453] Processing option: reads with value: /oasis/scratch/comet/ctrivedi/temp_project/IR_trans/02_Trim/cat_IR17_R1s.fastq.gz
[opt_reads:73] Processing reads file [1] out of total [2] files
[process:1453] Processing option: reads with value: /oasis/scratch/comet/ctrivedi/temp_project/IR_trans/02_Trim/cat_IR17_R2s.fastq.gz
[opt_reads:73] Processing reads file [2] out of total [2] files
[process:1453] Processing option: ref with value: /home/ctrivedi/sortmerna/source/sortmerna-4.2.0/data/rRNA_databases/silva-bac-16s-id90.fasta
[opt_ref:166] Processing reference [1] out of total [1] references
[opt_ref:220] File ["/home/ctrivedi/sortmerna/source/sortmerna-4.2.0/data/rRNA_databases/silva-bac-16s-id90.fasta"] exists and is readable
[process:1453] Processing option: threads with value: 24

[process:1473] === Options processing done ===

[validate_kvdbdir:1252] Key-value DB location "/oasis/scratch/comet/ctrivedi/temp_project/IR_trans/025_SortRNA/kvdb"
[validate_idxdir:1233] IDX directory: "/oasis/scratch/comet/ctrivedi/temp_project/IR_trans/025_SortRNA/idx" exists and is not empty

  Program:      SortMeRNA version 4.2.0
  Copyright:    2016-2020 Clarity Genomics BVBA:
                Turnhoutseweg 30, 2340 Beerse, Belgium
                2014-2016 Knight Lab:
                Department of Pediatrics, UCSD, La Jolla
                2012-2014 Bonsai Bioinformatics Research Group:
                LIFL, University Lille 1, CNRS UMR 8022, INRIA Nord-Europe
  Disclaimer:   SortMeRNA comes with ABSOLUTELY NO WARRANTY; without even the
                implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
                See the GNU Lesser General Public License for more details.
  Contributors: Jenya Kopylova   jenya.kopylov@gmail.com
                Laurent Noé      laurent.noe@lifl.fr
                Pierre Pericard  pierre.pericard@lifl.fr
                Daniel McDonald  wasade@gmail.com
                Mikaël Salson    mikael.salson@lifl.fr
                Hélène Touzet    helene.touzet@lifl.fr
                Rob Knight       robknight@ucsd.edu

[main:63] Running command:
sortmerna -reads /oasis/scratch/comet/ctrivedi/temp_project/IR_trans/02_Trim/cat_IR17_R1s.fastq.gz -reads /oasis/scratch/comet/ctrivedi/temp_project/IR_trans/02_Trim/cat_IR17_R2s.fastq.gz -ref /home/ctrivedi/sortmerna/source/sortmerna-4.2.0/data/rRNA_databases/silva-bac-16s-id90.fasta -fastx -workdir /oasis/scratch/comet/ctrivedi/temp_project/IR_trans/025_SortRNA --out2 --other -m 48000 --threads 24 
slurmstepd: *** JOB 39073992 ON comet-10-35 CANCELLED AT 2021-04-10T05:38:43 ***
```

**Comment by biocodz** [comment]
@megha20 if the program runs fine on command line, then something is wrong with your bash script. I run this program using quite complex scripts (see [here](https://github.com/biocore/sortmerna/blob/master/scripts/test.jinja.yaml)), often remotely e.g on AWS, and on multiple operating systems without problems.

**Comment by megha20** [comment]
I tried running using both srun and sbatch for running the bash script. In case of both srun and sbatch, the process gets stuck at sometimes at indexing and sometimes at alignment whether the fastq file is zipped or not. However, with sbatch the stats are not updated in the execution trace and therefore it appears that the process doesn't start while running the script in the sbatch mode.

**Comment by biocodz** [comment]
@ChrisTrivedi 
for the start I would recommend to switch to the [latest version 4.3.2](https://github.com/biocore/sortmerna/releases/tag/v4.3.2). The tests on 50M reads ([test 43](https://github.com/biocore/sortmerna/blob/v4.3.2/scripts/test.jinja.yaml#L2631) -` 8 databases, 50M reads, 32 threads, ~80min on AWS m5.8xlarge + Ubuntu 18 + 32 cpu + 128 GB RAM + 32 GB HD`) ran much faster than 4.2.0, and using high number of threads was not a problem.

Using 24 threads on 100K reads doesn't make sense especially using 4.2.0. 4 threads will do just fine.

I also wouldn't bother with `-m` flag when using version 4.x.

Back to your problem - the alignment apparently didn't even start. The process stuck right after parsing the arguments. 
You can compare to the expected trace [here - 4.0.1](https://github.com/biocore/sortmerna/wiki/Sample-execution-trace-v4.0.1) and [here - 4.3.2](https://github.com/biocore/sortmerna/wiki/sample-execution-trace-v4.3.2)
I would try running a single job on a single batch just to confirm the process runs OK i.e. no slurm or any other complex job management tools. If one job runs OK, then try 2. After that you can scale to whatever number suits your needs.
If a single command in the terminal runs OK, then the problem is likely somewhere downstream if using supplementary tools for launching.

**Comment by biocodz** [comment]
@megha20 
i didn't test using batch/workload managers, but their job is just to run the processes similar like identical twins on a few machines. I know that many users of sortmerna do it though.

**Comment by ChrisTrivedi** [comment]
> @ChrisTrivedi
> for the start I would recommend to switch to the [latest version 4.3.2](https://github.com/biocore/sortmerna/releases/tag/v4.3.2). The tests on 50M reads ([test 43](https://github.com/biocore/sortmerna/blob/v4.3.2/scripts/test.jinja.yaml#L2631) -` 8 databases, 50M reads, 32 threads, ~80min on AWS m5.8xlarge + Ubuntu 18 + 32 cpu + 128 GB RAM + 32 GB HD`) ran much faster than 4.2.0, and using high number of threads was not a problem.
> 
> Using 24 threads on 100K reads doesn't make sense especially using 4.2.0. 4 threads will do just fine.
> 
> Back to your problem - the alignment apparently didn't even start. The process stuck right after parsing the arguments.
> You can compare to the expected trace [here - 4.0.1](https://github.com/biocore/sortmerna/wiki/Sample-execution-trace-v4.0.1) and [here - 4.3.2](https://github.com/biocore/sortmerna/wiki/sample-execution-trace-v4.3.2)
> I would try running a single job on a single batch just to confirm the process runs OK i.e. no slurm or any other complex job management tools. If one job runs OK, then try 2. After that you can scale to whatever number suits your needs.
> If a single command in the terminal runs OK, then the problem is likely somewhere downstream if using supplementary tools for launching.

Thank you for your help on the issue. I never did figure out why it wasn't running on SLURM and unfortunately, my HPC compute time has now expired. However, I would like to report that now I've been running successfully, with multiple databases on a small server with no problems at all. Your help was much appreciated!
