### ISSUE TITLE
Different results when added --paired out and out2

### ISSUE THREAD

**Issue by TKSJ2020** [biocore/sortmerna#291]

**Comment by biocodz** [comment]
Could you, please, try the [4.3.3 pre-release](https://github.com/biocore/sortmerna/releases/tag/v4.3.3-pre), which fixes a couple of serious bugs. Or wait until the 4.3.3. is released next week.

**Comment by TKSJ2020** [comment]
Hi, I installed again and it's working. Thank you

**Comment by biocodz** [comment]
closing as resolved
