### ISSUE TITLE
Databases for v4.3

### ISSUE THREAD

**Issue by vragh** [biocore/sortmerna#292]
Dear `SortMeRNA` team,

Thank you for the amazing tool!!

I see that `v4.3` is out, and the [release page](https://github.com/biocore/sortmerna/releases/tag/v4.3.3) lists a bunch of databases. The `v4.0` [documentation page](https://github.com/biocore/sortmerna/wiki/User-manual-v4.0#Databases) lists yet another bunch of databases. (Which I can't seem to be able to find?)

The documentation for `v4.3` seems to be WIP, so I'd like to ask:

- Which databases should I use? The one in the release, or these other `SILVA`/`Rfam` databases?
- If it's the ones from the release, which one in particular? What's the difference between `smr_v4.3_sensitive_db.fasta` and `mr_v4.3_sensitive_db_rfam_seeds.fasta`? What's the relationship between these and the separate `SILVA/Rfam` databases mentioned above?
- If were to just use all the `SILVA` and `Rfam` databases (not yours, but ones straight from the source) can I just specify all of them? Would this be a folly? Is it better to use one of your bundled databases instead?

Your assistance would be much appreciated. (Super sorry for asking a ton of questions, I'm just really confused.)

**Comment by ekopylova** [comment]
Hello @vragh,

We recommend to use ```smr_v4.3_default_db.fasta```.

The difference between the databases is the % ID for clustering the sequences for each kingdom + rRNA component.
Specifically,

smr_v4.3_default_db.fasta -> bac-16S 90%, 5S & 5.8S seeds, rest 95% (benchmark accuracy: 99.899%)
smr_v4.3_sensitive_db.fasta -> all 97% (benchmark accuracy: 99.907%)
smr_v4.3_sensitive_db_rfam_seeds.fasta -> all 97%, except RFAM database which includes the full seed database sequences

The accuracy (based on sensitivity and selectivity) is very good for both, however the "sensitive" database will run at least 2x slower.

Yes, you can use the complete SILVA and Rfam databases, however you will not gain much in terms of sensitivity (e.g. sensitivity for the default database is >99.9%) but the program will run much slower.

Best,
Jenya

**Comment by vragh** [comment]
Hi @ekopylova ,

Thank you for the pointers. I decided to go ahead with `smr_v4.3_sensitive_db_rfam_seeds.fasta`.

**Comment by ppericard** [comment]
@ekopylova, @vragh, just to be sure that the information is complete:

`smr_v4.3_sensitive_db.fasta` is the most complete database. As said above it includes all db clustered at 97%id, including the full RFAM 5S & 5.8S database (~150,000 sequences before clustering). 

On the other hand, the `smr_v4.3_sensitive_db_rfam_seeds.fasta` includes all db clustered at 97%id _except_ the RFAM db which only includes the seed sequences for 5S & 5.8S (~800 sequences).

I'm not sure there is much difference in terms of running time between these 2 dbs but if what you're looking for is maximum sensitivity I would advise using the `smr_v4.3_sensitive_db.fasta` database.

Best,
Pierre

**Comment by vragh** [comment]
@ppericard ,

Thanks for clarifying that!! I guess I'll give `smr_v4.3_sensitive_db.fasta` a try then also.
