### ISSUE TITLE
SortMeRNA version 4.3.3 no multi threading

### ISSUE THREAD

**Issue by Allelica13** [biocore/sortmerna#293]
Hi, I am using SortMeRNA on a Linux Red Hat server with parameter "--threads 32" but it seems it does not work, it's very slow. 
Please can you help me with this?
Thank you.

**Comment by biocodz** [comment]
can you please provide the [trace](https://github.com/biocore/sortmerna#execution-trace)

**Comment by Allelica13** [comment]
[trace.txt](https://github.com/biocore/sortmerna/files/6784844/trace.txt)

Hi,

here there is the trace for a subset of 10k reads.
With a "normal", let's say,  file with, with ~40M reads, and parameter "--threads 32" the program "freezes" after about 2 hours and a half of computation and does not complete the analysis (the trace stops after description of the flags).
I've also tried to analyse paired-end fastq files with 36,906,674 reads using parameter "--threads" set to 2 and 4, and it works fine. 
These are the running times:
- with --threads = 2 --> 12 hours
- with --threads = 4 --> 6 hours.

**Comment by biocodz** [comment]
Your trace looks good. No errors. And the runtime is in seconds. Not possible to see what's wrong.
Using 32 threads on 20000 reads is overkill. The time is wasted on splitting and merging the files. 4...8 threads would be OK

For 40M reads 32 threads is reasonable.

The trace stopped after the flags description means the processing of the reads choked right at the start and no alignment was ever attempted.
== I need to see the trace of such a stalled process. ==

In my tests on AWS with 32 threads on 50M reads against 8 database files, the splitting took ~1hr, and the total runtime was ~80min i.e. the reads files splitting took the lion share of the time [see here](https://github.com/biocore/sortmerna/blob/master/scripts/test.jinja.yaml#L3042)

**Comment by Allelica13** [comment]
Here it is the trace of the stalled process
[trace_freezed.txt](https://github.com/biocore/sortmerna/files/6790723/trace_freezed.txt)

Here it is another trace. I tried running it on another node and it worked fine and the total runtime was ~150 min.
[new_trace.txt](https://github.com/biocore/sortmerna/files/6790695/new_trace.txt)
I guess the problem was related to the server.

Thank you very much for your help!

**Comment by biocodz** [comment]
Good to know you got the positive results!
The stalled run looks like a system glitch. It hadn't actually finished even the options processing.
73M reads on 32 threads in 150min seems like a reasonable time.
Thank you for the input.
