### ISSUE TITLE
Error: terminate called after throwing an instance of 'Sls::error'

### ISSUE THREAD

**Issue by iwilkie** [biocore/sortmerna#296]
Dear sortmerna team,

I've been trying to run sortmerna on a sample and keep running into the same error. As stated in the title, the `.err` file states that "terminate called after throwing an instance of 'Sls::error'", and then my job is terminated and since I haven't really found any solutions to this problem online, I thought I might ask here. 

Based on the `.out` file it seems that the sorting completes, but when I check the directory where I want the output files to go the generated files are empty (0 kb). I don't understand where the error is coming from/what is causing the issue, as output files are generated and it says that the process completes.

Attached you will find:
- my script for the filtering (`filtering_script.txt`; converted from a .sl file)
- .err file (`error_file.txt`; also converted to .txt)
- .out file (`output_file.txt`; I've converted it to .txt in order to upload it here)
- a screenshot of the output files I get (`output_files_screenshot.png`)

Thanks in advance for your support, I really appreciate it!

---------------------------------------------------------------------

[filtering_script.txt](https://github.com/biocore/sortmerna/files/6857853/filtering_script.txt)

[error_file.txt](https://github.com/biocore/sortmerna/files/6857852/error_file.txt)

[output_file.txt](https://github.com/biocore/sortmerna/files/6857851/output_file.txt)

<img width="670" alt="ouput_files_screenshot" src="https://user-images.githubusercontent.com/77722641/126535811-64ad8b24-b200-4d04-8979-969b4c343f79.png">

**Comment by biocodz** [comment]
Please, use the latest release [v4.3.4](https://github.com/biocore/sortmerna/releases/tag/v4.3.4).
4.2.0 is not too good with large number of threads, which was the reason for the processing pipeline modification in versions 4.3.x. Also a few bugs were fixed since 4.2.0

**Comment by iwilkie** [comment]
> Please, use the latest release [v4.3.4](https://github.com/biocore/sortmerna/releases/tag/v4.3.4).

Thank you so much for the quick response, I will try it again on the newest version then.

**Comment by iwilkie** [comment]
@biocodz so I was running my script again with the new version (v4.3.4) yesterday and it was working, but unfortunately timed out due to the slurm settings I used. I just changed them and tried running it again but I'm now getting a new error: `terminate called after throwing an instance of 'std::out_of_range'`. Is this an issue from sortmerna or is something else causing this problem? 

Thanks!

---------------------------------------------

[filtering script](https://github.com/biocore/sortmerna/files/6883876/filtering_script.txt)
[filtering err file](https://github.com/biocore/sortmerna/files/6883877/filtering_err.txt)
[filtering out file](https://github.com/biocore/sortmerna/files/6883878/filtering_out.txt)
(as with my previous message, the files are converted to `.txt`s so that they can be uploaded here)

**Comment by iwilkie** [comment]
@biocodz so I was running the same script as above with the newest version (4.3.4) and it was working until it timed out due to the slurm settings (it had started sorting but then reached the 12h mark). I just changed some of the slurm settings and am now getting a different error after about 30s: `terminate called after throwing an instance of 'std::out_of_range'`. Is this error coming from sortmerna or is something else causing the problem?

Thanks!

--------------------------------------

[filtering_script.txt](https://github.com/biocore/sortmerna/files/6884168/filtering_script.txt)
[filtering_err.txt](https://github.com/biocore/sortmerna/files/6884169/filtering_err.txt)
[filtering_out.txt](https://github.com/biocore/sortmerna/files/6884170/filtering_out.txt)
(As with the previous post, I've converted the files to `.txt`s so I can upload them here)

**Comment by biocodz** [comment]
what is the output of:
```
lscpu

nproc

hostnamectl
```
You are using the default number of threads (2) on 26M reads. It'll take forever to process. I'd use at least `-threads 10` or 20, 30, 40 etc. So. let's see what your system has to offer.

The process started OK but crashed somewhere in the splitting. What's the output of
```
ls -lrt /home/ollie/iwilkie/sortmerna/run/readb/
```

**Comment by iwilkie** [comment]
@biocodz thank you so much! I ran it with 20 treads and it completed within 3 hours, thank you so much for the help, I really appreciate it 😄
