### ISSUE TITLE
Regarding plant rRNA

### ISSUE THREAD

**Issue by jeffinrockey** [biocore/sortmerna#299]
Hi,
This is not at all an issue. Instead a doubt.

The context is checking the suitability of SortMeRNA for identifying rRNA reads in reads not limited to microbial or metagenomic nature. The expected fastqs could be from microbial, animal or plants samples.

Version is 4.3.4

Problem is that while going through the taxon info in the headers of smr_v4.3_default_db.fasta in the database folder, I could not see headers having Viridiplantae.

Are they not to be expected at all or am I missing something or I am wrong to assume a utility of SortMeRNA in the context of plant rRNA.

Any further information in this regard would be very helpful.

Jeffin

**Comment by ekopylova** [comment]
Hello @jeffinrockey ,

The databases provided with SortMeRNA contain clustered sequences from the complete Silva 138 SSURef NR99, Silva 132 LSURef and RFAM databases (see table below). Therefore, you won't find all of the same taxonomy names in the clustered databases as in the SILVA rep. However, there are several with the key "Viridiplantae" (database downloaded [here](https://github.com/biocore/sortmerna/releases/download/v4.3.4/database.tar.gz)):

[1] >SILVA_138_SSURef_NR99;HQ188979.1.1694 Eukaryota;Archaeplastida;Chloroplastida;Chlorophyta;Chlorophyceae;Viridiplantae environmental sample;size=2

[2] >SILVA_138_SSURef_NR99;HQ188961.1.1693 Eukaryota;Archaeplastida;Chloroplastida;Chlorophyta;Chlorophyceae;Viridiplantae environmental sample;size=2

[3] >SILVA_138_SSURef_NR99;HQ188949.1.1733 Eukaryota;Archaeplastida;Chloroplastida;Charophyta;Phragmoplastophyta;Streptophyta;Embryophyta;Bryophyta;Polytrichales;Viridiplantae environmental sample;size=2

[4] >SILVA_138_SSURef_NR99;HQ188967.1.1724 Eukaryota;Archaeplastida;Chloroplastida;Chlorophyta;Ulvophyceae;Viridiplantae environmental sample;size=3

[5] >SILVA_138_SSURef_NR99;HQ188947.1.1717 Eukaryota;Archaeplastida;Chloroplastida;Charophyta;Phragmoplastophyta;Streptophyta;Embryophyta;Bryophyta;Polytrichales;Viridiplantae environmental sample;size=1

Hope this helps!
Jenya

|                     | Silva 138 SSURef NR99 |       |          |        |           |       | Silva 132 LSURef |       |          |        |           |       | RFAM v14.1 |        |        |       |
|---------------------|-----------------------|-------|----------|--------|-----------|-------|------------------|-------|----------|--------|-----------|-------|------------|--------|--------|-------|
|                     | Archaea               |       | Bacteria |        | Eukaryota |       | Archaea          |       | Bacteria |        | Eukaryota |       | 5S         |        | 5.8S   |       |
|                     | %clust                | #seqs | %clust   | #seqs  | %clust    | #seqs | %clust           | #seqs | %clust   | #seqs  | %clust    | #seqs | %clust     | #seqs  | %clust | #seqs |
| complete DBs        | 99%                   | 20389 | 99%      | 432033 | 99%       | 58562 | 100%             | 1449  | 100%     | 168096 | 100%      | 29298 | 100%       | 140644 | 100%   | 4777  |
| SMR v4.3 default db | 95%                   | 5268  | 90%      | 33064  | 95%       | 18567 | 95%              | 392   | 95%      | 7642   | 95%       | 8271  | seed       | 712    | seed   | 61    |

**Comment by jeffinrockey** [comment]
Hi Jenya.

Thank you for the information. Very helpful indeed.  

I was searching for Viridiplantae immediately following Eukaryota like in NCBI Taxonomy (_cellular organisms; Eukaryota; Viridiplantae; Streptophyta; Streptophytina; Embryophyta_) and thus missed. Sorry about that. 

The details in the reply also provided much more clarity on the sequences. Thanks again.

Jeffin
