### ISSUE TITLE
alignment filtering and evalue threshold recommendation

### ISSUE THREAD

**Issue by mariabernard** [biocore/sortmerna#301]
Hi,

I am exploring sortmerna output files and I have a question about alignment filtering threshold.

I launched sortmerna with default parameter on smr_v4.3_default_db on paired short reads (trimmed with trimgalore)
```
sortmerna --threads 4 \
# param
--blast '1 cigar qcov qstrand' --fastx --out2 -v --paired_in
# output
--workdir Results/SortMeRNA/smr_v4.3/$i  --aligned Results/SortMeRNA/smr_v4.3/$i/${i}_rRNA --other Results/SortMeRNA/smr_v4.3/$i/${i}_other  \
# ref
--ref ref/sortmerna/smr_v4.3_default_db.fasta --idx-dir ref/sortmerna/idx/ \
# input
--reads Results/trimGalore/${i}-*val_1.fq.gz --reads Results/trimGalore/${i}-*val_2.fq.gz
```
Most of the reads detected as rRNA have (at least for on read of the pair)  have high %id (first quartile > 90) and %cov  (first quartile > 99%), but some alignment are much worse with minimum %id ~70% and min %cov ~20%.

Playing with -e option (filtering on evalue) remove few poor alignment but there is still (to my point of view) non confident alignments, such as :

```
M01945:364:000000000-DB246:1:1102:15185:1597	SILVA_132_LSURef;FP929048.199.3108	100	44	0	0	1	44	527	570	3.69e-09	78	44M106S	29.3	+
```
Moreover the second read of this pair did not match the reference database.

Again this append in very few case but to my point of view this read pair can be considered as non rRNA, no ?

Despite this behavior, what evalue threshold do you suggest to use ? I see in an issue of @ppericard that they use 1.00e-05, is this an habit ?

**Comment by biocodz** [comment]
Hi. 
The following issues might be useful in answering your question: [271](https://github.com/biocore/sortmerna/issues/271), [217](https://github.com/biocore/sortmerna/issues/217), [207](https://github.com/biocore/sortmerna/issues/207)
