### ISSUE TITLE
[opt_ref:186] ERROR: Could not locate File [sortmerna-master/data/rRNA_databases/silva-euk-18s-id95.fasta,] 

### ISSUE THREAD

**Issue by JenW1984** [biocore/sortmerna#302]
I am trying to run sortmerna and am getting an error where sortmerna cannot find the rRNA database files.  I show the commands/error below and also the path contents to show the files are indeed there. What is going wrong?

`bigboi@pop-os:/media/bigboi/Seagate Expansion Drive$ sortmerna --reads  MergedForSortMeRNA/TP1_FandR_Merged.fq --ref sortmerna-master/data/rRNA_databases/silva-euk-18s-id95.fasta, sortmerna-master/index/silva-euk-18s-database-id95:sortmerna-master/data/rRNA_databases/silva-euk-28s-id98.fasta,sortmerna-master/index/silva-euk-28s-id98 --paired_in --fastx --aligned Rep3_Data_rRNA_Removed/TP1_matched-18S-28s --other Rep3_Data_rRNA/TP1_unmatched-18S-28s -a 24
[process:1376] === Options processing starts ... ===
Found value: sortmerna
Found flag: --reads
Found value: MergedForSortMeRNA/TP1_FandR_Merged.fq of previous flag: --reads
Found flag: --ref
Found value: sortmerna-master/data/rRNA_databases/silva-euk-18s-id95.fasta, of previous flag: --ref
Found value: sortmerna-master/index/silva-euk-18s-database-id95:sortmerna-master/data/rRNA_databases/silva-euk-28s-id98.fasta,sortmerna-master/index/silva-euk-28s-id98
Found flag: --paired_in
Previous flag: --paired_in is Boolean. Setting to True
Found flag: --fastx
Previous flag: --fastx is Boolean. Setting to True
Found flag: --aligned
Found value: Rep3_Data_rRNA_Removed/TP1_matched-18S-28s of previous flag: --aligned
Found flag: --other
Found value: Rep3_Data_rRNA/TP1_unmatched-18S-28s of previous flag: --other
Found flag: -a
Found value: 24 of previous flag: -a
[process:1460] Processing option: a with value: 24

[opt_a:840] WARNING: Option '-a' was Deprecated in favour of '-threads'. Redirecting to 'threads' ...
[process:1460] Processing option: aligned with value: Rep3_Data_rRNA_Removed/TP1_matched-18S-28s
[process:1460] Processing option: fastx with value: 
[process:1460] Processing option: other with value: Rep3_Data_rRNA/TP1_unmatched-18S-28s
[process:1460] Processing option: paired_in with value: 
[process:1460] Processing option: reads with value: MergedForSortMeRNA/TP1_FandR_Merged.fq
[opt_reads:97] Processing reads file [1] out of total [1] files
[process:1460] Processing option: ref with value: sortmerna-master/data/rRNA_databases/silva-euk-18s-id95.fasta,
[opt_ref:157] Processing reference [1] out of total [1] references
[opt_ref:175] File  [sortmerna-master/data/rRNA_databases/silva-euk-18s-id95.fasta,] appears to be a relative path. Trying to locate in current directory and in the working directory ...
[opt_ref:183] File  [sortmerna-master/data/rRNA_databases/silva-euk-18s-id95.fasta,] has not been found in the current directory. Trying the working directory ...

[opt_ref:186] ERROR: Could not locate File [sortmerna-master/data/rRNA_databases/silva-euk-18s-id95.fasta,] neither at current path ["/media/bigboi/Seagate Expansion Drive"] nor in Workdir [""]
Reference file (FASTA) absolute or relative path.

Use mutliple times, once per a reference file

bigboi@pop-os:/media/bigboi/Seagate Expansion Drive$ cd sortmerna-master/data/rRNA_databases/
bigboi@pop-os:/media/bigboi/Seagate Expansion Drive/sortmerna-master/data/rRNA_databases$ ls
README.txt                     rfam-5s-database-id98.fasta  silva-arc-16s-id95.fasta  silva-bac-16s-id90.fasta  silva-euk-18s-id95.fasta  silva_ids_acc_tax.tar.gz
rfam-5.8s-database-id98.fasta  scripts                      silva-arc-23s-id98.fasta  silva-bac-23s-id98.fasta  silva-euk-28s-id98.fasta
bigboi@pop-os:/media/bigboi/Seagate Expansion Drive/sortmerna-master/data/rRNA_databases$ 

`

**Comment by biocodz** [comment]
`--ref` is not correctly used. You have to specify `--ref` as many times as there are references i.e. `-ref REF1 -ref REF2 -ref REF3 ... -ref REFN ...`
