### ISSUE TITLE
SortMeRNA version 4.3.4 not working properly  in sbatch cluster

### ISSUE THREAD

**Issue by SitaoZ** [biocore/sortmerna#304]
Hello, my script was running properly on the local server by `nohup sh work.sh &`,
my work.sh was listed as follows. 
`/home/zhusitao/project/biosoft/sortmerna-4.3.4-Linux/bin/sortmerna --threads 4 --workdir /home/zhusitao/project/ath/root/DRP003836/DRX099517/03.remove_rRNA/ --ref /home/zhusitao/project/biosoft/sortmerna/data/rRNA_databases/silva-euk-18s-id95.fasta --ref /home/zhusitao/project/biosoft/sortmerna/data/rRNA_databases/silva-euk-28s-id98.fasta --ref /home/zhusitao/project/biosoft/sortmerna/data/rRNA_databases/rfam-5.8s-database-id98.fasta --ref /home/zhusitao/project/biosoft/sortmerna/data/rRNA_databases/rfam-5s-database-id98.fasta --reads /home/zhusitao/project/ath/root/DRP003836/DRX099517/02.trim/DRR106422_1_trimed.fq.gz --reads /home/zhusitao/project/ath/root/DRP003836/DRX099517/02.trim/DRR106422_2_trimed.fq.gz --paired_out --out2 --sam --num_alignments 1 --fastx --aligned DRR106422_rRNA --other DRR106422_non_rRNA -v`
But when I submit the script to the sbatch cluster , an error occurred. The output was listed as follows:
`[process:1376] === Options processing starts ... ===
Found value: /home/zhusitao/project/biosoft/sortmerna-4.3.4-Linux/bin/sortmerna
Found flag: --threads
Found value: 4 of previous flag: --threads
Found flag: --workdir
Found value: /home/zhusitao/project/ath/root/DRP003836/DRX099517/03.remove_rRNA/ of previous flag: --workdir
Found flag: --ref
Found value: /home/zhusitao/project/biosoft/sortmerna/data/rRNA_databases/silva-euk-18s-id95.fasta of previous flag: --ref
Found flag: --ref
Found value: /home/zhusitao/project/biosoft/sortmerna/data/rRNA_databases/silva-euk-28s-id98.fasta of previous flag: --ref
Found flag: --ref
Found value: /home/zhusitao/project/biosoft/sortmerna/data/rRNA_databases/rfam-5.8s-database-id98.fasta of previous flag: --ref
Found flag: --ref
Found value: /home/zhusitao/project/biosoft/sortmerna/data/rRNA_databases/rfam-5s-database-id98.fasta of previous flag: --ref
Found flag: --reads
Found value: /home/zhusitao/project/ath/root/DRP003836/DRX099517/02.trim/DRR106422_1_trimed.fq.gz of previous flag: --reads
Found flag: --reads
Found value: /home/zhusitao/project/ath/root/DRP003836/DRX099517/02.trim/DRR106422_2_trimed.fq.gz of previous flag: --reads
Found flag: --paired_out
Previous flag: --paired_out is Boolean. Setting to True
Found flag: --out2
Previous flag: --out2 is Boolean. Setting to True
Found flag: --sam
Previous flag: --sam is Boolean. Setting to True
Found flag: --num_alignments
Found value: 1 of previous flag: --num_alignments
Found flag: --fastx
Previous flag: --fastx is Boolean. Setting to True
Found flag: --aligned
Found value: DRR106422_rRNA of previous flag: --aligned
Found flag: --other
Found value: DRR106422_non_rRNA of previous flag: --other
Found flag: -v`
Looking forward to your reply. Best wishes.

**Comment by biocodz** [comment]
@SitaoZ 
Hi, it's not possible to tell anything from the info you have provided. Not even if the alignment has actually started. 
Can you attach the [trace](https://github.com/biocore/sortmerna#execution-trace)?
In any case, if the program runs OK locally then your problem is the script processing, and it will be hard to advise what's wrong without accessing your environment.
