### ISSUE TITLE
4.2.0 and 4.3.4 killing large files

### ISSUE THREAD

**Issue by morgansobol** [biocore/sortmerna#305]
Hello, 

I have trouble getting sortmerna 4.2.0 and 4.3.4 to finish.
I suspect it has to do with the file size because my other samples with fewer reads were completed.

With 4.2.0, I tried increasing the -m value to 48000. Then I tried 4.3.4 since I saw in another issue that 4.2.0 had problems with large files. However, now it seems that 4.3.4 gets hung up as well.

Here is the output of gzip -l for both samples:

10G_2 = ~115 million reads
gzip -l 10G_2_S4_R1_001_val_1.fq.gz
 compressed        uncompressed  ratio uncompressed_name
 2044895092          3777712866  45.9% 10G_2_S4_R1_001_val_1.fq

5600_2= ~94 million
compressed uncompressed  ratio      uncompressed_name
 1211069493  3432541403     64.7%    5600G_2_S8_R1_001_val_1.fq

Trace from 4.3.4:

>[process:1376] === Options processing starts ... === 
Found value: /home/kit/ibg/fh9393/bin/sortmerna-4.3.4-Linux/bin/sortmerna
Found flag: -a
Found value: 40 of previous flag: -a
Found flag: -m
Found value: 48000 of previous flag: -m
Found flag: --ref
Found value: /home/kit/ibg/fh9393/bin/sortmerna-4.2.0/data/rRNA_databases/silva-bac-23s-id98.fasta of previous flag: --ref
Found flag: --ref
Found value: /home/kit/ibg/fh9393/bin/sortmerna-4.2.0/data/rRNA_databases/silva-bac-16s-id90.fasta of previous flag: --ref
Found flag: --ref
Found value: /home/kit/ibg/fh9393/bin/sortmerna-4.2.0/data/rRNA_databases/rfam-5s-database-id98.fasta of previous flag: --ref
Found flag: --kvdb
Found value: /pfs/work7/workspace/scratch/fh9393-2021Nov08_schwartz/results/rRNA_filter/4/kvdb/ of previous flag: --kvdb
Found flag: --idx-dir
Found value: /pfs/work7/workspace/scratch/fh9393-2021Nov08_schwartz/results/rRNA_filter/4/idx/ of previous flag: --idx-dir
Found flag: --aligned
Found value: /pfs/work7/workspace/scratch/fh9393-2021Nov08_schwartz/results/rRNA_filter/4/aligned_4 of previous flag: --aligned
Found flag: --other
Found value: /pfs/work7/workspace/scratch/fh9393-2021Nov08_schwartz/results/rRNA_filter/4/other_4 of previous flag: --other
Found flag: --reads
Found value: /pfs/work7/workspace/scratch/fh9393-2021Nov08_schwartz/results/trimmed/4//10G_2_S4_R1_001_val_1.fq.gz of previous flag: --reads
Found flag: --reads
Found value: /pfs/work7/workspace/scratch/fh9393-2021Nov08_schwartz/results/trimmed/4//10G_2_S4_R2_001_val_2.fq.gz of previous flag: --reads
Found flag: --aligned
Previous flag: --aligned is Boolean. Setting to True
Found flag: --other
Previous flag: --other is Boolean. Setting to True
Found flag: --fastx
[process:1460] Processing option: a with value: 40
[opt_a:840] ^[[0;33mWARNING^[[0m: Option '-a' was Deprecated in favour of '-threads'. Redirecting to 'threads' ...
[process:1460] Processing option: aligned with value: /pfs/work7/workspace/scratch/fh9393-2021Nov08_schwartz/results/rRNA_filter/4/aligned_4
[process:1460] Processing option: aligned with value:
[opt_aligned:238] Directory and Prefix for the aligned output was not provided. Using default dir/pfx: 'WORKDIR/out/aligned'
[process:1460] Processing option: fastx with value:
[process:1460] Processing option: idx-dir with value: /pfs/work7/workspace/scratch/fh9393-2021Nov08_schwartz/results/rRNA_filter/4/idx/
[opt_idxdir:1018] Using IDX dir: ["/pfs/work7/workspace/scratch/fh9393-2021Nov08_schwartz/results/rRNA_filter/4/idx/" as specified
[process:1460] Processing option: kvdb with value: /pfs/work7/workspace/scratch/fh9393-2021Nov08_schwartz/results/rRNA_filter/4/kvdb/
[opt_kvdb:1006] Using KVDB dir: ["/pfs/work7/workspace/scratch/fh9393-2021Nov08_schwartz/results/rRNA_filter/4/kvdb/" as specified
[process:1460] Processing option: m with value: 48000
[process:1460] Processing option: other with value: /pfs/work7/workspace/scratch/fh9393-2021Nov08_schwartz/results/rRNA_filter/4/other_4
[process:1460] Processing option: other with value:
[opt_other:267] other was specified without argument. Will use default Directory and Prefix for the non-aligned output.
/home/kit/ibg/fh9393/bin/sortmerna-4.3.4-Linux/bin/cmd_sortrRNA.sh: line 11: 3469073 Killed                  /home/kit/ibg/fh9393/bin/sortmerna-4.3.4-Linux/bin/s$
running...
finished sortmerna

Is there anything else I can try? Should I unzip the .gz files or should I divide the files into two?

Thanks!
Morgan

**Comment by biocodz** [comment]
Hi,
If that's all the trace you see, it means the file processing hasn't even started. The program was terminated before it was able to count the reads, and to split the files. Actually it was terminated even before the options processing finished, as otherwise you would see
```
[process:1476] === Options processing done ===
```
It doesn't look like the system watchdog terminated the process because of the limits, but you can still check: `ulimit -a`.
Please, double check you command.
You can try the `exact` same command with smaller files to ensure it works.
The max size of files used in SMR tests was ~50M reads in two files ~2G each [test 43](https://github.com/biocore/sortmerna/blob/master/scripts/test.jinja.yaml#L3189).

**Comment by morgansobol** [comment]
Hi @biocodz ,

I figured out it was an issue with my slurm settings for the HPC which were not utilizing the full computing resources I needed. 

Thanks!
Morgan
