### ISSUE TITLE
Sortmerna 4.3.4

### ISSUE THREAD

**Issue by biounique** [biocore/sortmerna#307]
Hi, 

Could you please help me with my code. I have just started to play with RNAseq data and I complete newbie to analysis. I have started with Sortmerna and I  was wondering how to separate output coming from two inputs fq files (as aligned, other, singleton for both paired  reads).
I dont know how to define  command in the way it treats as separate 8 .fq files?

My attempt so far:
/GWA$ sortmerna $Sortmerna_DB2 --reads 105_S1_L002_R1_001.fastq --reads 105_S1_L002_R2_001.fastq --paired_in -a 16 --fastx --aligned 105_S1_L002_rRNA --other 105_S1_L002_sortmerna --workdir ./srna_out/

It is working giving me one1 05_S1_L002_rRNA.fq   105_S1_L002_sortmerna.fq

Best,
B.

**Comment by biocodz** [comment]
Hi,
options that control the output are `-out2 -sout -paired_in -paired_out -other`
`-out2` puts FWD and REV reads into different files.
`-sout` separates paired and singleton aligned reads.
Note the limitations like `'sout' cannot be used with 'paired_in' | 'paired_out'` (see `sortmerna -h`)
You can find many examples of option usage in sortmerna [tests control file](https://github.com/biocore/sortmerna/blob/master/scripts/test.jinja.yaml)
Some examples:
[test 16_7](https://github.com/biocore/sortmerna/blob/master/scripts/test.jinja.yaml#L1019) `-sout` [2 files](https://github.com/biocore/sortmerna/blob/master/scripts/test.jinja.yaml#L1060)
[test 16_8](https://github.com/biocore/sortmerna/blob/master/scripts/test.jinja.yaml#L1063) `-out2 -sout` [4 files](https://github.com/biocore/sortmerna/blob/master/scripts/test.jinja.yaml#L1100)
[test 19_1](https://github.com/biocore/sortmerna/blob/master/scripts/test.jinja.yaml#L1562) `-paired_in -out2 -other` [4 files](https://github.com/biocore/sortmerna/blob/master/scripts/test.jinja.yaml#L1600)
[test 44_2](https://github.com/biocore/sortmerna/blob/master/scripts/test.jinja.yaml#L3345) `-out2 -sout -other` [8 files](https://github.com/biocore/sortmerna/blob/master/scripts/test.jinja.yaml#L3401)
