### ISSUE TITLE
reads number in log file is not inconsistent with it in the output fq file.

### ISSUE THREAD

**Issue by lancer-lu** [biocore/sortmerna#310]
Hi，thanks for your tools, It's very useful.

I found the number of reads stated in the log file is inconsistent with the number of reads in the output fq file.

- Here is my script：

`sortmerna --index 0 --threads 16 --ref /ref/rRNA/rfam-5.8s-database-id98.fasta --ref /ref/rRNA/rfam-5s-database-id98.fasta --ref/ref/rRNA/silva-arc-16s-id95.fasta --ref /ref/rRNA/silva-arc-23s-id98.fasta --ref/ref/rRNA/silva-bac-16s-id90.fasta --ref /ref/rRNA/silva-bac-23s-id98.fasta --ref /ref/rRNA/silva-euk-18s-id95.fasta --ref /ref/rRNA/silva-euk-28s-id98.fasta --idx-dir /ref/rRNA/idx/ --kvdb /home/kvdb/ --readb /home/readb/ --reads R9.nohuman.1.fq --reads R9.nohuman.2.fq --aligned R9_rRNA --other R9_clean --paired_out --fastx --out2`

- my output file(from --other )：

**R9_clean_fwd.fq R9_clean_rev.fq** 
#which means reads not aligned to the rRNA database, I thought the reads number should be the same with the output log file: "Total reads failing E-value threshold = 5535079 (94.33)". But when I stated the output fq:
`less R9_clean_rev.fq|grep "@"|wc -l
2887943`
total=288794*2=5775966!=Total reads failing E-value threshold = 5535079 (log file)

So I'm very confused, I would be appreciated if you answered me.

**Comment by biocodz** [comment]
Hi,
thanks for the feedback. However it's hard to answer the question based on the info you have provided.
Seeing the [trace](https://github.com/biocore/sortmerna#execution-trace) and the aligned.log file would be much better.
Please, have a look at the [test 19_3](https://github.com/biocore/sortmerna/blob/master/scripts/test.jinja.yaml#L1653) and its output [here](https://github.com/biocore/sortmerna/blob/master/scripts/test.jinja.yaml#L1684). It uses `paired_out, out2, other` like yours. Consider that `paired_out` puts any pair with either both or any one non-aligned strand into `other` i.e. `other` may contain aligned reads. The `aligned.log` shows the exact count of aligned and non-aligned reads, but `other` file only tells what `pairs` are non-aligned.

**Comment by lancer-lu** [comment]
> Hi, thanks for the feedback. However it's hard to answer the question based on the info you have provided. Seeing the [trace](https://github.com/biocore/sortmerna#execution-trace) and the aligned.log file would be much better. Please, have a look at the [test 19_3](https://github.com/biocore/sortmerna/blob/master/scripts/test.jinja.yaml#L1653) and its output [here](https://github.com/biocore/sortmerna/blob/master/scripts/test.jinja.yaml#L1684). It uses `paired_out, out2, other` like yours. Consider that `paired_out` puts any pair with either both or any one non-aligned strand into `other` i.e. `other` may contain aligned reads. The `aligned.log` shows the exact count of aligned and non-aligned reads, but `other` file only tells what `pairs` are non-aligned.

Thanks a lot，I got it.
