### ISSUE TITLE
File name is changing abnormally after running sortmerna

### ISSUE THREAD

**Issue by SA-Park** [biocore/sortmerna#312]
Hello, Thanks for great tool!

I'm writing this post to inform you something weird.
I set input file name as "PRO_Dis3_0h_r1_1.fastq_100bp.fq".
Then I run this commend :

> sortmerna \
> --ref $rRNA_path/rfam-5.8s-database-id98.fasta \
> --ref $rRNA_path/rfam-5s-database-id98.fasta \
> --ref $rRNA_path/silva-euk-18s-id95.fasta \
> --ref $rRNA_path/silva-euk-28s-id98.fasta \
> --reads $WD/01_Trim_100bp/PRO_Dis3_0h_r1_1.fastq_100bp.fq \
> --num_alignments 1 --fastx \
> --aligned $WD/02_sortmerna/aligned/PRO_Dis3_0h_r1_1.fastq_aligned.fq \
> --other $WD/02_sortmerna/unaligned/PRO_Dis3_0h_r1_1.fastq_unaligned.fq \
> -v --threads 14 \
> --kvdb $WD/02_sortmerna/kvdb/PRO_Dis3_0h_r1_1.fastq_kvdb \
> --idx-dir $WD/02_sortmerna/index/PRO_Dis3_0h_r1_1.fastq_index \
> -workdir $WD/02_sortmerna
>

And I got the following outputs....

> PRO_Dis3_0h_r1_1.fastq_aligned.fq.log
> PRO_Dis**3h_r1_1.fastq_aligned.fq_0**.fq
> [directory] PRO_Dis3_0h_r1_1.fastq_index
> [directory] PRO_Dis3_0h_r1_1.fastq_kvdb
> PRO_Dis**3h_r1_1.fastq_unaligned.fq_0**.fq

aligned & unaligned output file name got altered!
Name of other files which don't contain "_0" didn't altered.

In execution trace, the name changed at [merge:83].
I attached the execution trace log txt file here
[220109_sortmerna_excute.txt](https://github.com/biocore/sortmerna/files/7839716/220109_sortmerna_excute.txt)

I avoided this by simply changing the file name, but I decided to provide this information for others.
Hope this is helpful for you.

**Comment by biocodz** [comment]
Hi @SA-Park. 
Thanks for reporting this bug. 
Because the file names are complex, the logic broke while renaming the final output. Instead of removing the last '0' in the name, it removed the first one found. 
We'll fix this in the next release

**Comment by RaverJay** [comment]
This is still broken for me, running `SortMeRNA version 4.3.4`

**Comment by biocodz** [comment]
The fix will be included in release 4.3.6 (soon)

**Comment by biocodz** [comment]
fixed in [v4.3.6](https://github.com/biocore/sortmerna/releases/tag/v4.3.6)
