### ISSUE TITLE
Trouble locating reference files

### ISSUE THREAD

**Issue by bradleyclass** [biocore/sortmerna#313]
Hello,

 Where can I find the reference files? Are the suitable for _Drosophila_?

**Comment by biocodz** [comment]
Please, see [database.tar.gz](https://github.com/biocore/sortmerna/releases/download/v4.3.4/database.tar.gz) and the old ones at [rRNA_databases](https://github.com/biocore/sortmerna/tree/master/data/rRNA_databases)
