### ISSUE TITLE
--SQ parameter is non-functional

### ISSUE THREAD

**Issue by ahstram** [biocore/sortmerna#316]
The --SQ argument is advertised as such:

`    --SQ              BOOL        Optional  Add SQ tags to the SAM file`

However, when turning this option on, there appears to be no additional "SQ" information added to the output SAM file.

Upon further investigation, I found that src/sortmerna/report_sam.cpp has the following lines disabled via `# if 0` macro: https://github.com/biocore/sortmerna/blob/a7504fabece39c26cbf43dd7352c6b2475ed0639/src/sortmerna/report_sam.cpp#L158-L184

**Comment by biocodz** [comment]
Hi, thanks for reporting. I'll look into this.

**Comment by ahstram** [comment]
@biocodz please see PR #317

**Comment by biocodz** [comment]
fixed in [v4.3.6](https://github.com/biocore/sortmerna/releases/tag/v4.3.6)
