### ISSUE TITLE
sortmerna-4.3.4: stuck in reads spliting step

### ISSUE THREAD

**Issue by zjj19910** [biocore/sortmerna#320]
Hi,
I was trying to filter rRNA reads from my sequencing data. I used the 8 rRNA fasta files as a reference. But it got stuck in the splitting files step for 1 hour without any progress. No errors.
I attached the log as follows:

[trace.txt](https://github.com/biocore/sortmerna/files/8339825/trace.txt)

Can you tell me what happened? Shall I keep waiting for a moment?
Thank you.

**Comment by biocodz** [comment]
80M reads could take awhile to split. Depending on the hardware an hour or more. For large files the splitting is the most time consuming part of the processing.
You can see the splitting progress by issuing
```
ls -lrth sortmerna/HL-PBS-2/readb/
```
It will show you all the splits and how their size is growing as they are being filled up.

**Comment by zjj19910** [comment]
Thanks.
It's on the HPC, so there should be enough space for splitting files.
In fact, there were fwd_19 and rev_19 files in the readb directory, but the trace didn't show and remained the same for 1 hour.
I will try to see if these splitting files are changing this time and wait for some hours.

**Comment by biocodz** [comment]
The trace as the one attached is not normal. It should show all the splits created with 0 size e.g.
```
...
[next:322] EOF REV reached. Total reads: 19104889
[count_reads:979] done count. Elapsed time: 89.6753 sec. Total reads: 38209778
[init_split_files:1001] added file: /home/biocodz/sortmerna/run/readb/fwd_0.fq.gz
[init_split_files:1001] added file: /home/biocodz/sortmerna/run/readb/rev_0.fq.gz
[init_split_files:1001] added file: /home/biocodz/sortmerna/run/readb/fwd_1.fq.gz
[init_split_files:1001] added file: /home/biocodz/sortmerna/run/readb/rev_1.fq.gz
[init_split_files:1001] added file: /home/biocodz/sortmerna/run/readb/fwd_2.fq.gz
[init_split_files:1001] added file: /home/biocodz/sortmerna/run/readb/rev_2.fq.gz
[init_split_files:1001] added file: /home/biocodz/sortmerna/run/readb/fwd_3.fq.gz
[init_split_files:1001] added file: /home/biocodz/sortmerna/run/readb/rev_3.fq.gz
[init_split_files:1001] added file: /home/biocodz/sortmerna/run/readb/fwd_4.fq.gz
[init_split_files:1001] added file: /home/biocodz/sortmerna/run/readb/rev_4.fq.gz
[init_split_files:1001] added file: /home/biocodz/sortmerna/run/readb/fwd_5.fq.gz
[init_split_files:1001] added file: /home/biocodz/sortmerna/run/readb/rev_5.fq.gz
[init_split_files:1001] added file: /home/biocodz/sortmerna/run/readb/fwd_6.fq.gz
[init_split_files:1001] added file: /home/biocodz/sortmerna/run/readb/rev_6.fq.gz
[init_split_files:1001] added file: /home/biocodz/sortmerna/run/readb/fwd_7.fq.gz
[init_split_files:1001] added file: /home/biocodz/sortmerna/run/readb/rev_7.fq.gz
[is_split_ready:746] found existing readfeed descriptor /home/biocodz/sortmerna/run/readb/readfeed
[split:605] start splitting. Using number of splits equals number of processing threads: 8           <- here it might hang until the splitting is done
[clean:1132] found descriptor /home/biocodz/sortmerna/run/readb/readfeed
...
```

**Comment by zjj19910** [comment]
Here are the trace file and contents in the readb directory at the same time. 
Does it make sense?
![snapshot](https://user-images.githubusercontent.com/22379073/159921878-de8c9960-3530-49f6-85f4-705f81ae956b.png)
[trace2.txt](https://github.com/biocore/sortmerna/files/8341576/trace2.txt)

**Comment by zjj19910** [comment]
Yeah. I've downloaded it but I'm not sure which one to use, default, fast or sensitive? 
I just want to know how many of my sequencing reads are mapped to rRNA. Maybe default one is enough, I guess.

**Comment by biocodz** [comment]
sure, it'll give you the idea
