### ISSUE TITLE
Sortmerna output corrupted due directory space limits

### ISSUE THREAD

**Issue by mitharuka** [biocore/sortmerna#323]
Hello, 

We are using the latest version of SortMeRNA. And we have an issue with **getting only a cleaned-non-rRNA fastq file** after running the command. We didn't get rRNA fastq file or log file. We do expect a small amount of rRNA reads in these files. The trace looks normal as shown in the manual and we didn't get any errors. Does this mean there are no rRNA reads in the files? Do you know why we didn't get the log file? 

When we tried the same command with fastq files which we expected high rRNA reads, we were able to get cleaned-non-rRNA fastq file, rRNA fastq file, and log file. 

I would appreciate your insight on this. Thanks!

**Comment by biocodz** [comment]
The trace looks OK, and you are supposed to get 4 files according to the options used:
```
aligned.log  m6A_SEQ_SORTMERNA/Align_NS.1387.004.D701---D501.male_ctrl_1/NS.1387.004.D701---D501.male_ctrl_1_rRNA.log
aligned      m6A_SEQ_SORTMERNA/Align_NS.1387.004.D701---D501.male_ctrl_1/NS.1387.004.D701---D501.male_ctrl_1_rRNA.fq.gz
other        m6A_SEQ_SORTMERNA/Align_NS.1387.004.D701---D501.male_ctrl_1/NS.1387.004.D701---D501.male_ctrl_1_Clean.fq.gz
sam          m6A_SEQ_SORTMERNA/Align_NS.1387.004.D701---D501.male_ctrl_1/NS.1387.004.D701---D501.male_ctrl_1_rRNA.sam.gz
```
Can you find all those files? Per the trace all of them were generated without errors.

**Comment by mitharuka** [comment]
No, we only got 
`other        m6A_SEQ_SORTMERNA/Align_NS.1387.004.D701---D501.male_ctrl_1/NS.1387.004.D701---D501.male_ctrl_1_Clean.fq.gz`
We didn't get the other 3 files.

**Comment by biocodz** [comment]
what's the output of
```
ls -l /m6A_SEQ_SORTMERNA/Align_NS.1387.004.D701---D501.male_ctrl_1/NS.1387.004.D701---D501.male_ctrl_1_rRNA.log
```
?

**Comment by mitharuka** [comment]
We didn't get the .log file so there is no output from that.
Is it possible that if there are no rRNA reads found, **alinged.log** or **aligned.fastq** won't be generated? 

Also, we tried the same command for the other 40 samples, which we expected low rRNA reads. The same thing happened and we only got other.fastq for all the samples.

**Comment by biocodz** [comment]
All the files had to be generated, and there were aligned reads too as seen from the trace, although with `paired_out` all aligned reads could go to 'other' if no pairs were aligned.
Does the directory `/m6A_SEQ_SORTMERNA/Align_NS.1387.004.D701---D501.male_ctrl_1/` even exists? Try also searching this path relatively to the directory where the command was run. That's truly bizarre there are no files when the trace says they were generated. 
Also you may try specifying `--aligned /Haruka/m6A_SEQ_SORTMERNA/Align_NS.1387.004.D701---D501.male_ctrl_1/NS.1387.004.D701---D501.male_ctrl_1_rRNA` i.e. similar to how it is done for `--other`

**Comment by mitharuka** [comment]
Yes, we did specify `--aligned /Haruka/m6A_SEQ_SORTMERNA/Align_NS.1387.004.D701---D501.male_ctrl_1/NS.1387.004.D701---D501.male_ctrl_1_rRNA` similar to `--other  m6A_SEQ_SORTMERNA/Align_NS.1387.004.D701---D501.male_ctrl_1/NS.1387.004.D701---D501.male_ctrl_1_Clean`
And there are `/m6A_SEQ_SORTMERNA/Align_NS.1387.004.D701---D501.male_ctrl_1/` directory.  

Yes, we did use `--paired_out` option. So do you think there were no pairs aligned? But isn't it still weird that we didn't get .log file? 

Again, when we tried the same command with another dataset, in which we expect high rRNA reads, we were able to get .log, alinged.fastq, and other.fastq/

**Comment by biocodz** [comment]
This might me a system configuration problem similar to [issue 318](https://github.com/biocore/sortmerna/issues/318) where trouble was caused by the directory size limits. 
In your case it feels like the files are getting silently deleted as if redirected to /dev/null/

**Comment by mitharuka** [comment]
You were right, we were able to get all the files when we expanded the working directory size. 

Thank you for the prompt response and help us move forward!

**Comment by biocodz** [comment]
good to hear you have found the solution!
