### ISSUE TITLE
Conda installation

### ISSUE THREAD

**Issue by MichWeb75** [biocore/sortmerna#324]
Hi, I have installed conda sortmerna but how to proceed to download the silva-bac-16s-id90.fasta ? Do I need to download the github repository ? I cannot find the building scripts inside the conda environment.
Thank you for any help!

**Comment by biocodz** [comment]
Hi, 
the references are here: [rRNA_databases/](https://github.com/biocore/sortmerna/tree/master/data/rRNA_databases), and/or the latest [database.tar.gz](https://github.com/biocore/sortmerna/releases/download/v4.3.4/database.tar.gz)
