### ISSUE TITLE
Error while running sortmerna : "Segmentation fault (core dumped)"

### ISSUE THREAD

**Issue by NainaK6** [biocore/sortmerna#325]
I am getting "Segmentation fault (core dumped)" error while running sortmerna for paired end reads . The command I used is 
> sortmerna --ref silva-bac-16s-id90.fasta --ref silva-bac-23s-id98.fasta --ref silva-arc-16s-id95.fasta --ref   silva-arc-23s-id98.fasta --ref rfam-5.8s-database-id98.fasta --ref rfam-5s-database-id98.fasta --ref silva-euk-18s-id95.fasta --ref silva-euk-28s-id98.fasta –reads R1_paired_bengal. fastq –reads R2_paired_bengal. fastq --fastx --paired_in --other --workdir /home/sortmerna/

What could be the possible reason for this error?

**Comment by biocodz** [comment]
could you provide the [execution trace](https://github.com/biocore/sortmerna#execution-trace)?
