### ISSUE TITLE
Segmentation fault (core dumped) when splitting

### ISSUE THREAD

**Issue by daisyzhangsysu** [biocore/sortmerna#326]
Hi, 
I am getting the error segmentation fault (core dumped) when running sortmerna to remove rRNA from metatranscriptomic clean reads. The attached file is the trace. Can you help solve this problem?
Thanks a lot.
[trace.txt](https://github.com/biocore/sortmerna/files/8509878/trace.txt)

**Comment by biocodz** [comment]
Please, have a look at the [issue 323](https://github.com/biocore/sortmerna/issues/323). Possibly your problem is the same.

**Comment by daisyzhangsysu** [comment]
<img width="897" alt="1650378270(1)" src="https://user-images.githubusercontent.com/51351844/164026512-706eaf88-d27c-4429-81c5-8f08aafa9f7c.png">

**Comment by biocodz** [comment]
`ls -l` please

**Comment by biocodz** [comment]
The splitting failed somewhere at the end of the second file when it was almost done. Your split files look OK i.e. all are there and all about the same size. 
Your trace last entry:
```
...
[next:322] EOF FWD reached. Total reads: 85785005
[next:322] EOF REV reached. Total reads: 85785005  <- this is missing i.e. the REV didn't finish
```
Also there is no `./HMROV5-S5-mRNA/readb/readfeed` file in the list, meaning the split descriptor was not created.

This situation could be quite possibly caused by the directory limits.

**Comment by daisyzhangsysu** [comment]
So how do I solve the directory limit? Thanks

**Comment by biocodz** [comment]
You would need to talk to your system administrator who is responsible for allocating the hardware resources.
The commands useful for checking limits: `ulimit`, `du`, `df`

**Comment by jackieway** [comment]
Hello, I am also trying to use sortmerna to remove rRNA from metatranscriptome data. I have paired end reads from RNA-seq, and the adapters and low quality bases have been trimmed using Cutadapt on Galaxy (I ran Cutadapt on Galaxy but am using sortmerna locally on my computer, the trimmed files were downloaded from Galaxy and are in fastq.gz format). 

I'm using sortmerna version 4.3.6, and am having the same issue as above, with a segmentation fault during splitting. I have no readfeed file in /readb, and my trace is attached here. 
[sortmerna trace segmentation fault.txt](https://github.com/sortmerna/sortmerna/files/13956572/sortmerna.trace.segmentation.fault.txt)

I checked my directory limits and don't seem to be hitting any sort of limit, is there anything else that could be causing this issue?

**Comment by biocodz** [comment]
Please, create a separate issue for your problem. You can reference this issue if you think it is similar.
Your trace shows total count of reads 223725627 i.e. uneven number, which is not normal. Not sure if it's a problem with the input files or the program.
Two threads for 200M reads is too low. I'd use at least 8.
The segmentation fault is very likely due the resource allocation.  You can test with a smaller number of reads to ensure the program works.
Not knowing your setup and without the access to your system it's hard to troubleshoot. Sysadmin would be helpful.
