### ISSUE TITLE
understanding output results 

### ISSUE THREAD

**Issue by NickJeff13** [biocore/sortmerna#327]
Hello, 
I am trying to assemble a transcriptome for a crab species using a variety of tissue types. The output of my sortmerna log file per tissue shows very few reads passing the e-value threshold however (1-3%); does this mean my reads are all contaminated, or did I use a parameter incorrectly? Below is my command and the output from the log file. Thank you in advance for any help. 

```
 Command:
    sortmerna --ref /home/mcrg/sortmerna-master/data/rRNA_databases/silva-bac-16s-id90.fasta --ref /home/mcrg/sortmerna-master/data/rRNA_databases/silva-arc-16s-id95.fasta --ref /home/mcrg/sortmerna-master/data/rRNA_databases/silva-bac-23s-id98.fasta --reads Leg/NS.1265.002.NEBNext_dual_i7_D12---NEBNext_dual_i5_D12.SC_RNA_Leg_R1.fastq.gz --reads Leg/NS.1265.002.NEBNext_dual_i7_D12---NEBNext_dual_i5_D12.SC_RNA_Leg_R2.fastq.gz -workdir Leg/sortmerna_results/ 

 Process pid = 

 Parameters summary: 
    Reference file: /home/mcrg/sortmerna-master/data/rRNA_databases/silva-bac-16s-id90.fasta
        Seed length = 18
        Pass 1 = 18, Pass 2 = 9, Pass 3 = 3
        Gumbel lambda = 0.602725
        Gumbel K = 0.329559
        Minimal SW score based on E-value = 65
    Reference file: /home/mcrg/sortmerna-master/data/rRNA_databases/silva-arc-16s-id95.fasta
        Seed length = 18
        Pass 1 = 18, Pass 2 = 9, Pass 3 = 3
        Gumbel lambda = 0.596286
        Gumbel K = 0.322254
        Minimal SW score based on E-value = 63
    Reference file: /home/mcrg/sortmerna-master/data/rRNA_databases/silva-bac-23s-id98.fasta
        Seed length = 18
        Pass 1 = 18, Pass 2 = 9, Pass 3 = 3
        Gumbel lambda = 0.602436
        Gumbel K = 0.335011
        Minimal SW score based on E-value = 64
    Number of seeds = 2
    Edges = 4
    SW match = 2
    SW mismatch = -3
    SW gap open penalty = 5
    SW gap extend penalty = 2
    SW ambiguous nucleotide = -3
    SQ tags are not output
    Number of alignment processing threads = 2
    Reads file: Leg/NS.1265.002.NEBNext_dual_i7_D12---NEBNext_dual_i5_D12.SC_RNA_Leg_R1.fastq.gz
    Reads file: Leg/NS.1265.002.NEBNext_dual_i7_D12---NEBNext_dual_i5_D12.SC_RNA_Leg_R2.fastq.gz
    Total reads = 278664876

 Results:
    Total reads passing E-value threshold = 6805787 (2.44)
    Total reads failing E-value threshold = 271859089 (97.56)
    Minimum read length = 101
    Maximum read length = 101
    Mean read length    = 101

 Coverage by database:
    /home/mcrg/sortmerna-master/data/rRNA_databases/silva-bac-16s-id90.fasta		0.33
    /home/mcrg/sortmerna-master/data/rRNA_databases/silva-arc-16s-id95.fasta		0.08
    /home/mcrg/sortmerna-master/data/rRNA_databases/silva-bac-23s-id98.fasta		2.04
```

**Comment by ekopylova** [comment]
Hello @NickJeff13 ,

Was your data rRNA depleted (comparison of various rRNA depletion methods [here](https://www.nature.com/articles/s41598-022-09710-y)) ? 1-5% of detected rRNA is normal in rRNA depleted data. To confirm, you can run a subset of the non-rRNA reads (the 97.56% that didn't match to any rRNA database) against [Blast nr](https://blast.ncbi.nlm.nih.gov/Blast.cgi?PROGRAM=blastn&BLAST_SPEC=GeoBlast&PAGE_TYPE=BlastSearch) and see what those matches are (I suppose there should be many mRNA hits).

You can also try using the latest [SMR version](https://github.com/biocore/sortmerna/releases/tag/v4.3.4) and/or new [rRNA databases](https://github.com/biocore/sortmerna/releases/download/v4.3.4/database.tar.gz) to see if number of hits improves (though I wouldn't expect the % to rise significantly beyond 2.5%, only the quality of the matches).

Jenya

**Comment by ekopylova** [comment]
Hello @NickJeff13 
This is correct, reads passing the e-value threshold are those that aligned to the rRNA databases, while the rest of the data is non-rRNA (theoretically mRNA in transcriptomics data).
Best,
Jenya
