### ISSUE TITLE
SortMeRNA 4.3.4 Hangging at flag parsing and index building

### ISSUE THREAD

**Issue by EdgarLW** [biocore/sortmerna#331]
Hello everyone, I'm trying to run SortMeRNA on a Nextflow pipeline using docker containers from Quay.io and singularity, but the process hangs at flag parsing.
I'm not sure if this is a duplicate of another issue, but I cannot get it to work and found no help.

The whole process should be 20M reads per library (around 6GB each), paired-end, 18 total samples.
Since I can't get it to work I've been testing it on only one library and rRNA fasta.
Here's the nextflow script calling SortMeRNA:

#!/usr/bin/env/nextflow

nextflow.enable.dsl = 2

process SORTMERNA {

	container "docker://quay.io/biocontainers/sortmerna:4.3.4--h9ee0642_0"

	input:
		path( rRNA )
		path( reads )

	output:
		stdout

	script:
	"""
	sortmerna -ref ${rRNA}\
	-reads ${reads}\
	-fastx -other nonRNA
	"""
}

And here's the respective log:

[process:1376] === Options processing starts ... ===
Found value: sortmerna
Found flag: -ref
Found value: SILVA_138.1_SSURef_NR99.fasta of previous flag: -ref
Found flag: -reads
Found value: leave1_rd_1.fq of previous flag: -reads
Found flag: -fastx
Previous flag: -fastx is Boolean. Setting to True
Found flag: -other
Found value: nonRNA of previous flag: -other

Thinking my script could be causing errors I've also tried to download it locally, but no luck either, this time at index building:
`sortmerna --ref files/rRNA/SILVA_138.1_SSURef_NR99.fasta --reads files/reads/unripe3_rd_1.fq --fastx --other`

log output:

[process:1376] === Options processing starts ... ===
Found value: sortmerna
Found flag: --ref
Found value: files/rRNA/SILVA_138.1_SSURef_NR99.fasta of previous flag: --ref
Found flag: --reads
Found value: files/reads/unripe3_rd_1.fq of previous flag: --reads
Found flag: --fastx
Previous flag: --fastx is Boolean. Setting to True
Found flag: --other
[process:1460] Processing option: fastx with value: 
[process:1460] Processing option: other with value: 
[opt_other:267] other was specified without argument. Will use default Directory and Prefix for the non-aligned output.
[process:1460] Processing option: reads with value: files/reads/unripe3_rd_1.fq
[opt_reads:97] Processing reads file [1] out of total [1] files
[process:1460] Processing option: ref with value: files/rRNA/SILVA_138.1_SSURef_NR99.fasta
[opt_ref:157] Processing reference [1] out of total [1] references
[opt_ref:205] File "/home/andreiat/Desktop/EDGAR/Nextflow/files/rRNA/SILVA_138.1_SSURef_NR99.fasta" exists and is readable
[process:1480] === Options processing done ===
[process:1481] Alignment type: [best:1 num_alignments:1 min_lis:2 seeds:2]
[validate_kvdbdir:1221] 'workdir' option was not provided. Using USERDIR to set the working directory: ""
[validate_kvdbdir:1227] Key-value DB location "/home/andreiat/sortmerna/run/kvdb"
[validate_idxdir:1193] Using index directory: "/home/andreiat/sortmerna/run/idx"
[validate_idxdir:1209] IDX directory: "/home/andreiat/sortmerna/run/idx" exists and is not empty
[validate_readb_dir:1285] Using split reads directory : "/home/andreiat/sortmerna/run/readb"
[validate_readb_dir:1298] split reads directory : "/home/andreiat/sortmerna/run/readb" exists and is empty
[main:62] Running command:
sortmerna --ref files/rRNA/SILVA_138.1_SSURef_NR99.fasta --reads files/reads/unripe3_rd_1.fq --fastx --other 
[build_index:1127] ==== Index building started ====
[build_index:1190] Begin indexing file files/rRNA/SILVA_138.1_SSURef_NR99.fasta of size: 821793017 under index name /home/andreiat/sortmerna/run/idx/14846614615749508872

Thanks in advance!

**Comment by biocodz** [comment]
It's not possible to say what's wrong from the info provided. I would start with running the command without the container first to get a handle on the program behaviour. Then I would try the same from within the container but issuing the command manually i.e. setup the container so that the binaries and the reads/references are available inside the container. Container or not, there are should be no difference though.
The indexing might take awhile (e.g. half an hour) depending on the system resources, and the reference file size.

**Comment by EdgarLW** [comment]
Both strategies are working, thank you for the heads up.

Unfortunately, it seems that Nextflow is the problem but I've had no luck asking the community, has anyone reported a similar issue with pipeline managers and SortMeRNA?

**Comment by ppericard** [comment]
Hi @EdgarLW,
SortMeRNA 4.3.4 is currently integrated in the lastest version of the nf-core/rna-seq pipeline (https://nf-co.re/rnaseq/) and it seems it works well there. Maybe you can have a look at how they did it, and have a chat with the nf-core developers.
Cheers,
Pierre
