### ISSUE TITLE
Removal workdir

### ISSUE THREAD

**Issue by MichWeb75** [biocore/sortmerna#332]
I am wondering why sortemerna does not remove the files in working directory ? I run the following command :
```
    sortmerna -a 16 -ref silva-bac-16s-id90.fasta -reads input.fastq\
     -aligned input.ribosomes -other input.depleted -workdir /home/test/workdir -fastx -v
```
This would leave a folder called /home/test/workdir/input, which I manually delete after the call finished. How to require the programme to delete all temp files ?

SortMeRNA version 4.3.4

**Comment by biocodz** [comment]
There is no option to auto-delete the work directory. It may contain important files/data, so left to the user to handle.

**Comment by MichWeb75** [comment]
Thanks for the rapid answer! 
The workdir contains  according to manual :

* kvdb (key-value datastore for alignment results), 
* idx       index database
* out      output files like aligned.blast

Out is a directory of result files, but kvdb and idx are more temporary files ? Are they needed for consecutive tasks ?

**Comment by biocodz** [comment]
`idx` can be reused ( see `--index` option)
`kvdb` can be re-used for generating the output (see `--task` option). It also will be reusable in the next major release allowing for re-launching interrupted runs.
