### ISSUE TITLE
Is sortmerna supposed to give two output files with paired reads?

### ISSUE THREAD

**Issue by d-cjordan123** [biocore/sortmerna#334]
I am really new to this so forgive me if this is a stupid question. I am inputting two paired reads of RNA seq files into sortmerna, and do not understand why the outpout in the "out" directory is one file "aligned.blast.gz". I want two output fasta or fastq files that are for each paired read that I submitted. What am I doing wrong? Code is below. Please note that this is part of a for loop in which R1, R2, and i are specified (this part works fine)

sortmerna --ref /uoa/home/user/Software/sortmerna/sortmerna-2.1b/rRNA_databases/silva-euk-18s-id95.fasta --reads ${R1} --reads ${R2} --userdir /uoa/home/user/raw_data/C_fornicata/sortmerna_output/smr2/${i}

**Comment by biocodz** [comment]
can you provide the [trace](https://github.com/biocore/sortmerna#execution-trace) ?

**Comment by biocodz** [comment]
Everything looks OK. What's in the `out/aligned.log`?

**Comment by d-cjordan123** [comment]
This is what was in the out/aligned.log. I just don't understand why my forward and reverse reads are being combined into one file when I need them to be separate. Thank you!

Command:

    sortmerna --ref /uoa/home/r01dj21/Software/sortmerna/sortmerna-2.1b/rRNA_dat

abases/silva-euk-18s-id95.fasta --reads 0051_R1_val_1.fq.gz --reads 0051_R2_val_

2.fq.gz --fastx --paired_in --workdir /uoa/home/r01dj21/raw_data/C_fornicata/sor

tmerna_output/smr4 

 Process pid = 

Parameters summary: 

    Reference file: /uoa/home/r01dj21/Software/sortmerna/sortmerna-2.1b/rRNA_dat

abases/silva-euk-18s-id95.fasta

        Seed length = 18

        Pass 1 = 18, Pass 2 = 9, Pass 3 = 3

        Gumbel lambda = 0.612551

        Gumbel K = 0.33981

        Minimal SW score based on E-value = 59

    Number of seeds = 2

    Edges = 4

    SW match = 2

    SW mismatch = -3

    SW gap open penalty = 5

    SW gap extend penalty = 2

    SW ambiguous nucleotide = -3

    qSQ tags are not output

    Number of alignment processing threads = 2

    Reads file: 0051_R1_val_1.fq.gz

    Reads file: 0051_R2_val_2.fq.gz

    Total reads = 11759038

 Results:

    Total reads passing E-value threshold = 1210563 (10.29)

    Total reads failing E-value threshold = 10548475 (89.71)

    Minimum read length = 150

    Maximum read length = 70

    Mean read length    = 130

 Coverage by database:

    /uoa/home/r01dj21/Software/sortmerna/sortmerna-2.1b/rRNA_databases/silva-euk-18s-id95.fasta         10.29

Fri Jul  8 17:45:05 2022

**Comment by biocodz** [comment]
`-out2`

**Comment by biocodz** [comment]
`-other`. Have you looked into [issue 333](https://github.com/biocore/sortmerna/issues/333) last message as advised above?
