### ISSUE TITLE
Any advice on using sortmerna with assembled transcripts

### ISSUE THREAD

**Issue by kafker** [biocore/sortmerna#337]
Hello there,

Since I have already assembled my metatranscriptome with Trinity I was wondering if sortmerna can be used to detect rRNA transcripts instead of rRNA reads.

Thank you

edit: I just had a look at the description which says that sortmerna also accepts PacBio data. So, I guess it safe to use sortmerna to detect rRNA transcripts

**Comment by biocodz** [comment]
Your guess seems to be correct.
