### ISSUE TITLE
suboptimal alignment when matching the end of the reference (in blast output)

### ISSUE THREAD

**Issue by larssnip** [biocore/sortmerna#338]
It looks to me that SortMeRNA consistently output wrong coordinates in the blast format when the alignment runs across the end of the subject sequence (rRNA).

Assume we have a read of length 150, where the first 100 bases matches exactly the last 100 bases of an rRNA. This rRNA has length 1000 bases (simple numbers). Then we would expect the coordinates output to be qstart = 1, qend = 100, sstart = 901, send = 1000.

In all cases I have checked they are instead qstart = 1, qend = 92, sstart = 901, send = 992, i.e. there are exactly 8 bases missing at the end-part. In a rather large result-table, I added the length of all the subject sequences (rRNA's) as another column. I then found no cases (zero!) where the send is equal to the length of the subject, but plenty of cases where it is exactly 8 smaller!

This looks to me like a bug, some 8-mer match that has not been counted? I am looking especially for matches that runs across each end of the subject, which is how I discovered this (compared SortMeRNa to BLAST).

**Comment by biocodz** [comment]
What version of sortmerna do you use?

**Comment by larssnip** [comment]
SortMeRNA version 4.3.4

A singularity container from singularity.galaxyproject.org

**Comment by biocodz** [comment]
I'm looking at the results of the [test 18](https://github.com/biocore/sortmerna/blob/master/scripts/test.jinja#L1259). Here are a few random records from the blast report:
```
DRR121111.1.1   EU602318        78.9    127     22      5       1       127     28      151     7.32e-17        97
...
DRR121111.10.2  EU602318        71      242     48      27      60      301     109     357     4.83e-22        114
...
DRR121111.17.2  EU602318        69.9    246     55      23      56      301     109     357     1.88e-19        105
```
Here is a table of alignment length for the same alignments:
```
align_len   read_len        ref_len          mismatches  gaps
-------------------------------------------------------------
127         127 (127-1+1)   124 (151-28+1)       22        1
242         242             249                  48       27
246         246             249                  55       23
```
And here are the same alignments shown pairwise `-blast 0`:
```
Query ID: DRR121111.1.1
Score: 111 bits (97)    Expect: 7.32e-17        strand: +

Target:       28    GACGAACGCTGGCGGCGTGCCTAATACATGCAAGTCGAGCGCGGGAAGCAAG-CGGATC-    85
                    ||*|||||||||||||*|||||||*|||||||||||||*||*||*****|*| ||||*|
Query:         1    GATGAACGCTGGCGGCATGCCTAACACATGCAAGTCGAACGGGGTTTATATGACGGAACT    60

Target:       86    CTTCGGGGGTGAAGCT-TGTGGAACGAGCGGCGGACGGGTGAGTAACACGTGGGCAACCT    144
                    ||*|||*|| ||||*| |*|**|*|*||*||||||||||||||||||*||||||||||||
Query:        61    CTCCGGAGG-GAAGATATATAAACCTAGTGGCGGACGGGTGAGTAACGCGTGGGCAACCT    119

Target:      145    G-CCTGTA    151
                    | ||||||
Query:       120    GCCCTGTA    127
```
```
Sequence ID: EU602318
Query ID: DRR121111.10.2
Score: 131 bits (114)   Expect: 4.83e-22        strand: -

Target:      109    CGAGCGGCGGACGGGTGAGTAACACGTGGGCAACCTG-CCTGTAAGACC--GGAATAACC    165
                    ||||*||||||**||||||||||*||||*|||||||| ||||   ||||  ||*|||||*
Query:        60    CGAGTGGCGGAGTGGTGAGTAACGCGTGTGCAACCTGCCCTG---GACCGGGGGATAACA    116

Target:      166    CCGGGAAACCGGGGCTAATGCCGNGTAACACCTACCTT--CACCTG--A-AGGAAGGTTA    220
                    *|**||||**|**||||||*|||**||| *|||*|*||  |||*||  | ||*|*||  |
Query:       117    GCCAGAAATGGCTGCTAATACCGCATAA-GCCTGCTTTGCCACATGGCACAGCAGGG--A    173

Target:      221    AAAGATGGCTTCTCGCTATCACTTACA-GATGGGCCCGCGGC-GATTAGCTAGTTGGTGA    278
                    |||     |  |*||*|    **|||| ||||||||||||*| ||||||*|||||||***
Query:       174    AAA-----C--CACGGT----GGTACAGGATGGGCCCGCGTCTGATTAGTTAGTTGGCAG    222

Target:      279    TTTAATAGCTCACCAAGGCGACGATGCGTAGCCGACCTGAGAGGGTGATCGGCCACACTG    338
                    **|||**||**||||||*|*|||||**|||||||*|*||||||*|||**||||||||*||
Query:       223    GGTAACGGCCTACCAAGACAACGATCAGTAGCCGGCTTGAGAGAGTGGACGGCCACATTG    282

Target:      339    GGACTGAGACACGGCCCAG    357
                    |||||||||||||||||||
Query:       283    GGACTGAGACACGGCCCAG    301
```
```
Query ID: DRR121111.17.2
Score: 121 bits (105)   Expect: 1.88e-19        strand: -

Target:      109    CGAGCGGCGGACGGGTGAGTAACACGTGGGCAACCTGCCTGTAAGACCGGAATAACCCCG    168
                    |||*|||||*|||||||||||||||||**||||||||||*||*|*|**||*||||  *||
Query:        56    CGACCGGCGCACGGGTGAGTAACACGTATGCAACCTGCCCGTCACAGGGGGATAA--TCG    113

Target:      169    G--GAAA--CCGGGGCTAATGCCGNGT---AACACCTACCTTCACCTGAAGGAAGGTTAA    221
                    |  ||||  ||  |*|||||*|||*||   ||||||*|****||*||***||  *|||*|
Query:       114    GAAGAAATTCC--GTCTAATACCGCGTGACAACACCGAGAGGCATCTTTTGG--TGTTCA    169

Target:      222    AAGATGGC--TTCTCGCTATCACTTACAGATGGGCCCGCGGCG-ATTAGCTAGTTGGTGA    278
                    |||***||  ||| ||      *|*||*|||||||**|||*|| ||||||||||*||*|*
Query:       170    AAGGGAGCAATTC-CG------GTGACGGATGGGCATGCGTCGCATTAGCTAGTCGGCGG    222

Target:      279    TTTAATAGCTCACCAAGGCGACGATGCGTAGCCGACCTGAGAGGGTGATCGGCCACACTG    338
                    **|||**||*||||*||||||||||||||||**|**||||||||**|**|**||||||||
Query:       223    GGTAACGGCCCACCGAGGCGACGATGCGTAGGGGTTCTGAGAGGAAGGCCCCCCACACTG    282

Target:      339    GGACTGAGACACGGCCCAG    357
                    |*||||||||||||*||||
Query:       283    GTACTGAGACACGGACCAG    301
```
Can you see any discrepancies?

**Comment by larssnip** [comment]
No it looks fine, but do these alignments run across the end of the subject sequence? In my results the coordinates looks correct in all cases, except for those where the alignment is configured as in the example i mentioned in my first comment, i.e. it onvolves a part of the query (read) and the end of the subject (rRNA). It is really strange. I should also mention that I only considered perfect alignments, i.e. 100% identity (no mismatches or gapopens). I will see if I can make small example to reproduce it.

**Comment by larssnip** [comment]
OK, here is an example:

The subject sequence is 404 bases long.

There are 3 query sequences, all 150 bases long: 
a) The last 100 bases of read1 matches the first 100 of the subject
b) All 150 bases of read2 matches inside the subject
c) The first 100 bases of read3 matches the last 100 bases of the subject. This is the configuration that creates the strange result

Here is the out put in aligned.blast (using --blast '1 cigar qstrand'):
read1	subject1	100	100	0	0	51	150	1	100	2.65e-47	172	50S100M	+
read2	subject1	100	150	0	0	1	150	101	250	5.81e-73	257	150M	+
read3	subject1	100	92	0	0	1	92	305	396	3.38e-43	158	92M58S	+

The two first rows seem correct. The read1 alignment covers positions 51-150 on the query and 1-100 on the subject. The read1 alignment covers 1-150 on the query and 101-250 on the subject. BUT, the read3 alignment covers 1-92 on the query and 305-396 on the subject. This should have been 1-100 and 305-404.

Here are the sequences:
The file subject.fasta contains
>subject1
TGGGGAATATTGCACAATGGAGGAAACTCTGATGCAGCAACGCCGCGTGGAGGATGACGCATTTCGGTGTGTAAACTCCTTTTATATGGGAAGATAATGACGGTACCATATGAATAAGCACCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGGTGCAAGCGTTACTCGGAATCACTGGGCGTAAAGCGCGCGCAGGCGGCTATTTAAGTTGGATGTGAAAGCCTACGGCTCAACCGTAGAACTGCATCCAAAACTATTTAGCTAGAGTGTGGGAGAGGAAGATGGAATTAGTTGTGTAGGGGTAAAATCCGTAGAGATAACTAGGAATACCAAAAGCGAAGGCAATCTTCTGGAACACTACTGACGCTGAGGCGCGAAAGCGTGGGGAGCAAACAGG

The file query.fasta contains:
>read1
CAATGGTTATCCAGCCAAAAGGCGCTTGATAGCACAGAGATACGCCAGAGTGGGGAATATTGCACAATGGAGGAAACTCTGATGCAGCAACGCCGCGTGGAGGATGACGCATTTCGGTGTGTAAACTCCTTTTATATGGGAAGATAATGA
>read2
CGGTACCATATGAATAAGCACCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGGTGCAAGCGTTACTCGGAATCACTGGGCGTAAAGCGCGCGCAGGCGGCTATTTAAGTTGGATGTGAAAGCCTACGGCTCAACCGTAGAACT
>read3
AGGGGTAAAATCCGTAGAGATAACTAGGAATACCAAAAGCGAAGGCAATCTTCTGGAACACTACTGACGCTGAGGCGCGAAAGCGTGGGGAGCAAACAGGCAATGGTTATCCAGCCAAAAGGCGCTTGATAGCACAGAGATACGCCAGAG

**Comment by biocodz** [comment]
Can you try `-blast 0` to see the pairwise alignment?

**Comment by larssnip** [comment]
OK, here is the output for read3:

Sequence ID: subject1
Query ID: read3
Score: 184 bits (158)	Expect: 3.38e-43	strand: +

Target:      305    AGGGGTAAAATCCGTAGAGATAACTAGGAATACCAAAAGCGAAGGCAATCTTCTGGAACA    364
                    ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Query:         1    AGGGGTAAAATCCGTAGAGATAACTAGGAATACCAAAAGCGAAGGCAATCTTCTGGAACA    60

Target:      365    CTACTGACGCTGAGGCGCGAAAGCGTGGGGAG    396
                    ||||||||||||||||||||||||||||||||
Query:        61    CTACTGACGCTGAGGCGCGAAAGCGTGGGGAG    92

**Comment by larssnip** [comment]
The next 8 bases in the Query are:  CAAACAGG
And the last 8 bases of the subject are: CAAACAGG

These are not part of the alignment even if they are identical.

**Comment by biocodz** [comment]
So, it looks like the program stops at a sub-optimal alignment.
I'll investigate and get back with the results.

**Comment by larssnip** [comment]
Yes, for this particular situation, and it is always exactly 8 bases short.

**Comment by biocodz** [comment]
This is not a bug after all.

** It is apparently by design to accelerate the search. The algorithm doesn't necessarily search for exact matches **

The algorithm stops refining the search after it finds an alignment that passes a certain threshold value (e-value).
I played with different e-values ( `-e` option), but even setting it to a very low value like `1e-15` still stops the search before the exact match is found.

The algorithm proceeds in 3 stages:
- k-mer mapping
- LIS calculation (Longest Increasing sub-Sequence)
- SW calculation (Smith-Waterman score)

K-mer mapping uses a preset value (18nt by default - `-L` option), and selects the k-mers to map by using a 3-tuple of `shift values` (`-passes` option). With the smallest shift of 3 (default) only about 1/3 max of all possible k-mers are checked. But often the algorithm doesn't even go to a smaller shift if it finds a satisfactory alignment using the largest shift i.e in case of 18nt only ~1/18 of all possible k-mers are checked (your case).

Hopefully my explanation makes sense. Let me know otherwise :-)

**Comment by larssnip** [comment]
OK, thanks for this clarification. It means the alignment I get with sortmerna should not be thought of as the best possible, only "good enough" (small e-value).

**Comment by biocodz** [comment]
That depends on  `the best` interpretation. I would define it as an approximate match vs the exact match.

**Comment by larssnip** [comment]
Hmm, if you do a SW I think "best possible" is bound to be largest possible score. I cannot see how you can leave out exact-matching parts of the alignment and still think of it as the anything but less than best possible?

**Comment by biocodz** [comment]
When a read is aligned against a set of sequences then the alignment with the highest SW **found** would still be `the best`, even if that SW is not `the best possible`. I think that was the original interpretation.

**Comment by biocodz** [comment]
This needs more clarification. I'll keep digging...

**Comment by larssnip** [comment]
Yes, I agree with your previous statement. I think that for many purposes the "good enough" criterion is just that, good enough. It will indicate if a read is overlapping some 16S. But, for my purpose I want to have the exact part of the read that overlaps, and then I would not be satisfied by leaving out an exact matching part...

**Comment by ekopylova** [comment]
Hello! The algorithm for SortMeRNA was not optimized to report the highest scoring alignment, only an alignment that passes the threshold for classifying the sequence as rRNA with very high confidence (99.8% sensitivity and specificity). SortMeRNA works rapidly using a small rRNA database (SMR v4.3 default db has ~33064 bacterial rRNA) to accurately classify rRNA sequences (with similarity down to 80%) in large sequencing projects, but will not be the best performing tool in terms of speed/memory for delivering the highest scoring alignments (such as blastn, minimap, bowtie2, etc.). The indexing algorithm in SortMeRNA does not store the k-mer positions of all identical k-mers in the rRNA database (due to rapid increase in RAM requirements and alignment), which would be needed to identify all possible alignment positions (for LIS calculation / SW alignment), and thus the highest scoring alignment cannot be guaranteed (only a very good one).
