### ISSUE TITLE
How to run SortMeRNA (v4.3.4) with multiple reference files correctly?

### ISSUE THREAD

**Issue by banderoz** [biocore/sortmerna#339]
We have been executing SortMeRNA **v2.1** with multiple reference files this way:
`sortmerna --ref /tmp/sortmerna/rRNA_databases/rfam-5.8s-database-id98.fasta,/tmp/sortmerna/index/rfam-5.8s-db:/tmp/sortmerna/rRNA_databases/silva-arc-23s-id98.fasta,/tmp/sortmerna/silva-arc-23s-db -a 8 --fastx --log --reads /tmp/unpaired.fastq --aligned /tmp/unp.rRNAs --other /tmp/unp.no_rRNAs`
and it works perfectly.

Now we'd like to upgrade SortMeRNA to **v4.3.4** (the latest stable version), but we run into some issues while try executing the newest version.

This is a command I try executing in **v4.3.4**:
`sortmerna --threads 2 --fastx --ref /tmp/sortmerna/rRNA_databases/rfam-5.8s-database-id98.fasta,/tmp/sortmerna/index/rfam-5.8s-db --ref /tmp/sortmerna/rRNA_databases/silva-arc-23s-id98.fasta,/tmp/sortmerna/index/silva-arc-23s-db --reads /tmp/unpaired.fastq --aligned /tmp/unp.rRNAs --other /tmp/unp.no_rRNAs`
but I get the following error:
`ERROR: The file /tmp/sortmerna/rRNA_databases/rfam-5.8s-database-id98.fasta,/tmp/sortmerna/index/rfam-5.8s-db is not an existing/valid absolute or relative path`

This is a structure of the reference files:
<img width="305" alt="image" src="https://user-images.githubusercontent.com/48513784/183921919-9bd543c0-6f14-42ec-b38f-a9c9f59be20c.png">

Could you please clarify, how to execute **v4.3.4** correctly? Thank you.

BR,
Zulfat

**Comment by biocodz** [comment]
`-ref` takes a path to the reference file.
```
sortmerna -h
    --ref             PATH        Required  Reference file (FASTA) absolute or relative path.

       Use multliple times, once per a reference file
```
Many examples can be found in [tests](https://github.com/biocore/sortmerna/blob/master/scripts/test.jinja) e.g. [here](https://github.com/biocore/sortmerna/blob/master/scripts/test.jinja#L441)

**Comment by banderoz** [comment]
@biocodz thank you for the provided examples!

So no longer needed to pass paths to index files?

**Comment by biocodz** [comment]
You can optionally specify the index directory location
```
--idx-dir         PATH        Optional  Directory for storing Reference index.      WORKDIR/idx
```
Overall the indexing has changed a bit since v2.1 (along with many other changes). Relevant options:
```
--workdir
--idx-dir
--index
```

**Comment by banderoz** [comment]
@biocodz thanks for your help! Looks like it works as expected
