### ISSUE TITLE
rRNA filtering Simple

### ISSUE THREAD

**Issue by SergeyBaikal** [biocore/sortmerna#342]
Dear developers, Could you clarify please. There is no manual, I do not understand how to run the program.

I have a silva reference file for the large and small subunit.
What am I doing?

`./sortmerna --ref Silva_LSU_SSU.fasta`  # This, as I understand it, does indexing and needs to be done only once.

If I want to separate sequences into "Clean" and "containing rRNA" I use this command. I just change fastq files.

`./sortmerna -index 0 -reads ./My_data/13_1.fq.gz -reads ./My_data/13_2.fq.gz --aligned ./My_results/With_rRNA --other ./My_results/Clean --fastx --threads 8 -v --task 4 --workdir ./Index --paired_out --out2`

**Comment by biocodz** [comment]
There are multiple samples in [test.jinja](https://github.com/biocore/sortmerna/blob/master/scripts/test.jinja). The file is just a plain text, so should be easy to understand.
The [issue 333](https://github.com/biocore/sortmerna/issues/333) and [issue 339](https://github.com/biocore/sortmerna/issues/339) provide some instructions.
Use `sortmerna -h` for options description.
