### ISSUE TITLE
verifying my command line

### ISSUE THREAD

**Issue by sumitra20** [biocore/sortmerna#343]
Hi,

I am very new to bioinformatic analysis and i came across this tool recently. I have a few RNA sequences and i would like to filter out all the rRNAs and small rRNA reads to only retain the mRNA tags. I merged my forward and reverse reads before running sortmerna2.0. Below is the command line that i've executed, i was able to get my output files without any errors. However, im not very sure if I've been running it correctly as my output file from '--other' (which i assume is the non rRNA/ mRNA tags) is too huge (10-12gb). Did really appreciate it if someone could correct me if im going wrong somewhere.

Thank you

`sortmerna -ref ./rRNA_databases/silva-bac-16s-id90.fasta -ref ./rRNA_databases/silva-bac-23s-id98.fasta -ref ./rRNA_databases/silva-arc-16s-id95.fasta -ref ./rRNA_databases/silva-arc-23s-id98.fasta -ref ./rRNA_databases/silva-euk-18s-id95.fasta -ref ./rRNA_databases/silva-euk-28s-id98.fasta -ref ./rRNA_databases/rfam-5s-database-id98.fasta -ref ./rRNA_databases/rfam-5.8s-database-id98.fasta --reads ./R33P3_L_sortme_merge.fq -sam -num_alignments 1 -fastx -aligned ./R33P3_L_sortme_rRNA -other ./R33P3_L_sortme_non_rRNA fastq -v -m 32219 -threads 16`

**Comment by sumitra20** [comment]
Hi,
I've tried running sortmerna for several time using the output i obtained from the command i attached above, but this time using the latest version of sortmerna4.3.6 and using the 'smr_v4.3_default_db.fasta' database. 

**this was my first output using sortmerna 2.0** 
`sortmerna -ref ./rRNA_databases/silva-bac-16s-id90.fasta -ref ./rRNA_databases/silva-bac-23s-id98.fasta -ref ./rRNA_databases/silva-arc-16s-id95.fasta -ref ./rRNA_databases/silva-arc-23s-id98.fasta -ref ./rRNA_databases/silva-euk-18s-id95.fasta -ref ./rRNA_databases/silva-euk-28s-id98.fasta -ref ./rRNA_databases/rfam-5s-database-id98.fasta -ref ./rRNA_databases/rfam-5.8s-database-id98.fasta --reads ./R33P5_R_sortme_merge.fq -sam -num_alignments 1 -fastx -aligned ./R33P5_R_sortme_rRNA -other ./R33P5_R_sortme_non_rRNA fastq -v -m 32219 -threads 16 
`
 Results:
    Total reads passing E-value threshold = 2169678 (6.16)
    Total reads failing E-value threshold = 33046668 (93.84)
    Minimum read length = 150
    Maximum read length = 3
    Mean read length    = 135

 Coverage by database:
    ./rRNA_databases/silva-bac-16s-id90.fasta		0.36
    ./rRNA_databases/silva-bac-23s-id98.fasta		1.69
    ./rRNA_databases/silva-arc-16s-id95.fasta		0.04
    ./rRNA_databases/silva-arc-23s-id98.fasta		0.07
    ./rRNA_databases/silva-euk-18s-id95.fasta		0.30
    ./rRNA_databases/silva-euk-28s-id98.fasta		3.66
    ./rRNA_databases/rfam-5s-database-id98.fasta		0.04
    ./rRNA_databases/rfam-5.8s-database-id98.fasta		0.00

**output for the second round of sortmerna 4.3.6 (using the output i obtain from '--other')**

`/media/combio7/8TB_Backup/sumitra_130122/sortmerna-4.3.6-Linux/bin/sortmerna --ref ./database/smr_v4.3_default_db.fasta -index 0 --reads ./R33P5_R_sortme_non_rRNA.fq --paired -sam -num_alignments 1 -fastx -aligned ./R33P5_R_with_rrna_round2 --other ./R33P5_R_clean_round2 -v -m 32219 -threads 16 -workdir ./ `

Results:
    Total reads passing E-value threshold = 2664877 (8.06)
    Total reads failing E-value threshold = 30381791 (91.94)
    Minimum read length = 3
    Maximum read length = 150
    Mean read length    = 135

 Coverage by database:
    ./database/smr_v4.3_default_db.fasta		8.06


**and i also ran it the 3rd time** 

` /media/combio7/8TB_Backup/sumitra_130122/sortmerna-4.3.6-Linux/bin/sortmerna --ref ./database/smr_v4.3_default_db.fasta -index 0 --reads //media/combio7/8TB_Backup/sumitra_130122/sortmerna-4.3.6-Linux/bin/R33P5_R_clean_round2.fq.gz --paired -sam -num_alignments 1 -fastx -aligned ./R33P5_R_with_rrna_round3 --other ./R33P5_R_clean_round3 -v -m 32219 -threads 16 -workdir ./ `

 Results:
    Total reads passing E-value threshold = 32915 (0.11)
    Total reads failing E-value threshold = 30348876 (99.89)
    Minimum read length = 3
    Maximum read length = 150
    Mean read length    = 134

 Coverage by database:
    ./database/smr_v4.3_default_db.fasta		0.11


why do i keep getting different outputs?

**Comment by biocodz** [comment]
The command you use with sortmerna 2.0 doesn't look correct
What is the output of
```
which sortmerna      # e.g. ~/miniconda3/envs/smr21/bin/sortmerna
sortmerna --version  # e.g. SortMeRNA version 2.1b, 03/03/2016
```

**Comment by sumitra20** [comment]
Hi,
Thank you so much for the response. These are the outputs:

```
which sortmerna     
 # ~/home/combio7/anaconda3/bin/sortmerna

sortmerna --version 
 # SortMeRNA version 4.3.4
Build Date: Jul 21 2021
sortmerna_build_git_sha:@90cdf6ce459e9477c5d0de9a5daab025f49f3cc6@
sortmerna_build_git_date:@2021/07/21 11:56:36@
```

I also installed a version 2.0 separately to run the first command i posted,

```
which sortmerna      # ~./sortmerna
sortmerna --version  # SortMeRNA version 2.0, 29/11/2014
```

Maybe i should just stick to the current version 4.3? I hope the command line and the database i used for version 4.3 is correct

**Comment by biocodz** [comment]
I would recommend using v4.3.6. It fixed many bugs found in v4.3.4. And sure a lot has changed between 2.x and 4.x.
The difference in results when using different databases is no surprise.

**Comment by sumitra20** [comment]
Thank you, I shall use the v4.3.6 aft this.

**Comment by biocodz** [comment]
also check [test.jinja](https://github.com/biocore/sortmerna/blob/master/scripts/test.jinja) for many usage samples.
[issue 342](https://github.com/biocore/sortmerna/issues/342) has some usage info
