### ISSUE TITLE
how to get output separated into for and rev reads for downstream assembly using megahit

### ISSUE THREAD

**Issue by linneakh** [biocore/sortmerna#344]
Hi. I'm having trouble figuring out how to get my output of unaligned fastq files to be split into forward and reverse reads for downstream analysis using megahit. I am inputing my forward and reverse reads separately, and using the --paired-in option to ensure the paired reads stay together. In the old manual, there was an option to unmerge the reads as follows :
> bash ./unmerge-paired-reads.sh merged-reads.fastq forward-reads.fastq reverse-reads.fastq

However, I do not see this script included in the latest release. Is there a way to make my output automatically separated?

Here is my code for reference:
sortmerna -ref ~/silva-bac-16s-id90.fasta \
        -ref ~/silva-arc-16s-id95.fasta \
        -ref ~/silva-arc-23s-id98.fasta \
        -ref ~/silva-bac-23s-id98.fasta \
        -ref ~/silva-euk-18s-id95.fasta \
        -ref ~/silva-euk-28s-id98.fasta \
        -reads ${sample}_bbduck_1.fq.gz \
        -reads ${sample}_bbduck_2.fq.gz \
        -kvdb ${sample}/kvdb/ \
        --idx-dir idx/ \
        -readb ${sample}/readb/ \
        -aligned ${sample}/out/ \
        -other /${sample}/out/ \
        -fastx \
        --paired-in \
        -threads 28

Thanks for your help!

**Comment by biocodz** [comment]
option `-out2` separates R/F as can be seen in [test 20_1](https://github.com/biocore/sortmerna/blob/master/scripts/test.jinja#L1898). It outputs  [4 files](https://github.com/biocore/sortmerna/blob/master/scripts/test.jinja#L1936)

**Comment by linneakh** [comment]
Thanks!
