### ISSUE TITLE
SEG Faults with version 4.3.6

### ISSUE THREAD

**Issue by charlesdavid** [biocore/sortmerna#345]
Hello, I am finding that version 4.3.6 is not runnable due to seg faults. At first, I was using 32 threads and 4 processors, so dropped to one processor and only 8 threads. In both cases, about 50% of the jobs failed due to seg faults. Interestingly, I did not have these difficulties when running on paired end reads, only here with single end reads. In both cases the fast db was used. Note that the fastq files are not particularly large, all containing approx 10M seqs.

Here is the last command run for all files:

```
${SMRNA} \
       --ref ${SMRNA_DB} \
       --reads ${file} \
       --idx-dir ${OUT}/${NAME}/index \
       --workdir ${OUT}/${NAME} \
        --aligned ${rRNA}/${NAME}_rRNA \
        --other ${FILTERED}/${NAME}_filtered \
        --fastx 1 \
        --out2 0 \
        --num_alignments 1 \
        --no-best 1 \
        --paired_out 0 \
        --threads 8 \
        -m 8192 \
         --zip-out 0
```

SLURM provided 1 CPU with 32G mem per cpu.

Here is one err file:

/var/spool/slurmd/job484922/slurm_script: line 9: 32740 Segmentation fault      (core dumped) /powerplant/workspace/cflcyd/software/sortmerna-4.3.6-Linux/bin/sortmerna --ref /powerplant/workspace/cflcyd/software/sortmerna-4.3.6-Linux/smr_v4.3_fast_db.fasta --reads /workspace/cflcyd/git/Stealth_Apple_II/000.raw/data/AGRF_CAGRF220410433_HL7JTDRX2/SC3_HL7JTDRX2_CGTACAGGAA-AGAGAACCTA_L001_R1.fastq.gz --idx-dir /workspace/cflcyd/git/Stealth_Apple_II/002.smrna/SC3_HL7JTDRX2_CGTACAGGAA-AGAGAACCTA_L001/index --workdir /workspace/cflcyd/git/Stealth_Apple_II/002.smrna/SC3_HL7JTDRX2_CGTACAGGAA-AGAGAACCTA_L001 --aligned /workspace/cflcyd/git/Stealth_Apple_II/002.smrna/rRNA/SC3_HL7JTDRX2_CGTACAGGAA-AGAGAACCTA_L001_rRNA --other /workspace/cflcyd/git/Stealth_Apple_II/002.smrna/filtered/SC3_HL7JTDRX2_CGTACAGGAA-AGAGAACCTA_L001_filtered --fastx 1 --out2 0 --num_alignments 1 --no-best 1 --paired_out 0 --threads 8 -m 8192 --zip-out 0

And here is the corresponding out file:

[process:1393] === Options processing starts ... ===
Found value: /powerplant/workspace/cflcyd/software/sortmerna-4.3.6-Linux/bin/sortmerna
Found flag: --ref
Found value: /powerplant/workspace/cflcyd/software/sortmerna-4.3.6-Linux/smr_v4.3_fast_db.fasta of previous flag: --ref
Found flag: --reads
Found value: /workspace/cflcyd/git/Stealth_Apple_II/000.raw/data/AGRF_CAGRF220410433_HL7JTDRX2/SC3_HL7JTDRX2_CGTACAGGAA-AGAGAACCTA_L001_R1.fastq.gz of previous flag: --reads
Found flag: --idx-dir
Found value: /workspace/cflcyd/git/Stealth_Apple_II/002.smrna/SC3_HL7JTDRX2_CGTACAGGAA-AGAGAACCTA_L001/index of previous flag: --idx-dir
Found flag: --workdir
Found value: /workspace/cflcyd/git/Stealth_Apple_II/002.smrna/SC3_HL7JTDRX2_CGTACAGGAA-AGAGAACCTA_L001 of previous flag: --workdir
Found flag: --aligned
Found value: /workspace/cflcyd/git/Stealth_Apple_II/002.smrna/rRNA/SC3_HL7JTDRX2_CGTACAGGAA-AGAGAACCTA_L001_rRNA of previous flag: --aligned
Found flag: --other
Found value: /workspace/cflcyd/git/Stealth_Apple_II/002.smrna/filtered/SC3_HL7JTDRX2_CGTACAGGAA-AGAGAACCTA_L001_filtered of previous flag: --other
Found flag: --fastx
Found value: 1 of previous flag: --fastx
Found flag: --out2
Found value: 0 of previous flag: --out2
Found flag: --num_alignments
Found value: 1 of previous flag: --num_alignments
Found flag: --no-best
Found value: 1 of previous flag: --no-best
Found flag: --paired_out
Found value: 0 of previous flag: --paired_out
Found flag: --threads
Found value: 8 of previous flag: --threads
Found flag: -m
Found value: 8192 of previous flag: -m
Found flag: --zip-out
Found value: 0 of previous flag: --zip-out

**My confusion here is why are 50% of the jobs completing successfully?**

Please inform me if this can be corrected due to an error on my part, or if there is a flaw elsewhere.

Here are some additional information:

![Issue Index](https://user-images.githubusercontent.com/8854788/193728764-700c7a20-306e-47ea-9af4-e555fe34d690.JPG)
![Issue kvdb](https://user-images.githubusercontent.com/8854788/193728790-d88d07d3-ce2a-44fe-8c4d-2005af1a676b.JPG)
![Issue read db](https://user-images.githubusercontent.com/8854788/193728797-8027f66d-e34f-43e8-bf4f-6e508ce545ef.JPG)

[LOG.txt](https://github.com/biocore/sortmerna/files/9702567/LOG.txt)

**Comment by charlesdavid** [comment]
UPDATE: I ran the jobs again using only one thread and all completed with no errors. There appears to be a problem with multi-threading based on these results.

**Comment by biocodz** [comment]
Thanks for reporting this.
Could you try running using just a single VM instance other then using HPC facilities (to see if the problem persists)? Using Slurm on HPC adds to the setup complexity.
I didn't see segfaults through [the tests](https://github.com/biocore/sortmerna/blob/master/scripts/test.jinja) run on a standalone machine with up to 32 threads.
Also, the boolean options `fastx, out2, no-best, paired_out` don't take arguments
