### ISSUE TITLE
Use SortMeRNA with PR2 database?

### ISSUE THREAD

**Issue by whitnersyrena** [biocore/sortmerna#347]
Hi there, 

I am hoping to use the PR2 database with SortMeRNA instead of the standard SILVA builds, is there a way to do this? I do not see an option to use a custom database but I assume it is possible....

**Comment by biocodz** [comment]
Sortmerna can only take a set of Fasta files as references i.e. whatever reference set you use should be converted to the Fasta format by some means external to Sortmerna.

**Comment by whitnersyrena** [comment]
Hi there, 

Thank you for your response. 
I have my reference db in fasta format, will I need to create an index file as well. similar to the SILVA db? Or is just the .fasta file sufficient?
