### ISSUE TITLE
Multiple references into one output file

### ISSUE THREAD

**Issue by Adele2604** [biocore/sortmerna#351]
Hello,
I want to create a bash loop to analyze all my fastq.gz files like this:
Samples="/home/admit1/scratch/Test/Results/Trimmomatic"
Output="/home/admit1/scratch/Test/Results/SortMeRNA"

for sample in $Samples/*_R1_pe*
do
sample=${sample%_R1_pe.fastq.gz}
name=${sample##*/}
sortmerna --ref /home/admit1/scratch/Test/Scripts/silva-bac-16s-id90.fasta
          --ref /home/admit1/scratch/Test/Scripts/silva-bac-23s-id98.fasta
          --ref /home/admit1/scratch/Test/Scripts/rfam-5s-database-id98.fasta
          --ref /home/admit1/scratch/Test/Scripts/rfam-5.8s-database-id98.fasta
          --reads ${sample}_R1_pe.fastq.gz
          --reads ${sample}_R2_pe.fastq.gz
          --aligned ${Output}/${name}_rRNA_reads
          --other ${Output}/${name}_non_rRNA_reads
          --paired-in --log --threads 32
done

I have a warning to purge the kdvb files, how do I include it in my loop?
Also, is it possible to have a single file with the rRNAs found by all the noted references and a second file with the mRNAs also for all the references instead of one file per reference?

**Comment by biocodz** [comment]
You could call `rm -rf $HOME/kvdb/*` after `sortmerna ...` i.e. right before the closing `done`, so that the kvdb is purged at the end of each cycle.

The program has no option of reusing the output files, so you will have to combine them manually.
