### ISSUE TITLE
Job fails during alignment 

### ISSUE THREAD

**Issue by rpeguil** [biocore/sortmerna#355]
Hello,
I am trying to run sortmerna 4.3.6 on paired-end fasta files from Illumina sequencing with the following command (in a slurm script): 

`sortmerna --ref /softs/contrib/apps/anaconda/3/envs/sortmerna-4.3.6/rRNA_databases_v4.3.6/smr_v4.3_default_db.fasta --reads 594_R1_paired.fq.gz --reads 594_R2_paired.fq.gz --workdir /home/user/r/rpeguilhan/work/SortMeRNA/RNAseq/ --paired_out --out2`

But I received this error during alignment step and don't understand what is the issue :

`[process:1393] === Options processing starts ... ===
Found value: sortmerna
Found flag: --ref
Found value: /softs/contrib/apps/anaconda/3/envs/sortmerna-4.3.6/rRNA_databases_v4.3.6/smr_v4.3_default_db.fasta of previous flag: --ref
Found flag: --reads
Found value: 594_R1_paired.fq.gz of previous flag: --reads
Found flag: --reads
Found value: 594_R2_paired.fq.gz of previous flag: --reads
Found flag: --workdir
Found value: /home/user/r/rpeguilhan/work/SortMeRNA/RNAseq/ of previous flag: --workdir
Found flag: --paired_out
Previous flag: --paired_out is Boolean. Setting to True
Found flag: --out2
[opt_workdir:995] Using WORKDIR: "/home/user/r/rpeguilhan/work/SortMeRNA/RNAseq/" as specified
[process:1483] Processing option: out2 with value: 
[process:1483] Processing option: paired_out with value: 
[process:1483] Processing option: reads with value: 594_R1_paired.fq.gz
[opt_reads:98] Processing reads file [1] out of total [2] files
[process:1483] Processing option: reads with value: 594_R2_paired.fq.gz
[opt_reads:98] Processing reads file [2] out of total [2] files
[process:1483] Processing option: ref with value: /softs/contrib/apps/anaconda/3/envs/sortmerna-4.3.6/rRNA_databases_v4.3.6/smr_v4.3_default_db.fasta
[opt_ref:158] Processing reference [1] out of total [1] references
[opt_ref:206] File "/softs/contrib/apps/anaconda/3/envs/sortmerna-4.3.6/rRNA_databases_v4.3.6/smr_v4.3_default_db.fasta" exists and is readable
[process:1503] === Options processing done ===
[process:1504] Alignment type: [best:1 num_alignments:1 min_lis:2 seeds:2]
[validate_kvdbdir:1248] Key-value DB location "/home/user/r/rpeguilhan/work/SortMeRNA/RNAseq/kvdb"
[validate_kvdbdir:1284] Creating KVDB directory: "/home/user/r/rpeguilhan/work/SortMeRNA/RNAseq/kvdb"
[validate_idxdir:1214] Using index directory: "/home/user/r/rpeguilhan/work/SortMeRNA/RNAseq/idx"
[validate_idxdir:1222] Created index directory - OK
[validate_readb_dir:1306] Using split reads directory : "/home/user/r/rpeguilhan/work/SortMeRNA/RNAseq/readb"
[validate_readb_dir:1314] Created split reads directory - OK
[validate_aligned_pfx:1335] Checking output directory: "/home/user/r/rpeguilhan/work/SortMeRNA/RNAseq/out"
[validate:1533] No output format has been chosen (fastx|sam|blast|otu_map). Using default 'blast'
[validate:1569] Options 'paired_in' and 'paired_out' must be accompanied by option 'fastx'. Setting to true.
[main:62] Running command:
sortmerna --ref /softs/contrib/apps/anaconda/3/envs/sortmerna-4.3.6/rRNA_databases_v4.3.6/smr_v4.3_default_db.fasta --reads 594_R1_paired.fq.gz --reads 594_R2_paired.fq.gz --workdir /home/user/r/rpeguilhan/work/SortMeRNA/RNAseq/ --paired_out --out2 
[build_index:1127] ==== Index building started ====
[build_index:1190] Begin indexing file /softs/contrib/apps/anaconda/3/envs/sortmerna-4.3.6/rRNA_databases_v4.3.6/smr_v4.3_default_db.fasta of size: 146741693 under index name /home/user/r/rpeguilhan/work/SortMeRNA/RNAseq/idx/4383911207881337579
  done.

[build_index:2108] ==== Done index building in 652.709 sec ====

[init:108] Readfeed init started
[define_format:881] file: "594_R1_paired.fq.gz" is FASTQ gzipped
[define_format:881] file: "594_R2_paired.fq.gz" is FASTQ gzipped
[count_reads:915] started count  ...   
[next:322] EOF FWD reached. Total reads: 11927932
[next:322] EOF REV reached. Total reads: 11927932
[count_reads:945] done count. Elapsed time: 102.562 sec. Total reads: 23855864
[init_split_files:967] added file: /home/user/r/rpeguilhan/work/SortMeRNA/RNAseq/readb/fwd_0.fq.gz
[init_split_files:967] added file: /home/user/r/rpeguilhan/work/SortMeRNA/RNAseq/readb/rev_0.fq.gz
[init_split_files:967] added file: /home/user/r/rpeguilhan/work/SortMeRNA/RNAseq/readb/fwd_1.fq.gz
[init_split_files:967] added file: /home/user/r/rpeguilhan/work/SortMeRNA/RNAseq/readb/rev_1.fq.gz
[split:605] start splitting. Using number of splits equals number of processing threads: 2
[next:322] EOF FWD reached. Total reads: 11927932
[next:322] EOF REV reached. Total reads: 11927932
[split:717] Done splitting. Reads count: 23855864 Runtime sec: 1634.93

[init:135] Readfeed init done in sec [1737.58]
[store_to_db:292] Stored Reads statistics to DB:
     all_reads_count= 23855864 all_reads_len= 3363660887 min_read_len= 100 max_read_len= 151 total_aligned= 0 total_aligned_id= 0 total_aligned_cov= 0 total_aligned_id_cov= 0 total_denovo= 0 num_short= 0 reads_matched_per_db= TODO is_stats_calc= 0 is_total_reads_mapped_cov= 0

[align:143] ==== Starting alignment ====
[align:146] Number of cores: 32
[align:163] Using number of Processor threads: 2
[Refstats:60] Index Statistics calculation starts ... done in: 0.641792 sec
[align:185] Loading index: 0 part: 1/1 Memory KB: 7 ... 
[align:190] done in [5.72735] sec Memory KB: 3187
[align:193] Loading references ...
[align:197] done in [0.4143] sec. Memory KB: 3341
[align2:70] Processor 0 thread 47182524761856 started
[align2:70] Processor 1 thread 47182522660608 started
[next:455] EOF FWD reached. Total reads: 5963966
[next:455] EOF REV reached. Total reads: 5963966
[align2:133] Processor 0 thread 47182524761856 done. Processed 11927932 reads. Skipped already processed: 0 reads Aligned reads (passing E-value): 4952500 Runtime sec: 13611.2

[next:462] [0;31mERROR[0m: reading from FWD file. Exiting...
`

Thank you for your feedbacks.
Best

**Comment by biocodz** [comment]
Looks like a slurm related resource allocations problem similar to reported previously, e.g. issues [345](https://github.com/biocore/sortmerna/issues/345), [340](https://github.com/biocore/sortmerna/issues/340), [305](https://github.com/biocore/sortmerna/issues/305). All of which had problems with the HPC cluster resource allocations.
The trace shows the program had no problem reading the files because the split was done OK.
As a side note, I would recommend to increase the number of threads e.g. `-threads 8` as the files are fairly large.

**Comment by rpeguil** [comment]
Hello,
Thanks for the comment. Indeed, it was a problem of resource allocation. I respecified a minimum thread count of 2 in my slurm script (1 by default) and corrected the number of nodes used to 1 (I had tried using multiple nodes).
