### ISSUE TITLE
tmp file fixed to test.txt causes writing permission problem on a multi-user server

### ISSUE THREAD

**Issue by dawnmy** [biocore/sortmerna#48]
### tmp file fixed to test.txt causes writing permission problem on a multi-user server.
```bash
WARNING: no write permissions in directory /vol/tmp: Permission denied will try /tmp/.
ERROR: could not open /vol/tmp//tmp/sortmerna_keys_43918.txt file for writing
```
I think this problem involves the following source code in **indexdb.cpp**
```cpp
strcat(try_str,"test.txt");
FILE *tmp = fopen(try_str, "w+");
```

**Comment by ekopylova** [comment]
Resolved in PR #61.

Now the temporary 'test.txt' file is 'test_PID.txt' and should not cause issues on a multi-user server. Also, the temporary file is deleted if successfully written to the temporary directory.
