### ISSUE TITLE
No index file created

### ISSUE THREAD

**Issue by rmc7777** [biocore/sortmerna#51]
With Sortmerna v.2.0, when we run this command in the directory rRNA_databases:

indexdb_rna --ref rfam-5.8s-database-id98.fasta,rfam-5.8s-database-id98 -v

it creates these files

rfam-5.8s-database-id98.bursttrie_0.dat
rfam-5.8s-database-id98.kmer_0.dat
rfam-5.8s-database-id98.pos_0.dat
rfam-5.8s-database-id98.stats

but does not create the index file itself. Are we running the command correctly?  Where is the index file?

**Comment by ekopylova** [comment]
Documentation updated in SortMeRNA 3.0 to include this.
