### ISSUE TITLE
Few pb with the --best parameter

### ISSUE THREAD

**Issue by ppericard** [biocore/sortmerna#53]
“--best 0” → ERROR ?!?! (Should be all alignments found by SortMe for a given "--min_lis")

    ERROR: --best [INT] must be > 0. 

“--best 10” → OK

“--best 100000” → ERROR (This error message is weird)

    ERROR: --best [INT] must be > 0. 

“--best 1000000” → OK ?!?! O_o (I suspect an overflow...)

**Comment by ekopylova** [comment]
The option "--best 0" is not currently available (there's a mistake in the user manual that says it is). The maximum size for INT in --best [INT] is 32767 (int16_t). Both --best 100000 and --best 1000000 cause an overflow and unexpected behavior. Currently working on a solution.

**Comment by ekopylova** [comment]
Issue has been resolved.
Dynamic memory allocation has been implemented to increase the number of alignments stored on demand, rather than one-time allocation to the maximum allowed.

The option "--best 0 --min_lis 0" is also equivalent to "--num_alignments 0".
