### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by ajcardenasb** [biocore/sortmerna#68]
Hi, 

Im trying to sort my RNAs using the command below and all I have is a screen showing me the parameter options and the "--num_alignments" parameter in red. I tried changing or removing it but never works. I just want to separe rRNAs from non-rRNAs in fasta files.
Thanks
./sortmerna-2.0-linux-64/sortmerna --ref /home/acardenasb/software/sortmerna-2.0-linux-64/rRNA_databases/SILVA_119_LSU_SSU.fasta,/home/acardenasb/software/sortmerna-2.0-linux-64/index/SILVA_LSU_SSU --reads /home/acardenasb/SDOC/B1/out.extendedFrags.fastq --fastx /home/acardenasb/SDOC/B1/rRNA.fasta --other mRNA --log rRNA.filter.log --aligned aligmentsilva --sam --num_alignments 1

**Comment by ekopylova** [comment]
Hello,

The parameters --fastx and --log do not accept any input, they are boolean flags. The parameter --fastx states that you'd like to output fasta/fastq files and --log is for the output of the log file. Both --fastx and --log output files will have the prefix specified by --aligned STRING (so aligmentsilva.fastq (rRNA) and aligmentsilva.log). Non-rRNA output fastq file will be prefixed by the string 'mRNA'.

Can you try with the command:

./sortmerna-2.0-linux-64/sortmerna --ref /home/acardenasb/software/sortmerna-2.0-linux-64/rRNA_databases/SILVA_119_LSU_SSU.fasta,/home/acardenasb/software/sortmerna-2.0-linux-64/index/SILVA_LSU_SSU --reads /home/acardenasb/SDOC/B1/out.extendedFrags.fastq --aligned rRNA --other mRNA --sam --fastx --log --num_alignments 1

By the way, using the distributed databases (./rRNA_databases/) will render significantly faster filtering than using the complete SILVA database at a very small cost in precision. I would suggest only using the entire SILVA database if you would like more accurate alignments (I see you've specified --sam, however you mention that you just want to separate rRNA from non-rRNA sequences).

Let me know if this works,
Jenya

**Comment by ajcardenasb** [comment]
Dear Jenya,

Thank you so much for your response, the code is currently working. However
as you said before, I don't need the alignments I just need the fasta
files for my downstream processing, in that case removing the  --sam
parameter will skip the alignment file?
And regarding the databases, using the distributing databases forces me to
create index files for each?
Sorry for my limited experience in bioinformatics, I´m new in this field.
Thanks again for your help.
best,
Anny

On Sun, Feb 15, 2015 at 7:35 PM, Evguenia Kopylova <notifications@github.com

**Comment by ekopylova** [comment]
Hi Anny,

You can use one command to build indices from multiple fasta files (see User manual v2.0 section 4.1.2, Example 2 which shows exactly how to do that with the distributed databases).

Yes, removing the --sam parameter will skip the alignment file (see User manual v2.0 section 4.3.1, Example 3 which shows how to use the indexed distributed databases to filter rRNA. Remove the --sam parameter to skip alignments).

Hope this helps,
Jenya
