### ISSUE TITLE
SortmeRNA fails to map reads over 30M

### ISSUE THREAD

**Issue by ghoshal** [biocore/sortmerna#78]
Hi,
I have 30 Million reads in the fastq format and whenever I am trying to run sortmerna on these it is running forever. However when I run sortmerna on samples with less than 30 million reads its doing it within 1.5 hrs. Why is this happening? Can I specify any options? I am already using -a 4 -m 8192
Thanks in advance.

Thanks,

Biba

**Comment by ekopylova** [comment]
Hi Biba,

I believe the issue is with the -m 8192 parameter (see this [issue](https://github.com/biocore/sortmerna/issues/70)). Try using the default value for -m, or up to 4096 (should be almost as fast).

Jenya

**Comment by ghoshal** [comment]
Hi Jenya,

Thanks for the feedback. That really helped and solved the issue.

Thanks,

Biba
