### ISSUE TITLE
Issue with building

### ISSUE THREAD

**Issue by bebatut** [biocore/sortmerna#85]
Hi,
I just pulled the code and I have an issue for building with `build.sh`: 
```configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."````.

I have the feeling this issue come from the symbolink link in `install-sh` toward `/opt/local/share/automake-1.14/install-sh`.

Thanks
Bérénice

**Comment by ekopylova** [comment]
Hi Bérénice, I've replaced the symbolic links with the appropriate files. Please try to pull the latest changes and run "bash build.sh". Thanks for reporting the issue!

**Comment by pabloiturralde** [comment]
Hi, 

I get this exact same issue with the 2.1b version.
Please advise how to compile on cygwin64.

Thanks,
Pablo

**Comment by ekopylova** [comment]
Hello @pabloiturralde ,

Could you please paste the exact command used to build? Thanks!

Jenya
