### ISSUE TITLE
SortMeRNA stuck when more than 1 section

### ISSUE THREAD

**Issue by jejust** [biocore/sortmerna#87]
Hello,
I've tried SortMeRNA (commit a82b9253a3dbb3f9db3f75cea0ff5d3886890a26 of Aug 13, 2015) on a file containing  150460124 lines (6018149198 bytes). With options “-m 4096 -a 6”, it splits the input in 2 sections, but it gives no output after displaying this:

    Begin mmap reads section # 1:

I had it run for more than three days: it just ate 100% of one CPU without giving anything useful. If I manually split the file in two, SortMeRNA processes both halves in a few minutes.

I've tried to add debugging code to the file `paralleltraversal.cpp`, and apparently, there is an infinite loop here (near line 1948), but I'm not familiar enough with your code to provide a patch:

    for ( uint32_t i = reads_offset_f; i < partial_file_size; i++ ) if ( raw[i] == '\n' ) strs++;

I can provide the datafile privately if needed, or perform additional tests.

  Thank you for your work!
  Best regards,
Jérémy.

**Comment by ekopylova** [comment]
Hi Jérémy,

I'm currently working on resolving this [issue](https://github.com/biocore/sortmerna/issues/70) (you're correct about the infinite loop).

Thanks!

**Comment by ekopylova** [comment]
Hi Jérémy,
The error should be fixed, see issue #70 for more details. Please let me know if the latest master is not working for you. Thanks!
