### ISSUE TITLE
terminate called after throwing an instance of 'Sls::error'

### ISSUE THREAD

**Issue by wileyfox123** [biocore/sortmerna#93]
hi, i got this error after running through some RNAseq data.

user@it053392:~/Downloads/sortmerna-2.0$ time ./sortmerna --ref ./rRNA_databases/arb-silva.de_2015-10-26_id289745.fasta,./index/insecta --reads /home/user/Desktop/_sam/RNAseq_beta_data/fasta/10G87.fasta --sam --num_alignments 1 --fastx --aligned /home/user/Desktop/10G87_sortmerna 
terminate called after throwing an instance of 'Sls::error'
Aborted (core dumped)

real	1m7.628s
user	0m45.603s
sys	0m1.811s

i've got no idea about it, but someone reccomended it could be an issue with the C++ script and to report it here.

**Comment by ekopylova** [comment]
Hello,

Can you try running SortMeRNA with the verbose option (-v) to be sure at what step the program crashes? Without further info, this could be an error with the database index. I would suggest to remove the index from `./index/insecta`, rebuild it using `indexdb_rna` version 2.0 and try running SortMeRNA again.

Jenya

**Comment by wileyfox123** [comment]
Hi,

This is the terminal when I ran it with verbose on (attatched a screen
shot). How do I get hold of the version two of the indexdb?

Thanks,

Sam

On Tue, Oct 27, 2015 at 2:22 PM, Evguenia Kopylova <notifications@github.com

**Comment by ekopylova** [comment]
Hi Sam,

It seems that attachments are not added when replying via e-mail. Can you send me the screenshot by e-mail or attach it again using this website?

Thanks!

**Comment by wileyfox123** [comment]
Hi,

Tried it again - how's that? If not I'll do it on the website.

Thanks,

Sam

**Comment by ekopylova** [comment]
I still don't see any attachments ..

**Comment by wileyfox123** [comment]
![screenshot from 2015-10-27 14 33 01](https://cloud.githubusercontent.com/assets/15343404/10784778/e6a739c2-7d57-11e5-80f2-6d0c7d183af7.png)

How's that?

**Comment by ekopylova** [comment]
Hi!

If you downloaded SortMeRNA 2.0, then the indexdb_rna in that package is version 2.0. I've seen the error that you're showing when users called the binary `indexdb_rna` from another SortMeRNA version (ex. 1.9) together with the binary `sortmerna` from SortMeRNA version 2.0. Have you tried to remove your indexes, re-build them with `indexdb_rna` from the sortmerna 2.0 package and launch `sortmerna` again (from the same package)?

**Comment by wileyfox123** [comment]
Hi,

Yes I've just done that and it came up with the same problem. I've only installed version 2 of SortMeRNA and only used the indexdb_rna from this package, so I'm not sure how I would have called the binary a different package?

**Comment by ekopylova** [comment]
hmm, could you also attach the verbose output (-v) of `indexdb_rna` for constructing the index `./index/insecta`? Thanks!

**Comment by wileyfox123** [comment]
![screenshot from 2015-10-28 11 42 36](https://cloud.githubusercontent.com/assets/15343404/10787466/072b71ca-7d69-11e5-8f02-e9d232da5a4f.png)

**Comment by ekopylova** [comment]
and if you add the `--log` option to the `sortmerna command`, is the log file empty after the program exists with the error?

**Comment by ekopylova** [comment]
also, could you try running with a different set of reads (other than `10G87.fasta`) and the same database `--ref ./rRNA_databases/arb-silva.de_2015-10-26_id289745.fasta,./index/insecta`? Thanks!

**Comment by wileyfox123** [comment]
Yes, the log is empty. Just tried running it with another FASTA file and the same error occurs. Thanks for your time btw!

**Comment by ekopylova** [comment]
Could you send me `arb-silva.de_2015-10-26_id289745.fasta`? I'd like to see if I can reproduce the error on my end. Seems the error is caused by the database during Gumbel parameter calculation. I can quickly debug with the file at hand. Thanks!

**Comment by wileyfox123** [comment]
Hi,

I'll try again with the attatchments! Hopefully it'll work this time.

Sam

**Comment by wileyfox123** [comment]
Just realised that I'm attaching them on the email rather than on the forum
- can you access the email I sent to get the attatchment? I think thats why
it wasnt working.

**Comment by ekopylova** [comment]
I don't see any attachments on the website, or via e-mail. You can also send it directly to my e-mail account (jenya dot kopylov at gmail dot com).

**Comment by ekopylova** [comment]
In the meanwhile, could you try indexing one of the provided databases (in folder `rRNA_databases`) and run the same `sortmerna` command with that database instead of `arb-silva.de_2015-10-26_id289745.fasta`?

**Comment by ekopylova** [comment]
hmm, looking at `arb-silva.de_2015-10-26_id289745.fasta`, there is one sequence and it is in multiple aligned format. That's probably the issue as SortMeRNA was written to support only the standard FASTA sequence format. I agree it is misleading because you're not getting an error during indexing, which is something I will need to look at and fix.

**Comment by wileyfox123** [comment]
OK, thanks for helping sort it. Do you know if there is any way I can
convert it from multiple aligned format to standard FASTA format?

Best,

Sam

**Comment by wileyfox123** [comment]
It's OK, found one!
