### ISSUE TITLE
can we add support for gziped fastQ files?

### ISSUE THREAD

**Issue by etheleon** [biocore/sortmerna#94]
currently cant feed sortmerna with fq.gz directly

**Comment by ekopylova** [comment]
Thanks for submitting this! This functionality is planned for the next release.

**Comment by etheleon** [comment]
and output files as well! :+1:

**Comment by ekopylova** [comment]
Option ```--reads-gz``` has been added to allow for .zip or .gz input files. You can use this new functionality in the master version. A new release will soon include this and many other updates. Thanks!

**Comment by etheleon** [comment]
thanks! appreciate this!

**Comment by ralomba** [comment]
Is this feature available on v2.1 release?

**Comment by ekopylova** [comment]
No it is not, however it is available in the current development version for which a release is coming shortly. We will also provide a DNAnexus app where you can leverage cloud services and launch SortMeRNA without manual installation.

Thanks,
Jenya

**Comment by olechnwin** [comment]
Hi,
I have paired reads thus I need to use merge-paired-reads.sh. My files are compressed (i.e. .gz). Does merge-paired-reads.sh support .gz files?
