### ISSUE TITLE
Blank rRNA directory

### ISSUE THREAD

**Issue by ghoshal** [biocore/sortmerna#95]
Hi,

I am running the sortmerna program and getting the output file that is not rRNA. However the directory that I am specifying for having all the rRNA information is blank and even the LOG file is not getting generated.

Here is the command I am using.

~/Downloads/Softwares/sortmerna-2.0-mac-os-64-multithread/sortmerna --ref /Users/biba/Downloads/Softwares/sortmerna-2.0-mac-os-64-multithread/rRNA_databases/silva-bac-16s-id90.fasta,/Users/biba/Downloads/Softwares/sortmerna-2.0-mac-os-64-multithread/index/silva-bac-16s-db:/Users/biba/Downloads/Softwares/sortmerna-2.0-mac-os-64-multithread/rRNA_databases/silva-bac-23s-id98.fasta,/Users/biba/Downloads/Softwares/sortmerna-2.0-mac-os-64-multithread/index/silva-bac-23s-db:/Users/biba/Downloads/Softwares/sortmerna-2.0-mac-os-64-multithread/rRNA_databases/silva-arc-16s-id95.fasta,/Users/biba/Downloads/Softwares/sortmerna-2.0-mac-os-64-multithread/index/silva-arc-16s-db:/Users/biba/Downloads/Softwares/sortmerna-2.0-mac-os-64-multithread/rRNA_databases/silva-arc-23s-id98.fasta,/Users/biba/Downloads/Softwares/sortmerna-2.0-mac-os-64-multithread/index/silva-arc-23s-db:/Users/biba/Downloads/Softwares/sortmerna-2.0-mac-os-64-multithread/rRNA_databases/silva-euk-18s-id95.fasta,/Users/biba/Downloads/Softwares/sortmerna-2.0-mac-os-64-multithread/index/silva-euk-18s-db:/Users/biba/Downloads/Softwares/sortmerna-2.0-mac-os-64-multithread/rRNA_databases/silva-euk-28s-id98.fasta,/Users/biba/Downloads/Softwares/sortmerna-2.0-mac-os-64-multithread/index/silva-euk-28s
--reads filtered_129.fastq --fastx --sam --num_alignments 1 --aligned 129_rRNA/ --other filtered_129_norrna -a 4 -m 8192 --log -v

Any help will be greatly appreciated.

Thanks,

Bibaswan

**Comment by ekopylova** [comment]
Hi Bibaswan,

The issue could be the `-m 8192` parameter (see closed issue #70 for more info). In version 2.0 there is a bug that does not allow SortMeRNA to run with `-m > 4096`. If you would like to continue using 2.0, simply remove this parameter from your command. Otherwise, you can clone the current development version of SortMeRNA where the bug has been resolved and continue passing `-m 8192`.

Let me know if the command works after either of these suggestions.
Thanks!

**Comment by ghoshal** [comment]
Hi,

I tried both the methods. First, I removed the -m 8192 and ran the program with the defaults and again I got a blank directory created. Then I upgraded to the development version 2.1 and ran it with -m 8192 and got the same result. Both time, the program completed its run and filtered the non rRNA sequences out. This is the exact command I ran.

~/Downloads/Softwares/sortmerna/sortmerna --ref /Users/biba/Downloads/Softwares/sortmerna-2.0-mac-os-64-multithread/rRNA_databases/silva-bac-16s-id90.fasta,/Users/biba/Downloads/Softwares/sortmerna-2.0-mac-os-64-multithread/index/silva-bac-16s-db:/Users/biba/Downloads/Softwares/sortmerna-2.0-mac-os-64-multithread/rRNA_databases/silva-bac-23s-id98.fasta,/Users/biba/Downloads/Softwares/sortmerna-2.0-mac-os-64-multithread/index/silva-bac-23s-db:/Users/biba/Downloads/Softwares/sortmerna-2.0-mac-os-64-multithread/rRNA_databases/silva-arc-16s-id95.fasta,/Users/biba/Downloads/Softwares/sortmerna-2.0-mac-os-64-multithread/index/silva-arc-16s-db:/Users/biba/Downloads/Softwares/sortmerna-2.0-mac-os-64-multithread/rRNA_databases/silva-arc-23s-id98.fasta,/Users/biba/Downloads/Softwares/sortmerna-2.0-mac-os-64-multithread/index/silva-arc-23s-db:/Users/biba/Downloads/Softwares/sortmerna-2.0-mac-os-64-multithread/rRNA_databases/silva-euk-18s-id95.fasta,/Users/biba/Downloads/Softwares/sortmerna-2.0-mac-os-64-multithread/index/silva-euk-18s-db:/Users/biba/Downloads/Softwares/sortmerna-2.0-mac-os-64-multithread/rRNA_databases/silva-euk-28s-id98.fasta,/Users/biba/Downloads/Softwares/sortmerna-2.0-mac-os-64-multithread/index/silva-euk-28s --reads filtered_129.fastq --fastx --aligned 129_rRNA/ -a 4 -m 8192 --log -v

Please advise on what to do.

Thanks,

Bibaswan

**Comment by ekopylova** [comment]
Hi Bibaswan,

Can you try this simple command (use only 1 database and remove the '/' after 129_rRNA) and see whether you get results. The '/' could be the reason you're getting an empty directory. The output should be only files, in your case `129_rRNA.fastq` and `129_rRNA.log`.

`~/Downloads/Softwares/sortmerna/sortmerna --ref /Users/biba/Downloads/Softwares/sortmerna-2.0-mac-os-64-multithread/rRNA_databases/silva-bac-16s-id90.fasta,/Users/biba/Downloads/Softwares/sortmerna-2.0-mac-os-64-multithread/index/silva-bac-16s-db --reads filtered_129.fastq --fastx --aligned 129_rRNA -a 4 --log -v`

Thanks,
Jenya

**Comment by ghoshal** [comment]
Hi Jenya,

That worked. I think the problem was it was detecting the output as a directory.

Thanks a lot.

Bibaswan
