### ISSUE TITLE
outfiles not written

### ISSUE THREAD

**Issue by DanielJamesWhite** [biocore/sortmerna#97]
I am working with sortmerna 2.0 to filter rRNA in 64 bit linux and ran the command
./sortmerna --ref ./rRNA_databases/nrsilva_rrna.fasta,./index/nrsilva_rrna --reads exp1.fasta --aligned ./exp1_rRNA --other ./exp1_no_rRNA -m 4096 --log
which seemed to go well, and the log file showed rRNA was found.
But I can't find my --aligned or --other output in the cwd or anywhere else.
Where do I find these? Many thanks
Daniel

**Comment by ekopylova** [comment]
Hi Daniel,

You need to specify the output format, `--sam`, `--blast OPTIONS` or `--fastx` as well. See the manual (`sortmerna -h`) for more details. Let me know if that doesn't fix the issue.

Jenya

**Comment by DanielJamesWhite** [comment]
Thanks Jenya. It works smoothly now. Very quick response too!
