### ISSUE TITLE
no subject strand information about the output in BLAST m8 format

### ISSUE THREAD

**Issue by ShannonDaddy** [biocore/sortmerna#98]
Dear sortmerna maintainers!

I ran sortmerna as follows:
/home/Softwares/sortmerna-2.0-linux-64/sortmerna --ref 99_otus.fasta,99_otus_db --reads OTU_rep_seqs.fasta --aligned sortmerna_align.out --blast 1 --best 20

and --blast 1 stands for '1 - tabular (Blast -m 8 format)' as specified in the sortmerna help.

Part of the the aligned output file looks like:
OTU2    345114  99      420     4       0       1       420     353     772     2.12e-201       712
OTU2    4455257 99      420     4       0       1       420     310     729     2.12e-201       712
OTU2    4365470 99      420     4       0       1       420     315     734     2.12e-201       712
OTU2    4343720 99      420     4       0       1       420     310     729     2.12e-201       712
OTU2    4314505 99      420     4       0       1       420     333     752     2.12e-201       712
OTU2    1676534 99      420     4       0       1       420     315     734     2.12e-201       712

the meanings of the columns are:
Query id,Subject id,% identity,alignment length,mismatches,gap openings,q. start,q. end,s. start,s. end,e-value,bit score

I found that s. start is always smaller than s. end, even the query is aligned to the reverse strand of the subject, so there is no strand information of the subject sequences. Actually, the query 'OTU2' is aligned to the reverse strands of the subjects.

For comparison, I used another search tools usearch in usearch_local mode, and part of the result is:
OTU2    1676534 99.0    420     4       0       13      432     734     315     9.4e-217        754.6
OTU2    4343720 99.0    420     4       0       13      432     729     310     9.4e-217        754.6
OTU2    4314505 99.0    420     4       0       13      432     752     333     9.4e-217        754.6
OTU2    4365470 99.0    420     4       0       13      432     734     315     9.4e-217        754.6
OTU2    4455257 99.0    420     4       0       13      432     729     310     9.4e-217        754.6
OTU2    345114  99.0    420     4       0       13      432     772     353     9.4e-217        754.6

Is this a bug or something?  Can't wait for your help, thank you.

ShannonDaddy

**Comment by ekopylova** [comment]
Hello,

Could you paste the FASTA string for OTU2?

Thanks!
Jenya

**Comment by ekopylova** [comment]
Hi again,

For SortMeRNA, the read is reverse complemented and then aligned against the forward strand reference database. The "+" or "-" symbols with the ``--blast '1 cigar qcov qstrand' `` option in version 2.1 show the direction of the read (forward or reverse complement).

Let me know if you need further information,
Jenya
